24
(Lift hoist2 crate1 pallet5 distributor1)
(Lift hoist3 crate8 pallet5 distributor0)
(Lift hoist0 crate11 crate6 depot0)
(Load hoist1 crate3 truck0 depot1)
(Lift hoist4 crate5 pallet0 distributor1)
(Lift hoist0 crate4 crate0 depot0)
(Lift hoist2 crate9 crate8 depot2)
(Lift hoist4 crate9 crate7 distributor1)
(Drop hoist1 crate3 crate9 distributor0)
(Lift hoist3 crate0 pallet0 distributor0)
(Lift hoist2 crate2 crate0 distributor1)
(Drop hoist4 crate5 pallet2 distributor1)
(Drop hoist2 crate2 pallet5 distributor1)
(Lift hoist1 crate7 crate4 distributor0)
(Drop hoist3 crate8 pallet3 distributor0)
(Drop hoist2 crate1 pallet4 distributor1)
(Drop hoist3 crate0 crate7 distributor0)
(Drop hoist0 crate4 pallet0 depot0)
(Drop hoist2 crate9 crate2 depot2)
(Lift hoist0 crate6 crate3 depot0)
(Drop hoist0 crate6 crate5 depot0)
(Load hoist1 crate7 truck1 depot1)
(Unload hoist0 crate7 truck1 depot0)
(Drop hoist0 crate7 crate1 depot0)
36
(:init
	(on crate7 crate4)
	(at crate4 distributor1)
	(on crate12 crate9)
	(at truck1 depot1)
	(at crate6 distributor0)
	(at crate3 distributor1)
	(clear crate4)
	(on crate1 pallet5)
	(on crate6 crate3)
	(at crate5 depot2)
	(clear pallet2)
	(at crate11 depot0)
	(on crate12 crate11)
	(on crate1 pallet2)
	(clear crate5)
	(clear crate12)
	(on crate14 crate13)
	(on crate9 crate7)
	(at crate5 depot0)
	(at crate13 distributor0)
	(at hoist2 distributor1)
	(clear pallet4)
	(at hoist4 distributor1)
	(on crate5 crate4)
	(at crate0 distributor1)
	(at crate9 distributor0)
	(on crate6 pallet1)
	(on crate9 crate8)
	(at crate8 depot0)
	(clear crate10)
	(on crate4 crate2)
	(on crate4 crate3)
	(at crate5 distributor1)
	(on crate0 pallet1)
	(at crate2 depot2)
	(at crate7 distributor2)
	(clear crate8)
	(at pallet4 distributor1)
	(on crate4 crate0)
	(on crate5 pallet0)
	(at truck0 distributor0)
	(on crate11 pallet4)
	(on crate14 crate9)
	(clear crate9)
	(clear crate11)
	(on crate3 crate1)
	(at crate2 distributor1)
	(on crate7 crate6)
	(at pallet3 distributor0)
	(at crate12 distributor0)
	(at crate2 depot0)
	(at crate7 distributor0)
	(at crate8 distributor0)
	(at pallet2 depot2)
	(on crate3 crate2)
	(on crate0 pallet0)
	(clear pallet3)
	(on crate3 pallet1)
	(on crate13 crate12)
	(at hoist1 distributor0)
	(available hoist2)
	(on crate5 crate2)
	(at crate9 depot2)
	(at crate8 distributor2)
	(at pallet5 depot0)
	(on crate11 crate6)
	(at pallet5 distributor2)
	(at pallet0 depot0)
	(on crate8 crate7)
	(clear crate2)
	(at truck0 depot0)
	(at truck0 distributor1)
	(at pallet4 distributor0)
	(on crate13 crate4)
	(on crate6 pallet5)
	(at crate10 distributor1)
	(on crate0 pallet2)
	(at crate11 distributor0)
	(at crate4 depot0)
	(clear crate1)
	(at hoist5 distributor2)
	(available hoist3)
	(at crate0 depot0)
	(on crate1 pallet0)
	(at pallet1 distributor0)
	(clear crate0)
	(at truck0 depot1)
	(at pallet3 distributor1)
	(on crate0 pallet4)
	(on crate2 crate0)
	(at pallet2 distributor1)
	(at pallet5 distributor1)
	(available hoist4)
	(at crate0 depot1)
	(at pallet1 depot1)
	(at crate4 depot2)
	(on crate5 pallet3)
	(clear crate13)
	(lifting hoist1 crate3)
	(on crate9 crate5)
	(available hoist5)
	(at crate1 depot0)
	(at hoist0 depot0)
	(clear pallet1)
	(on crate2 pallet2)
	(on crate2 crate1)
	(at hoist3 distributor0)
	(at crate3 distributor0)
	(at crate13 distributor1)
	(at crate4 distributor0)
	(at crate3 depot0)
	(available hoist0)
	(on crate10 crate5)
	(at crate6 depot0)
	(at crate6 distributor2)
	(at crate1 distributor1)
	(clear crate14)
	(at hoist2 depot2)
	(at truck1 depot0)
	(on crate6 crate1)
	(at crate0 distributor0)
	(at hoist1 depot1)
	(on crate8 pallet5)
	(at crate9 distributor1)
	(at crate14 distributor0)
)
(:add
	(clear pallet0)
	(lifting hoist3 crate0)
	(available hoist2)
	(clear crate9)
	(at crate9 depot2)
	(on crate9 crate2)
	(lifting hoist0 crate7)
	(at crate6 depot0)
	(available hoist0)
	(on crate6 crate5)
	(clear crate6)
	(clear pallet5)
	(lifting hoist3 crate8)
	(lifting hoist2 crate9)
	(clear crate8)
	(clear pallet5)
	(lifting hoist2 crate1)
	(available hoist2)
	(clear crate1)
	(at crate1 distributor1)
	(on crate1 pallet4)
	(clear pallet0)
	(lifting hoist4 crate5)
	(in crate3 truck0)
	(available hoist1)
	(clear crate4)
	(lifting hoist1 crate7)
	(on crate5 pallet2)
	(at crate5 distributor1)
	(clear crate5)
	(available hoist4)
	(lifting hoist2 crate2)
	(clear crate0)
	(on crate2 pallet5)
	(available hoist2)
	(clear crate2)
	(at crate2 distributor1)
	(clear crate4)
	(at crate4 depot0)
	(available hoist0)
	(on crate4 pallet0)
	(in crate7 truck1)
	(available hoist1)
	(on crate3 crate9)
	(at crate3 distributor0)
	(clear crate3)
	(available hoist1)
	(on crate7 crate1)
	(clear crate7)
	(available hoist0)
	(at crate7 depot0)
	(on crate8 pallet3)
	(at crate8 distributor0)
	(available hoist3)
	(clear crate8)
	(lifting hoist0 crate6)
	(clear crate3)
	(clear crate7)
	(lifting hoist4 crate9)
	(lifting hoist0 crate11)
	(clear crate6)
	(at crate0 distributor0)
	(clear crate0)
	(on crate0 crate7)
	(available hoist3)
	(clear crate0)
	(lifting hoist0 crate4)
)
(:delete
	(at crate0 distributor0)
	(clear crate0)
	(available hoist3)
	(on crate0 pallet0)
	(lifting hoist2 crate9)
	(clear crate2)
	(in crate7 truck1)
	(available hoist0)
	(lifting hoist0 crate6)
	(clear crate5)
	(at crate8 distributor0)
	(available hoist3)
	(on crate8 pallet5)
	(clear crate8)
	(available hoist2)
	(clear crate9)
	(at crate9 depot2)
	(on crate9 crate8)
	(on crate1 pallet5)
	(available hoist2)
	(clear crate1)
	(at crate1 distributor1)
	(lifting hoist2 crate1)
	(clear pallet4)
	(on crate5 pallet0)
	(at crate5 distributor1)
	(clear crate5)
	(available hoist4)
	(lifting hoist1 crate3)
	(on crate7 crate4)
	(clear crate7)
	(at crate7 distributor0)
	(available hoist1)
	(lifting hoist4 crate5)
	(clear pallet2)
	(on crate2 crate0)
	(available hoist2)
	(clear crate2)
	(at crate2 distributor1)
	(lifting hoist2 crate2)
	(clear pallet5)
	(clear pallet0)
	(lifting hoist0 crate4)
	(lifting hoist1 crate7)
	(clear crate9)
	(lifting hoist1 crate3)
	(clear crate1)
	(lifting hoist0 crate7)
	(clear pallet3)
	(lifting hoist3 crate8)
	(at crate6 depot0)
	(on crate6 crate3)
	(available hoist0)
	(clear crate6)
	(at crate9 distributor1)
	(clear crate9)
	(on crate9 crate7)
	(available hoist4)
	(on crate11 crate6)
	(available hoist0)
	(clear crate11)
	(at crate11 depot0)
	(lifting hoist3 crate0)
	(clear crate7)
	(on crate4 crate0)
	(clear crate4)
	(at crate4 depot0)
	(available hoist0)
)
(:goal
	(on crate3 crate9)
	(on crate5 pallet2)
	(on crate8 pallet3)
	(on crate7 crate1)
	(on crate2 pallet5)
	(on crate1 pallet4)
	(on crate6 crate5)
	(on crate4 pallet0)
	(on crate0 crate7)
	(on crate9 crate2)
)
(:current
)
