12
(Drive truck1 distributor2 distributor0)
(Drop hoist2 crate5 pallet2 depot2)
(Drive truck1 distributor2 depot0)
(Drop hoist5 crate2 pallet5 distributor2)
(Drive truck1 distributor2 distributor1)
(Lift hoist1 crate12 crate9 distributor0)
(Unload hoist4 crate6 truck1 distributor1)
(Unload hoist0 crate9 truck1 depot0)
(Unload hoist3 crate3 truck1 distributor0)
(Drop hoist4 crate6 crate5 distributor1)
(Drop hoist0 crate9 crate2 depot0)
(Drop hoist3 crate3 crate9 distributor0)
-3
(:init
	(on crate7 crate4)
	(at crate4 distributor1)
	(on crate12 crate9)
	(at crate3 distributor1)
	(at crate6 distributor0)
	(on crate1 pallet5)
	(clear crate4)
	(on crate6 crate3)
	(clear pallet2)
	(at crate11 depot0)
	(on crate1 pallet2)
	(on crate12 crate11)
	(clear pallet5)
	(clear crate12)
	(on crate14 crate13)
	(at crate5 depot0)
	(on crate9 crate7)
	(on crate0 crate7)
	(at crate13 distributor0)
	(at hoist2 distributor1)
	(at hoist4 distributor1)
	(at crate0 distributor1)
	(at crate9 distributor0)
	(in crate6 truck1)
	(on crate6 pallet1)
	(on crate9 crate8)
	(at crate8 depot0)
	(lifting hoist2 crate5)
	(clear crate10)
	(on crate4 crate3)
	(at crate5 distributor1)
	(clear crate8)
	(lifting hoist5 crate2)
	(at pallet4 distributor1)
	(on crate4 crate0)
	(on crate5 pallet0)
	(at truck0 distributor0)
	(on crate11 pallet4)
	(on crate14 crate9)
	(clear crate11)
	(on crate3 crate1)
	(at crate2 distributor1)
	(at pallet3 distributor0)
	(at crate12 distributor0)
	(at crate2 depot0)
	(at crate7 distributor0)
	(at crate8 distributor0)
	(at pallet2 depot2)
	(on crate4 pallet0)
	(on crate3 crate2)
	(on crate0 pallet0)
	(on crate8 pallet3)
	(on crate3 pallet1)
	(on crate1 pallet4)
	(on crate13 crate12)
	(at hoist1 distributor0)
	(on crate5 crate2)
	(at pallet5 depot0)
	(on crate11 crate6)
	(at pallet5 distributor2)
	(at pallet0 depot0)
	(in crate9 truck1)
	(available hoist1)
	(at truck0 depot0)
	(at pallet4 distributor0)
	(at truck0 distributor1)
	(on crate13 crate4)
	(at crate10 distributor1)
	(on crate0 pallet2)
	(at crate11 distributor0)
	(at crate4 depot0)
	(at hoist5 distributor2)
	(available hoist3)
	(at crate0 depot0)
	(at crate7 distributor1)
	(at pallet1 distributor0)
	(clear crate0)
	(at truck0 depot1)
	(at pallet3 distributor1)
	(on crate2 crate0)
	(on crate0 pallet4)
	(at pallet2 distributor1)
	(at pallet5 distributor1)
	(available hoist4)
	(at truck1 distributor2)
	(at pallet1 depot1)
	(on crate5 pallet3)
	(clear crate13)
	(in crate3 truck1)
	(at hoist0 depot0)
	(clear pallet1)
	(on crate2 crate1)
	(at hoist3 distributor0)
	(at crate3 distributor0)
	(on crate7 crate1)
	(at crate13 distributor1)
	(at crate4 distributor0)
	(at crate3 depot0)
	(available hoist0)
	(on crate10 crate5)
	(at crate6 depot0)
	(at crate1 distributor1)
	(clear crate14)
	(at hoist2 depot2)
	(on crate6 crate1)
	(at crate0 distributor0)
	(at hoist1 depot1)
	(on crate8 pallet5)
	(at crate9 distributor1)
	(at crate14 distributor0)
)
(:add
	(at truck1 distributor1)
	(at crate6 distributor1)
	(on crate6 crate5)
	(clear crate6)
	(available hoist4)
	(lifting hoist4 crate6)
	(on crate5 pallet2)
	(available hoist2)
	(at crate5 depot2)
	(clear crate5)
	(lifting hoist3 crate3)
	(on crate2 pallet5)
	(available hoist5)
	(at crate2 distributor2)
	(clear crate2)
	(clear crate9)
	(available hoist0)
	(at crate9 depot0)
	(on crate9 crate2)
	(lifting hoist0 crate9)
	(on crate3 crate9)
	(at crate3 distributor0)
	(clear crate3)
	(available hoist3)
	(lifting hoist1 crate12)
	(clear crate9)
	(at truck1 distributor0)
	(at truck1 depot0)
)
(:delete
	(at truck1 distributor2)
	(lifting hoist4 crate6)
	(clear crate5)
	(in crate6 truck1)
	(available hoist4)
	(clear pallet2)
	(lifting hoist2 crate5)
	(in crate3 truck1)
	(available hoist3)
	(lifting hoist5 crate2)
	(clear pallet5)
	(lifting hoist0 crate9)
	(clear crate2)
	(in crate9 truck1)
	(available hoist0)
	(clear crate9)
	(lifting hoist3 crate3)
	(at crate12 distributor0)
	(on crate12 crate9)
	(available hoist1)
	(clear crate12)
	(at truck1 distributor2)
	(at truck1 distributor2)
)
(:goal
	(on crate3 crate9)
	(on crate5 pallet2)
	(on crate8 pallet3)
	(on crate7 crate1)
	(on crate2 pallet5)
	(on crate1 pallet4)
	(on crate6 crate5)
	(on crate4 pallet0)
	(on crate0 crate7)
	(on crate9 crate2)
)
(:current
	(on crate0 crate7)
	(on crate4 pallet0)
	(on crate8 pallet3)
	(on crate1 pallet4)
	(on crate7 crate1)
)
