10
(Unload hoist4 crate1 truck4 distributor1)
(Unload hoist1 crate3 truck5 depot1)
(Lift hoist6 crate5 crate3 distributor2)
(Lift hoist11 crate2 pallet2 distributor5)
(Unload hoist5 crate8 truck5 depot1)
(Drop hoist5 crate8 pallet15 depot1)
(Drop hoist6 crate5 pallet5 depot0)
(Drop hoist4 crate1 pallet7 distributor1)
(Drop hoist11 crate2 pallet11 distributor5)
(Drop hoist1 crate3 pallet3 distributor0)
9
(:init
	(on crate7 crate6)
	(at crate4 distributor2)
	(clear crate10)
	(on crate14 crate9)
	(on crate4 pallet0)
	(clear pallet17)
	(clear pallet4)
	(at pallet12 distributor1)
	(on crate13 crate9)
	(at hoist6 distributor0)
	(on crate1 pallet4)
	(on crate4 pallet1)
	(at hoist4 distributor1)
	(clear pallet15)
	(clear crate12)
	(clear pallet5)
	(at hoist5 depot5)
	(in crate1 truck4)
	(on crate9 pallet2)
	(clear pallet2)
	(at crate4 distributor1)
	(at crate6 distributor0)
	(on crate9 pallet3)
	(at hoist6 distributor2)
	(at truck1 distributor1)
	(on crate13 crate7)
	(on crate4 crate0)
	(on crate6 pallet0)
	(on crate9 crate7)
	(at hoist7 distributor3)
	(clear pallet3)
	(on crate0 pallet9)
	(on crate9 crate8)
	(at crate11 distributor1)
	(on crate6 pallet1)
	(clear crate11)
	(on crate4 crate2)
	(on crate1 crate0)
	(at pallet9 depot3)
	(on crate9 pallet19)
	(at hoist7 distributor1)
	(clear pallet11)
	(on crate7 crate4)
	(on crate7 crate5)
	(at crate4 depot1)
	(on crate1 pallet5)
	(at pallet9 depot0)
	(clear pallet14)
	(at pallet7 depot1)
	(on crate0 pallet8)
	(on crate1 pallet2)
	(clear pallet6)
	(at pallet1 distributor0)
	(clear pallet7)
	(at pallet10 distributor4)
	(at crate11 distributor2)
	(at pallet2 distributor1)
	(at pallet9 depot2)
	(on crate6 crate1)
	(on crate11 pallet8)
	(at hoist6 depot1)
	(on crate4 pallet2)
	(on crate2 pallet8)
	(at pallet16 depot1)
	(at crate11 distributor0)
	(on crate12 crate6)
	(on crate9 crate5)
	(on crate4 pallet3)
	(at crate6 depot1)
	(at truck3 depot0)
	(at pallet5 depot0)
	(on crate6 pallet7)
	(at pallet4 depot4)
	(at hoist4 distributor0)
	(at crate7 depot4)
	(on crate7 pallet18)
	(at pallet8 distributor1)
	(at crate1 depot2)
	(at pallet2 distributor0)
	(at crate13 depot0)
	(at crate6 distributor2)
	(clear pallet0)
	(at crate1 distributor1)
	(on crate7 pallet3)
	(at crate13 depot2)
	(at crate6 distributor1)
	(at crate4 distributor0)
	(clear pallet1)
	(on crate11 crate1)
	(at pallet1 depot1)
	(on crate9 pallet7)
	(clear crate13)
	(at hoist8 distributor2)
	(at hoist0 depot0)
	(on crate4 pallet6)
	(at crate9 distributor0)
	(on crate4 pallet8)
	(at crate8 depot0)
	(on crate14 crate12)
	(at pallet7 depot0)
	(on crate10 crate0)
	(on crate13 crate12)
	(at crate7 depot1)
	(in crate8 truck5)
	(on crate8 pallet3)
	(at crate9 distributor2)
	(on crate14 crate11)
	(at crate11 depot0)
	(on crate4 crate3)
	(at pallet11 distributor5)
	(at hoist14 depot4)
	(on crate2 pallet3)
	(at pallet8 depot1)
	(at crate12 depot1)
	(on crate14 crate13)
	(at pallet19 depot1)
	(at pallet17 distributor2)
	(at crate12 distributor0)
	(at crate8 distributor0)
	(on crate12 crate9)
	(at pallet9 distributor0)
	(on crate3 pallet5)
	(on crate6 crate3)
	(at crate10 depot1)
	(on crate10 crate1)
	(clear crate0)
	(at crate10 distributor3)
	(at crate4 depot0)
	(at pallet3 depot3)
	(at crate9 depot1)
	(at hoist4 depot4)
	(at pallet6 depot1)
	(on crate2 pallet0)
	(clear crate2)
	(on crate12 crate2)
	(at crate10 distributor1)
	(at hoist6 depot0)
	(on crate8 pallet1)
	(at crate8 distributor2)
	(at pallet0 depot0)
	(on crate5 crate0)
	(available hoist7)
	(on crate6 pallet12)
	(clear crate14)
	(at crate6 depot0)
	(at hoist2 depot2)
	(at crate2 distributor5)
	(at hoist12 depot5)
	(on crate5 crate2)
	(at crate12 distributor1)
	(on crate13 crate3)
	(at crate4 depot2)
	(on crate8 crate7)
	(on crate5 crate1)
	(at hoist4 depot0)
	(on crate13 crate4)
	(on crate3 crate1)
	(at crate0 distributor1)
	(clear crate6)
	(on crate3 pallet0)
	(at truck2 depot2)
	(on crate0 pallet0)
	(at pallet8 depot2)
	(at pallet7 distributor1)
	(on crate3 crate2)
	(on crate3 pallet1)
	(at truck4 distributor1)
	(at hoist2 distributor1)
	(on crate0 pallet1)
	(clear crate5)
	(available hoist14)
	(at hoist9 distributor3)
	(at truck2 depot0)
	(on crate3 crate0)
	(at crate3 distributor1)
	(at hoist5 depot1)
	(clear crate4)
	(at crate5 depot1)
	(at hoist3 distributor1)
	(on crate11 pallet4)
	(at pallet6 depot0)
	(on crate5 pallet0)
	(at pallet8 depot0)
	(at truck5 depot1)
	(on crate8 crate6)
	(available hoist9)
	(at truck0 distributor2)
	(at crate11 depot1)
	(available hoist12)
	(at crate2 distributor1)
	(at pallet3 distributor0)
	(on crate10 crate9)
	(at pallet13 distributor5)
	(clear crate9)
	(at pallet2 depot2)
	(at crate0 distributor3)
	(at truck0 distributor0)
	(available hoist10)
	(clear pallet10)
	(on crate5 pallet7)
	(at pallet7 distributor3)
	(available hoist13)
	(at pallet3 distributor1)
	(at crate2 distributor0)
	(on crate0 pallet3)
	(at truck0 depot2)
	(at truck2 distributor3)
	(on crate0 pallet16)
	(at crate0 depot1)
	(clear crate7)
	(at pallet5 distributor1)
	(on crate8 pallet5)
	(at hoist5 distributor2)
	(at pallet5 depot5)
	(on crate2 pallet4)
	(available hoist5)
	(at pallet18 depot4)
	(available hoist6)
	(at crate5 distributor2)
	(available hoist11)
	(at hoist10 distributor4)
	(at pallet15 depot1)
	(available hoist8)
	(on crate5 pallet3)
	(at pallet4 distributor0)
	(at truck0 depot0)
	(at crate9 depot2)
	(on crate2 crate1)
	(on crate2 pallet2)
	(at hoist13 depot1)
	(on crate3 pallet6)
	(at pallet5 distributor2)
	(at crate0 distributor0)
	(at hoist1 depot1)
	(at pallet7 distributor0)
	(at crate3 distributor2)
	(on crate12 crate10)
	(at crate9 distributor1)
	(on crate0 pallet7)
	(at pallet5 distributor0)
	(on crate0 pallet4)
	(on crate2 crate0)
	(at crate0 distributor2)
	(available hoist4)
	(at hoist3 distributor0)
	(at pallet14 depot2)
	(at crate3 distributor0)
	(on crate0 pallet5)
	(on crate11 crate6)
	(available hoist3)
	(on crate0 pallet2)
	(at pallet4 depot0)
	(on crate11 crate5)
	(on crate3 pallet8)
	(at pallet8 distributor2)
	(on crate1 pallet9)
	(at crate5 depot3)
	(on crate7 pallet6)
	(at pallet9 distributor3)
	(on crate1 pallet1)
	(at crate13 distributor0)
	(at crate5 depot0)
	(at hoist5 depot0)
	(at truck2 depot1)
	(at crate8 depot1)
	(clear pallet9)
	(at crate14 depot1)
	(at pallet6 distributor2)
	(at crate13 distributor2)
	(at crate2 depot3)
	(at truck3 depot1)
	(at truck1 depot1)
	(at crate5 depot2)
	(at crate7 depot0)
	(on crate5 crate4)
	(at hoist1 distributor0)
	(at crate7 depot3)
	(at crate7 distributor0)
	(at crate2 depot0)
	(at crate1 depot1)
	(at pallet4 distributor1)
	(at crate5 distributor1)
	(on crate9 crate1)
	(at crate14 distributor1)
	(on crate9 crate2)
	(on crate5 crate3)
	(at crate2 depot2)
	(at crate7 distributor2)
	(at hoist5 distributor1)
	(on crate12 crate11)
	(at pallet6 distributor1)
	(at crate7 distributor1)
	(at crate0 depot0)
	(at truck0 depot1)
	(in crate3 truck5)
	(at hoist11 distributor5)
	(at truck3 distributor1)
	(on crate10 crate5)
	(at crate0 depot2)
	(at truck0 distributor1)
	(on crate14 pallet9)
	(at truck3 distributor3)
	(available hoist0)
	(at truck1 depot0)
	(at pallet6 distributor0)
	(available hoist1)
	(at crate14 distributor0)
	(at hoist3 depot3)
	(at crate3 depot0)
	(at hoist2 distributor0)
	(on crate5 pallet1)
	(at truck1 distributor0)
	(at pallet4 depot1)
	(at truck3 distributor0)
	(available hoist2)
	(on crate2 pallet13)
	(at crate13 distributor1)
	(at truck1 depot2)
	(at truck1 distributor2)
	(at crate0 depot3)
	(at crate3 depot2)
	(on crate6 pallet5)
)
(:add
	(clear crate3)
	(lifting hoist6 crate5)
	(clear crate8)
	(on crate8 pallet15)
	(at crate8 depot1)
	(available hoist5)
	(clear pallet2)
	(lifting hoist11 crate2)
	(available hoist4)
	(on crate1 pallet7)
	(clear crate1)
	(at crate1 distributor1)
	(lifting hoist1 crate3)
	(at crate2 distributor5)
	(on crate2 pallet11)
	(clear crate2)
	(available hoist11)
	(available hoist6)
	(clear crate5)
	(on crate5 pallet5)
	(at crate5 depot0)
	(clear crate3)
	(available hoist1)
	(at crate3 distributor0)
	(on crate3 pallet3)
	(lifting hoist4 crate1)
	(lifting hoist5 crate8)
)
(:delete
	(on crate5 crate3)
	(available hoist6)
	(at crate5 distributor2)
	(clear crate5)
	(clear pallet15)
	(lifting hoist5 crate8)
	(at crate2 distributor5)
	(clear crate2)
	(available hoist11)
	(on crate2 pallet2)
	(clear pallet7)
	(lifting hoist4 crate1)
	(available hoist1)
	(in crate3 truck5)
	(lifting hoist11 crate2)
	(clear pallet11)
	(clear pallet5)
	(lifting hoist6 crate5)
	(lifting hoist1 crate3)
	(clear pallet3)
	(in crate1 truck4)
	(available hoist4)
	(in crate8 truck5)
	(available hoist5)
)
(:goal
	(on crate6 pallet12)
	(on crate2 pallet11)
	(on crate0 pallet2)
	(on crate1 pallet7)
	(on crate8 pallet15)
	(on crate7 pallet18)
	(on crate3 pallet3)
	(on crate5 pallet5)
)
(:current
	(on crate7 pallet18)
	(on crate6 pallet12)
	(on crate0 pallet2)
)
