18
(Lift hoist3 crate4 pallet1 distributor1)
(Lift hoist3 crate13 crate7 distributor1)
(Lift hoist6 crate2 pallet0 distributor0)
(Lift hoist0 crate1 pallet1 depot0)
(Lift hoist4 crate8 crate7 distributor1)
(Lift hoist1 crate5 pallet3 depot1)
(Lift hoist4 crate11 pallet8 distributor0)
(Lift hoist2 crate14 pallet9 distributor0)
(Lift hoist7 crate7 pallet6 distributor1)
(Drop hoist1 crate5 crate14 distributor0)
(Drop hoist6 crate2 pallet6 distributor2)
(Drop hoist3 crate13 crate2 depot3)
(Drop hoist3 crate4 crate5 distributor1)
(Drop hoist7 crate7 pallet2 distributor1)
(Drop hoist4 crate8 pallet7 depot0)
(Drop hoist2 crate14 pallet1 distributor0)
(Drop hoist0 crate1 crate11 depot0)
(Drop hoist4 crate11 pallet5 distributor1)
79
(:init
	(at crate5 depot0)
	(at crate13 distributor0)
	(on crate0 pallet3)
	(at crate8 depot1)
	(at truck2 depot1)
	(clear pallet2)
	(at hoist5 depot0)
	(at crate5 depot3)
	(at pallet8 distributor2)
	(on crate2 pallet4)
	(clear pallet5)
	(on crate8 pallet5)
	(clear crate12)
	(at truck1 depot1)
	(at truck3 depot1)
	(at crate2 depot3)
	(at crate13 distributor2)
	(on crate5 pallet3)
	(at crate5 depot2)
	(clear pallet4)
	(at crate14 depot1)
	(on crate3 pallet6)
	(on crate2 pallet2)
	(on crate2 crate1)
	(clear crate10)
	(at pallet6 distributor2)
	(at crate7 depot3)
	(on crate12 crate10)
	(on crate0 pallet7)
	(at crate2 depot0)
	(at crate7 distributor0)
	(at crate7 depot0)
	(on crate0 pallet4)
	(on crate2 crate0)
	(at hoist1 distributor0)
	(at crate14 distributor1)
	(on crate0 pallet5)
	(on crate11 crate6)
	(clear crate11)
	(at crate5 distributor1)
	(at pallet6 distributor1)
	(at hoist5 distributor1)
	(at crate7 distributor2)
	(at crate2 depot2)
	(at pallet4 distributor1)
	(on crate11 crate5)
	(at crate1 depot1)
	(on crate0 pallet2)
	(clear pallet3)
	(on crate3 pallet0)
	(on crate3 crate1)
	(on crate3 pallet1)
	(at truck0 depot1)
	(at crate0 depot0)
	(at crate7 distributor1)
	(on crate3 crate2)
	(on crate0 pallet0)
	(at truck3 distributor1)
	(on crate0 pallet1)
	(on crate5 pallet0)
	(at crate0 depot2)
	(on crate11 pallet4)
	(clear pallet7)
	(on crate3 crate0)
	(at truck3 distributor3)
	(clear pallet6)
	(at truck0 distributor1)
	(at pallet4 depot1)
	(clear crate13)
	(at truck1 distributor0)
	(at hoist2 distributor0)
	(at crate3 depot0)
	(on crate8 crate6)
	(clear pallet1)
	(at truck1 depot0)
	(on crate10 crate9)
	(at hoist3 depot3)
	(at crate14 distributor0)
	(clear pallet0)
	(at crate3 depot2)
	(at crate0 depot3)
	(at truck1 distributor2)
	(at truck1 depot2)
	(on crate5 pallet7)
	(at crate13 distributor1)
	(on crate10 crate5)
	(at pallet7 distributor1)
	(at pallet8 depot2)
	(at hoist2 distributor1)
	(at crate0 distributor1)
	(at truck2 depot2)
	(at hoist5 depot1)
	(at crate3 distributor1)
	(on crate14 pallet9)
	(at pallet8 depot0)
	(at pallet6 depot0)
	(at crate5 depot1)
	(at hoist3 distributor1)
	(available hoist7)
	(at truck2 depot0)
	(at crate2 distributor1)
	(at pallet2 depot2)
	(at pallet3 distributor0)
	(at crate11 depot1)
	(at pallet7 distributor3)
	(on crate6 pallet4)
	(at crate0 distributor3)
	(on crate6 pallet5)
	(at crate3 depot1)
	(at truck0 distributor0)
	(on crate7 pallet6)
	(at hoist5 distributor2)
	(on crate1 pallet9)
	(at crate5 distributor2)
	(on crate3 pallet8)
	(at pallet3 distributor1)
	(clear crate2)
	(at pallet5 distributor1)
	(at crate0 depot1)
	(at truck0 depot2)
	(on crate1 pallet1)
	(at crate2 distributor0)
	(clear crate1)
	(at crate9 depot2)
	(at pallet5 distributor2)
	(clear crate0)
	(at truck0 depot0)
	(at pallet4 distributor0)
	(on crate5 crate4)
	(at crate0 distributor2)
	(at pallet5 distributor0)
	(at hoist1 depot1)
	(at crate0 distributor0)
	(at crate9 distributor1)
	(at crate3 distributor2)
	(at pallet7 distributor0)
	(clear crate14)
	(at pallet4 depot0)
	(at hoist3 distributor0)
	(on crate12 crate11)
	(on crate5 crate3)
	(on crate9 crate2)
	(on crate9 crate1)
	(at crate3 distributor0)
	(at pallet7 depot0)
	(clear crate4)
	(available hoist3)
	(at crate7 depot1)
	(at crate8 depot0)
	(on crate11 pallet8)
	(at crate9 distributor0)
	(available hoist4)
	(on crate6 crate1)
	(clear crate5)
	(at pallet8 depot1)
	(on crate9 crate5)
	(on crate12 crate6)
	(on crate2 pallet8)
	(at crate12 depot1)
	(on crate4 pallet2)
	(at crate11 depot0)
	(clear crate6)
	(on crate6 pallet7)
	(at crate9 distributor2)
	(on crate4 pallet3)
	(at crate8 distributor0)
	(at crate12 distributor0)
	(clear crate8)
	(on crate1 pallet0)
	(available hoist6)
	(on crate11 crate1)
	(clear crate9)
	(at crate10 depot1)
	(available hoist5)
	(on crate7 pallet3)
	(at pallet9 distributor0)
	(on crate4 pallet6)
	(on crate9 pallet7)
	(clear crate3)
	(at pallet3 depot3)
	(at crate4 depot0)
	(on crate4 pallet0)
	(at pallet6 depot1)
	(on crate14 crate9)
	(on crate7 crate6)
	(at crate8 distributor1)
	(on crate4 pallet1)
	(on crate1 pallet4)
	(on crate13 crate9)
	(at crate10 distributor3)
	(at crate8 distributor2)
	(on crate9 pallet2)
	(at hoist6 depot0)
	(at pallet0 depot0)
	(clear crate7)
	(on crate13 crate7)
	(on crate4 crate0)
	(on crate9 pallet3)
	(at crate10 distributor1)
	(on crate0 pallet9)
	(at hoist2 depot2)
	(at crate6 depot0)
	(on crate6 pallet0)
	(on crate9 crate7)
	(on crate1 crate0)
	(on crate4 crate2)
	(on crate9 crate8)
	(on crate6 pallet1)
	(on crate1 pallet5)
	(on crate7 crate5)
	(at crate4 depot2)
	(on crate7 crate4)
	(at hoist4 depot0)
	(on crate0 pallet8)
	(at crate12 distributor1)
	(on crate1 pallet2)
	(at hoist4 distributor1)
	(at hoist6 distributor0)
	(at crate4 distributor2)
	(clear pallet9)
	(at crate6 distributor0)
	(at crate4 distributor1)
	(available hoist2)
	(on crate12 crate2)
	(on crate2 pallet0)
	(at truck1 distributor1)
	(at hoist6 distributor2)
	(available hoist1)
	(on crate8 pallet1)
	(available hoist0)
	(at crate11 distributor1)
	(on crate5 crate0)
	(at hoist7 distributor3)
	(on crate13 crate3)
	(at pallet9 depot0)
	(on crate5 crate2)
	(at pallet7 depot1)
	(on crate13 crate4)
	(at hoist7 distributor1)
	(on crate5 crate1)
	(at pallet9 depot3)
	(at crate4 depot1)
	(on crate8 crate7)
	(at pallet9 depot2)
	(on crate4 pallet8)
	(at hoist6 depot1)
	(on crate8 pallet3)
	(on crate13 crate12)
	(at pallet1 distributor0)
	(on crate10 crate0)
	(at pallet2 distributor1)
	(at crate11 distributor2)
	(on crate14 crate12)
	(at truck3 depot0)
	(at pallet5 depot0)
	(at crate6 depot1)
	(on crate14 crate11)
	(on crate4 crate3)
	(on crate2 pallet3)
	(at crate11 distributor0)
	(at crate1 distributor1)
	(on crate14 crate13)
	(at crate13 depot0)
	(at crate6 distributor2)
	(at pallet2 distributor0)
	(at crate1 depot2)
	(at hoist4 distributor0)
	(at pallet8 distributor1)
	(on crate3 pallet5)
	(on crate6 crate3)
	(at pallet1 depot1)
	(on crate12 crate9)
	(at crate1 depot0)
	(at hoist0 depot0)
	(at crate13 depot2)
	(on crate10 crate1)
	(at crate4 distributor0)
	(at crate6 distributor1)
)
(:add
	(available hoist3)
	(clear crate13)
	(at crate13 depot3)
	(on crate13 crate2)
	(at crate14 distributor0)
	(clear crate14)
	(available hoist2)
	(on crate14 pallet1)
	(available hoist4)
	(clear crate11)
	(on crate11 pallet5)
	(at crate11 distributor1)
	(clear pallet8)
	(lifting hoist4 crate11)
	(clear pallet0)
	(lifting hoist6 crate2)
	(clear pallet9)
	(lifting hoist2 crate14)
	(on crate1 crate11)
	(at crate1 depot0)
	(clear crate1)
	(available hoist0)
	(available hoist4)
	(on crate8 pallet7)
	(at crate8 depot0)
	(clear crate8)
	(clear pallet1)
	(lifting hoist3 crate4)
	(clear pallet3)
	(lifting hoist1 crate5)
	(clear crate7)
	(lifting hoist3 crate13)
	(on crate5 crate14)
	(available hoist1)
	(clear crate5)
	(at crate5 distributor0)
	(lifting hoist4 crate8)
	(clear crate7)
	(on crate4 crate5)
	(clear crate4)
	(available hoist3)
	(at crate4 distributor1)
	(on crate7 pallet2)
	(clear crate7)
	(available hoist7)
	(at crate7 distributor1)
	(clear pallet1)
	(lifting hoist0 crate1)
	(available hoist6)
	(at crate2 distributor2)
	(clear crate2)
	(on crate2 pallet6)
	(clear pallet6)
	(lifting hoist7 crate7)
)
(:delete
	(clear crate2)
	(lifting hoist3 crate13)
	(clear pallet1)
	(lifting hoist2 crate14)
	(clear pallet5)
	(lifting hoist4 crate11)
	(available hoist4)
	(at crate11 distributor0)
	(on crate11 pallet8)
	(clear crate11)
	(available hoist6)
	(clear crate2)
	(on crate2 pallet0)
	(at crate2 distributor0)
	(at crate14 distributor0)
	(clear crate14)
	(available hoist2)
	(on crate14 pallet9)
	(clear crate11)
	(lifting hoist0 crate1)
	(lifting hoist4 crate8)
	(clear pallet7)
	(clear crate4)
	(available hoist3)
	(at crate4 distributor1)
	(on crate4 pallet1)
	(on crate5 pallet3)
	(available hoist1)
	(clear crate5)
	(at crate5 depot1)
	(on crate13 crate7)
	(available hoist3)
	(clear crate13)
	(at crate13 distributor1)
	(lifting hoist1 crate5)
	(clear crate14)
	(available hoist4)
	(at crate8 distributor1)
	(clear crate8)
	(on crate8 crate7)
	(clear crate5)
	(lifting hoist3 crate4)
	(clear pallet2)
	(lifting hoist7 crate7)
	(at crate1 depot0)
	(clear crate1)
	(available hoist0)
	(on crate1 pallet1)
	(lifting hoist6 crate2)
	(clear pallet6)
	(on crate7 pallet6)
	(clear crate7)
	(available hoist7)
	(at crate7 distributor1)
)
(:goal
	(on crate4 crate5)
	(on crate5 crate14)
	(on crate7 pallet2)
	(on crate1 crate11)
	(on crate12 crate6)
	(on crate0 pallet3)
	(on crate11 pallet5)
	(on crate2 pallet6)
	(on crate6 pallet4)
	(on crate8 pallet7)
	(on crate3 crate0)
	(on crate9 crate8)
	(on crate14 pallet1)
	(on crate13 crate2)
)
(:current
	(on crate0 pallet3)
	(on crate3 crate0)
	(on crate6 pallet4)
	(on crate12 crate6)
	(on crate9 crate8)
)
