12
(Lift hoist0 crate1 pallet2 depot0)
(Drop hoist1 crate4 pallet1 distributor0)
(Load hoist1 crate4 truck1 distributor0)
(Unload hoist2 crate5 truck0 distributor1)
(Drive truck1 distributor0 distributor1)
(Lift hoist2 crate1 pallet5 distributor1)
(Lift hoist1 crate0 pallet2 distributor0)
(Unload hoist2 crate4 truck1 distributor1)
(Drop hoist2 crate5 crate1 distributor1)
(Drop hoist0 crate1 crate4 depot0)
(Drop hoist1 crate0 pallet3 distributor0)
(Drop hoist2 crate4 pallet5 distributor1)
