5
(Unload hoist5 crate3 truck3 depot0)
(Lift hoist5 crate13 crate3 distributor2)
(Unload hoist2 crate7 truck1 distributor0)
(Drop hoist5 crate3 crate8 distributor2)
(Drop hoist2 crate7 crate3 depot2)
0
(:init
	(at crate13 depot2)
	(at hoist3 distributor0)
	(on crate2 pallet3)
	(at crate4 distributor0)
	(at crate3 distributor0)
	(clear crate13)
	(on crate4 crate3)
	(at pallet1 depot1)
	(on crate14 crate11)
	(at hoist0 depot0)
	(at crate1 depot0)
	(on crate1 pallet1)
	(at hoist1 depot1)
	(at crate0 distributor0)
	(at pallet8 distributor1)
	(on crate13 crate12)
	(available hoist4)
	(on crate8 pallet3)
	(at crate3 distributor2)
	(at pallet7 distributor0)
	(at crate9 distributor1)
	(on crate3 pallet8)
	(on crate1 pallet9)
	(at crate0 distributor2)
	(at crate1 distributor1)
	(at crate1 depot2)
	(available hoist3)
	(at crate6 distributor2)
	(at pallet2 distributor0)
	(at crate11 distributor0)
	(on crate10 crate1)
	(on crate9 crate2)
	(on crate12 crate11)
	(at pallet4 distributor0)
	(at truck0 depot0)
	(at pallet5 depot0)
	(at truck3 depot0)
	(at crate9 depot2)
	(available hoist6)
	(at crate6 depot1)
	(on crate12 crate9)
	(available hoist5)
	(on crate6 crate3)
	(at pallet5 distributor2)
	(at pallet3 distributor1)
	(at pallet1 distributor0)
	(at crate0 depot1)
	(at truck0 depot2)
	(at pallet5 distributor1)
	(at pallet2 distributor1)
	(at crate11 distributor2)
	(at crate2 distributor0)
	(in crate7 truck1)
	(at hoist5 distributor2)
	(on crate14 crate13)
	(at crate5 distributor2)
	(at hoist6 depot1)
	(on crate5 crate4)
	(on crate8 pallet6)
	(at hoist7 distributor1)
	(on crate8 pallet1)
	(at crate3 depot1)
	(at truck0 distributor0)
	(at pallet9 depot0)
	(on crate2 pallet0)
	(on crate14 pallet9)
	(clear crate8)
	(at pallet7 depot1)
	(clear pallet3)
	(at crate2 distributor1)
	(clear crate9)
	(clear crate11)
	(at crate11 distributor1)
	(at pallet2 depot2)
	(on crate10 crate5)
	(at pallet3 distributor0)
	(on crate8 crate7)
	(in crate3 truck3)
	(on crate6 pallet5)
	(at truck2 depot0)
	(clear crate5)
	(on crate5 crate1)
	(clear pallet5)
	(on crate13 crate4)
	(clear crate12)
	(at crate6 distributor0)
	(at hoist5 depot1)
	(at crate4 distributor1)
	(on crate5 crate2)
	(clear crate4)
	(at pallet6 depot0)
	(on crate6 pallet4)
	(at pallet8 depot0)
	(at crate5 depot1)
	(at hoist3 distributor1)
	(at truck1 distributor1)
	(clear pallet2)
	(on crate13 crate3)
	(clear crate6)
	(at crate0 distributor1)
	(clear crate10)
	(on crate5 crate0)
	(at pallet8 depot2)
	(at pallet7 distributor1)
	(at hoist4 distributor1)
	(at hoist2 distributor1)
	(clear pallet4)
	(at crate12 distributor1)
	(available hoist1)
	(available hoist7)
	(on crate3 crate0)
	(at truck1 depot2)
	(at crate13 distributor1)
	(on crate11 pallet4)
	(on crate4 crate0)
	(on crate5 pallet0)
	(at crate3 depot2)
	(on crate0 pallet1)
	(available hoist2)
	(at crate4 depot2)
	(at truck1 distributor2)
	(on crate9 pallet2)
	(at hoist4 depot0)
	(on crate0 pallet0)
	(on crate3 crate2)
	(on crate13 crate9)
	(on crate1 pallet4)
	(at crate14 distributor0)
	(on crate3 pallet1)
	(at pallet4 depot1)
	(on crate7 crate6)
	(on crate14 crate9)
	(at hoist2 distributor0)
	(at truck1 distributor0)
	(on crate4 pallet0)
	(at hoist2 depot2)
	(clear crate14)
	(at crate6 depot0)
	(at crate0 depot2)
	(clear crate2)
	(at crate10 distributor1)
	(at truck0 distributor1)
	(on crate1 pallet2)
	(on crate0 pallet8)
	(at crate8 distributor2)
	(on crate7 crate4)
	(at hoist6 depot0)
	(at pallet0 depot0)
	(on crate6 pallet1)
	(on crate9 crate8)
	(clear crate0)
	(at crate0 depot0)
	(on crate4 crate2)
	(on crate1 crate0)
	(available hoist0)
	(on crate9 crate7)
	(clear crate1)
	(at crate4 depot0)
	(at pallet6 depot1)
	(at pallet9 distributor0)
	(on crate4 pallet3)
	(at pallet4 distributor1)
	(at crate1 depot1)
	(on crate2 crate1)
	(on crate2 pallet2)
	(at crate14 distributor1)
	(on crate4 pallet2)
	(at crate5 distributor1)
	(at crate10 depot1)
	(on crate2 pallet8)
	(on crate5 pallet3)
	(at pallet6 distributor1)
	(on crate9 crate5)
	(at crate7 distributor2)
	(at crate2 depot2)
	(on crate8 pallet5)
	(on crate2 pallet4)
	(on crate6 crate1)
	(at hoist1 distributor0)
	(on crate1 pallet7)
	(at crate8 distributor0)
	(on crate0 pallet3)
	(at crate7 distributor0)
	(at crate2 depot0)
	(at crate12 distributor0)
	(at crate11 depot0)
	(on crate9 pallet7)
	(at crate9 distributor2)
	(on crate11 crate5)
	(on crate0 pallet2)
	(on crate4 pallet6)
	(at pallet6 distributor2)
	(at truck1 depot1)
	(at crate13 distributor2)
	(at crate5 depot2)
	(on crate11 crate6)
	(on crate0 pallet5)
	(at crate12 depot1)
	(at crate8 depot0)
	(at crate9 distributor0)
	(on crate1 pallet0)
	(on crate0 pallet4)
	(on crate2 crate0)
	(at crate13 distributor0)
	(clear pallet9)
	(at crate5 depot0)
	(at pallet7 depot0)
	(at crate7 depot1)
	(on crate12 crate10)
	(at hoist5 depot0)
	(at crate8 depot1)
	(at truck2 depot1)
)
(:add
	(lifting hoist5 crate3)
	(lifting hoist2 crate7)
	(lifting hoist5 crate13)
	(clear crate3)
	(available hoist5)
	(on crate3 crate8)
	(at crate3 distributor2)
	(clear crate3)
	(clear crate7)
	(available hoist2)
	(at crate7 depot2)
	(on crate7 crate3)
)
(:delete
	(available hoist5)
	(in crate3 truck3)
	(available hoist2)
	(in crate7 truck1)
	(available hoist5)
	(clear crate13)
	(at crate13 distributor2)
	(on crate13 crate3)
	(lifting hoist5 crate3)
	(clear crate8)
	(lifting hoist2 crate7)
	(clear crate3)
)
(:goal
	(on crate6 pallet1)
	(on crate1 pallet7)
	(on crate4 pallet0)
	(on crate3 crate8)
	(on crate2 pallet4)
	(on crate8 pallet6)
	(on crate7 crate3)
)
(:current
	(on crate8 pallet6)
	(on crate4 pallet0)
	(on crate6 pallet1)
	(on crate2 pallet4)
	(on crate1 pallet7)
)
