8
(Unload hoist0 crate3 truck1 depot0)
(Unload hoist0 crate13 truck1 depot0)
(Drive truck1 depot0 distributor0)
(Lift hoist1 crate4 crate3 distributor0)
(Drop hoist0 crate13 crate3 depot0)
(Unload hoist1 crate11 truck1 distributor0)
(Drop hoist0 crate3 pallet0 depot0)
(Drop hoist1 crate11 pallet1 distributor0)
-1
(:init
	(on crate2 pallet2)
	(at crate4 depot0)
	(on crate2 crate10)
	(in crate3 truck1)
	(at pallet2 distributor1)
	(in crate11 truck1)
	(at pallet5 distributor1)
	(at crate0 depot0)
	(on crate9 crate5)
	(at pallet1 distributor0)
	(at pallet3 distributor1)
	(at pallet0 depot0)
	(on crate6 crate1)
	(at pallet5 depot0)
	(on crate5 pallet5)
	(clear crate9)
	(at pallet4 distributor0)
	(at truck0 distributor1)
	(at crate10 distributor1)
	(at crate6 depot0)
	(at crate1 distributor1)
	(on crate8 crate7)
	(at crate3 depot0)
	(clear crate12)
	(at crate9 distributor1)
	(on crate5 crate2)
	(at truck1 depot0)
	(on crate11 crate6)
	(clear crate4)
	(at crate0 distributor0)
	(on crate6 pallet4)
	(on crate4 crate6)
	(at hoist0 depot0)
	(on crate2 crate0)
	(on crate0 pallet4)
	(on crate0 crate5)
	(at crate4 distributor0)
	(at crate12 distributor1)
	(on crate3 crate0)
	(clear pallet1)
	(in crate7 truck1)
	(at hoist2 distributor1)
	(on crate5 pallet0)
	(at crate5 depot0)
	(at crate13 distributor0)
	(on crate4 crate3)
	(available hoist0)
	(on crate0 pallet1)
	(on crate3 crate2)
	(on crate0 pallet0)
	(at crate3 distributor1)
	(at crate6 distributor0)
	(on crate13 crate12)
	(clear pallet0)
	(on crate3 crate1)
	(on crate14 pallet3)
	(on crate12 crate14)
	(in crate13 truck1)
	(at crate11 depot0)
	(at pallet3 distributor0)
	(on crate9 crate1)
	(at crate8 distributor0)
	(on crate1 pallet2)
	(on crate1 crate2)
	(at crate2 distributor1)
	(on crate7 crate4)
	(on crate12 crate9)
	(at hoist1 distributor0)
	(on crate1 pallet5)
	(on crate10 pallet2)
	(clear crate0)
	(on crate6 pallet1)
	(in crate8 truck0)
	(available hoist1)
	(on crate9 crate8)
	(at crate14 distributor1)
	(on crate14 crate13)
	(available hoist2)
)
(:add
	(lifting hoist1 crate11)
	(lifting hoist0 crate3)
	(on crate11 pallet1)
	(clear crate11)
	(available hoist1)
	(at crate11 distributor0)
	(available hoist0)
	(at crate3 depot0)
	(on crate3 pallet0)
	(clear crate3)
	(at crate13 depot0)
	(available hoist0)
	(clear crate13)
	(on crate13 crate3)
	(lifting hoist1 crate4)
	(clear crate3)
	(at truck1 distributor0)
	(lifting hoist0 crate13)
)
(:delete
	(in crate11 truck1)
	(available hoist1)
	(in crate3 truck1)
	(available hoist0)
	(clear pallet1)
	(lifting hoist1 crate11)
	(lifting hoist0 crate3)
	(clear pallet0)
	(clear crate3)
	(lifting hoist0 crate13)
	(on crate4 crate3)
	(clear crate4)
	(available hoist1)
	(at crate4 distributor0)
	(at truck1 depot0)
	(available hoist0)
	(in crate13 truck1)
)
(:goal
	(on crate5 pallet5)
	(on crate9 crate1)
	(on crate4 crate6)
	(on crate11 pallet1)
	(on crate14 pallet3)
	(on crate12 crate14)
	(on crate0 crate5)
	(on crate3 pallet0)
	(on crate13 crate3)
	(on crate1 crate2)
	(on crate6 pallet4)
	(on crate2 crate10)
	(on crate10 pallet2)
)
(:current
	(on crate2 crate10)
	(on crate5 pallet5)
	(on crate6 pallet4)
	(on crate4 crate6)
	(on crate0 crate5)
	(on crate14 pallet3)
	(on crate12 crate14)
	(on crate9 crate1)
	(on crate1 crate2)
	(on crate10 pallet2)
)
