28
(Lift hoist2 crate2 crate1 distributor1)
(Drop hoist1 crate12 crate14 distributor0)
(Unload hoist0 crate13 truck1 depot0)
(Lift hoist2 crate1 pallet0 distributor1)
(Lift hoist2 crate0 pallet4 distributor1)
(Unload hoist2 crate10 truck1 distributor1)
(Lift hoist0 crate3 pallet1 depot0)
(Lift hoist2 crate1 pallet5 distributor1)
(Lift hoist0 crate11 crate6 depot0)
(Lift hoist2 crate5 crate2 distributor1)
(Lift hoist2 crate9 crate5 distributor1)
(Unload hoist0 crate4 truck1 depot0)
(Lift hoist0 crate1 pallet2 depot0)
(Lift hoist1 crate6 crate1 distributor0)
(Drop hoist0 crate13 crate3 depot0)
(Drop hoist2 crate5 pallet5 distributor1)
(Drop hoist0 crate1 crate2 depot0)
(Drop hoist2 crate0 crate5 distributor1)
(Drop hoist2 crate9 crate1 distributor1)
(Lift hoist1 crate11 pallet4 distributor0)
(Lift hoist1 crate14 crate9 distributor0)
(Drop hoist2 crate10 pallet2 distributor1)
(Drop hoist0 crate3 pallet0 depot0)
(Drop hoist0 crate4 crate6 depot0)
(Drop hoist1 crate6 pallet4 distributor0)
(Drop hoist2 crate2 crate10 distributor1)
(Drop hoist1 crate11 pallet1 distributor0)
(Drop hoist1 crate14 pallet3 distributor0)
38
(:init
	(on crate2 crate1)
	(on crate2 pallet2)
	(at crate4 depot0)
	(on crate5 pallet3)
	(at pallet2 distributor1)
	(at pallet5 distributor1)
	(at crate0 depot0)
	(on crate9 crate5)
	(at pallet1 distributor0)
	(at pallet3 distributor1)
	(clear crate8)
	(on crate6 crate1)
	(at pallet0 depot0)
	(on crate8 pallet5)
	(clear pallet3)
	(clear crate3)
	(at pallet5 depot0)
	(at truck0 depot0)
	(clear crate9)
	(at truck0 distributor1)
	(at pallet4 distributor0)
	(clear crate11)
	(at crate11 distributor0)
	(at crate6 depot0)
	(at crate1 distributor1)
	(on crate8 crate7)
	(at crate3 depot0)
	(clear crate5)
	(on crate0 pallet2)
	(at crate9 distributor1)
	(on crate5 crate2)
	(at crate14 distributor0)
	(at truck1 depot0)
	(on crate11 crate6)
	(at crate0 distributor0)
	(in crate4 truck1)
	(clear pallet2)
	(on crate1 pallet0)
	(at crate1 depot0)
	(at hoist0 depot0)
	(on crate0 pallet4)
	(on crate2 crate0)
	(at crate3 distributor0)
	(at crate4 distributor0)
	(clear pallet1)
	(on crate3 crate0)
	(at hoist2 distributor1)
	(on crate5 pallet0)
	(at crate5 depot0)
	(at crate13 distributor0)
	(on crate11 pallet4)
	(on crate4 crate3)
	(available hoist0)
	(on crate0 pallet1)
	(at crate0 distributor1)
	(at crate9 distributor0)
	(at crate8 depot0)
	(lifting hoist1 crate12)
	(on crate3 crate2)
	(at truck1 distributor1)
	(on crate0 pallet0)
	(on crate3 pallet1)
	(at crate6 distributor0)
	(at crate3 distributor1)
	(on crate13 crate12)
	(on crate14 crate9)
	(on crate7 crate6)
	(on crate3 crate1)
	(in crate10 truck1)
	(clear crate14)
	(in crate13 truck1)
	(at crate11 depot0)
	(at pallet3 distributor0)
	(at crate2 depot0)
	(at crate7 distributor0)
	(clear crate2)
	(at crate8 distributor0)
	(on crate1 pallet2)
	(at crate2 distributor1)
	(on crate7 crate4)
	(on crate12 crate9)
	(at hoist1 distributor0)
	(on crate6 crate3)
	(on crate1 pallet5)
	(clear crate0)
	(on crate6 pallet1)
	(on crate9 crate8)
	(at crate5 distributor1)
	(on crate14 crate13)
	(clear crate1)
	(available hoist2)
	(on crate9 crate7)
)
(:add
	(lifting hoist2 crate5)
	(clear crate2)
	(at crate0 distributor1)
	(available hoist2)
	(on crate0 crate5)
	(clear crate0)
	(clear pallet4)
	(lifting hoist2 crate0)
	(clear crate5)
	(lifting hoist2 crate9)
	(clear crate1)
	(lifting hoist2 crate2)
	(at crate12 distributor0)
	(on crate12 crate14)
	(available hoist1)
	(clear crate12)
	(available hoist0)
	(at crate3 depot0)
	(on crate3 pallet0)
	(clear crate3)
	(lifting hoist0 crate4)
	(available hoist2)
	(clear crate2)
	(on crate2 crate10)
	(at crate2 distributor1)
	(lifting hoist2 crate1)
	(clear pallet5)
	(lifting hoist0 crate3)
	(clear pallet1)
	(available hoist0)
	(clear crate1)
	(on crate1 crate2)
	(at crate1 depot0)
	(on crate6 pallet4)
	(clear crate6)
	(available hoist1)
	(at crate6 distributor0)
	(at crate9 distributor1)
	(on crate9 crate1)
	(clear crate9)
	(available hoist2)
	(on crate11 pallet1)
	(clear crate11)
	(available hoist1)
	(at crate11 distributor0)
	(lifting hoist1 crate14)
	(clear crate9)
	(available hoist2)
	(clear crate10)
	(at crate10 distributor1)
	(on crate10 pallet2)
	(at crate13 depot0)
	(available hoist0)
	(clear crate13)
	(on crate13 crate3)
	(clear crate1)
	(lifting hoist1 crate6)
	(on crate14 pallet3)
	(clear crate14)
	(at crate14 distributor0)
	(available hoist1)
	(lifting hoist0 crate13)
	(clear pallet0)
	(lifting hoist2 crate1)
	(on crate5 pallet5)
	(available hoist2)
	(clear crate5)
	(at crate5 distributor1)
	(clear crate4)
	(at crate4 depot0)
	(available hoist0)
	(on crate4 crate6)
	(lifting hoist0 crate1)
	(clear pallet2)
	(lifting hoist1 crate11)
	(clear pallet4)
	(lifting hoist0 crate11)
	(clear crate6)
	(lifting hoist2 crate10)
)
(:delete
	(on crate5 crate2)
	(available hoist2)
	(at crate5 distributor1)
	(clear crate5)
	(clear crate5)
	(lifting hoist2 crate0)
	(on crate0 pallet4)
	(at crate0 distributor1)
	(available hoist2)
	(clear crate0)
	(at crate9 distributor1)
	(on crate9 crate5)
	(clear crate9)
	(available hoist2)
	(on crate2 crate1)
	(available hoist2)
	(clear crate2)
	(at crate2 distributor1)
	(clear crate14)
	(lifting hoist1 crate12)
	(lifting hoist0 crate3)
	(clear pallet0)
	(available hoist0)
	(in crate4 truck1)
	(clear crate10)
	(lifting hoist2 crate2)
	(on crate1 pallet5)
	(clear crate1)
	(available hoist2)
	(at crate1 distributor1)
	(available hoist0)
	(at crate3 depot0)
	(on crate3 pallet1)
	(clear crate3)
	(lifting hoist0 crate1)
	(clear crate2)
	(lifting hoist1 crate6)
	(clear pallet4)
	(clear crate1)
	(lifting hoist2 crate9)
	(clear pallet1)
	(lifting hoist1 crate11)
	(on crate14 crate9)
	(clear crate14)
	(at crate14 distributor0)
	(available hoist1)
	(lifting hoist2 crate10)
	(clear pallet2)
	(clear crate3)
	(lifting hoist0 crate13)
	(on crate6 crate1)
	(clear crate6)
	(available hoist1)
	(at crate6 distributor0)
	(clear pallet3)
	(lifting hoist1 crate14)
	(available hoist0)
	(in crate13 truck1)
	(clear crate1)
	(on crate1 pallet0)
	(available hoist2)
	(at crate1 distributor1)
	(lifting hoist2 crate5)
	(clear pallet5)
	(lifting hoist0 crate4)
	(clear crate6)
	(on crate1 pallet2)
	(available hoist0)
	(clear crate1)
	(at crate1 depot0)
	(clear crate11)
	(available hoist1)
	(on crate11 pallet4)
	(at crate11 distributor0)
	(on crate11 crate6)
	(available hoist0)
	(clear crate11)
	(at crate11 depot0)
	(in crate10 truck1)
	(available hoist2)
)
(:goal
	(on crate5 pallet5)
	(on crate9 crate1)
	(on crate4 crate6)
	(on crate11 pallet1)
	(on crate14 pallet3)
	(on crate12 crate14)
	(on crate0 crate5)
	(on crate3 pallet0)
	(on crate13 crate3)
	(on crate1 crate2)
	(on crate6 pallet4)
	(on crate2 crate10)
	(on crate10 pallet2)
)
(:current
)
