30
(Drive truck1 depot0 distributor1)
(Drop hoist0 crate4 crate1 depot0)
(Drive truck0 depot0 distributor0)
(Lift hoist2 crate1 pallet0 distributor1)
(Drive truck0 depot0 distributor1)
(Lift hoist2 crate8 crate3 distributor1)
(Drive truck1 depot0 distributor0)
(Load hoist2 crate1 truck1 distributor1)
(Unload hoist0 crate9 truck0 depot0)
(Unload hoist1 crate2 truck0 distributor0)
(Unload hoist2 crate6 truck0 distributor1)
(Unload hoist1 crate5 truck0 distributor0)
(Unload hoist1 crate0 truck0 distributor0)
(Unload hoist0 crate6 truck0 depot0)
(Unload hoist0 crate7 truck1 depot0)
(Lift hoist2 crate3 crate0 distributor1)
(Unload hoist2 crate9 truck0 distributor1)
(Unload hoist1 crate1 truck1 distributor0)
(Drop hoist1 crate2 crate0 distributor0)
(Drop hoist2 crate9 crate8 distributor1)
(Drop hoist0 crate9 pallet0 depot0)
(Drop hoist2 crate6 crate8 distributor1)
(Drop hoist1 crate5 crate4 distributor0)
(Drop hoist1 crate5 pallet1 distributor0)
(Drop hoist0 crate7 crate1 depot0)
(Drop hoist0 crate6 crate1 depot0)
(Drop hoist2 crate6 crate9 distributor1)
(Drop hoist0 crate4 crate6 depot0)
(Drop hoist1 crate1 pallet1 distributor0)
(Drop hoist1 crate0 crate5 distributor0)
