10
(Unload hoist3 crate10 truck0 distributor0)
(Unload hoist4 crate10 truck0 distributor1)
(Lift hoist2 crate6 crate1 distributor1)
(Unload hoist4 crate1 truck0 distributor1)
(Unload hoist1 crate10 truck0 distributor0)
(Drop hoist2 crate6 pallet6 distributor1)
(Drop hoist4 crate10 crate0 distributor1)
(Drop hoist3 crate10 crate11 distributor0)
(Drop hoist1 crate10 pallet9 distributor0)
(Drop hoist4 crate1 crate10 distributor1)
-2
(:init
	(on crate6 pallet5)
	(on crate5 crate1)
	(on crate13 crate4)
	(at crate8 distributor0)
	(on crate8 crate7)
	(clear crate2)
	(at crate2 depot0)
	(at crate12 distributor0)
	(at crate7 distributor0)
	(on crate6 pallet4)
	(at hoist1 distributor0)
	(on crate5 crate2)
	(at crate14 distributor1)
	(available hoist2)
	(at crate5 distributor1)
	(at pallet6 distributor1)
	(clear crate0)
	(at crate7 distributor2)
	(at pallet9 distributor0)
	(at pallet4 distributor1)
	(at crate1 depot1)
	(available hoist1)
	(at crate5 depot0)
	(at crate13 distributor0)
	(available hoist0)
	(at pallet7 depot0)
	(at crate8 depot1)
	(on crate8 pallet1)
	(on crate2 pallet0)
	(on crate14 pallet9)
	(at crate8 depot0)
	(at truck1 depot1)
	(at crate13 distributor2)
	(at crate12 depot1)
	(at crate5 depot2)
	(at crate11 depot0)
	(clear crate14)
	(on crate10 crate5)
	(at crate9 distributor2)
	(at pallet6 distributor2)
	(on crate9 crate2)
	(on crate12 crate11)
	(at crate3 depot0)
	(at hoist2 depot2)
	(at crate6 depot0)
	(on crate6 crate3)
	(at crate14 distributor0)
	(on crate4 crate7)
	(on crate12 crate9)
	(at crate4 depot2)
	(on crate5 crate4)
	(at crate13 distributor1)
	(on crate14 crate13)
	(on crate8 pallet7)
	(clear pallet9)
	(at crate4 depot0)
	(at pallet6 depot1)
	(on crate0 crate8)
	(on crate2 pallet3)
	(on crate11 crate9)
	(at crate0 depot0)
	(at crate7 distributor1)
	(on crate4 crate3)
	(on crate14 crate11)
	(at crate8 distributor2)
	(on crate13 crate12)
	(at crate12 distributor2)
	(on crate1 pallet1)
	(at pallet0 depot0)
	(at crate0 depot2)
	(on crate3 pallet8)
	(on crate1 pallet9)
	(at truck0 distributor1)
	(on crate0 pallet2)
	(at crate2 distributor1)
	(at crate11 distributor1)
	(at pallet2 depot2)
	(at pallet3 distributor0)
	(available hoist3)
	(on crate11 crate6)
	(available hoist4)
	(clear pallet6)
	(on crate0 pallet4)
	(on crate2 crate0)
	(at pallet9 depot0)
	(at pallet7 depot1)
	(on crate1 pallet0)
	(on crate7 pallet4)
	(in crate3 truck1)
	(at crate3 depot1)
	(at truck0 distributor0)
	(on crate3 pallet6)
	(at pallet8 depot2)
	(at hoist2 distributor1)
	(on crate4 pallet3)
	(on crate12 crate5)
	(at hoist4 distributor1)
	(clear pallet1)
	(on crate2 pallet2)
	(on crate2 crate1)
	(on crate9 crate5)
	(at crate0 distributor1)
	(on crate13 pallet8)
	(clear crate13)
	(on crate5 pallet3)
	(at crate3 distributor1)
	(at crate6 distributor0)
	(at crate4 distributor1)
	(on crate9 crate4)
	(at pallet8 depot0)
	(on crate8 pallet5)
	(available hoist5)
	(on crate6 crate1)
	(at crate5 depot1)
	(in crate1 truck0)
	(on crate5 pallet5)
	(clear crate12)
	(on crate1 pallet2)
	(on crate0 pallet8)
	(at crate6 distributor2)
	(at crate1 depot2)
	(at hoist1 depot1)
	(clear pallet2)
	(on crate1 pallet5)
	(at crate0 distributor0)
	(at pallet8 distributor1)
	(on crate7 crate4)
	(at crate9 distributor1)
	(at crate3 distributor2)
	(at pallet7 distributor0)
	(on crate1 crate0)
	(on crate4 crate2)
	(at pallet1 depot1)
	(on crate6 pallet1)
	(at crate1 depot0)
	(on crate9 crate8)
	(at hoist0 depot0)
	(clear crate6)
	(at hoist3 distributor0)
	(at crate13 depot2)
	(on crate9 crate7)
	(at crate4 distributor0)
	(at crate3 distributor0)
	(at crate6 distributor1)
	(on crate11 pallet4)
	(on crate4 crate0)
	(on crate5 pallet0)
	(at hoist5 distributor2)
	(at crate5 distributor2)
	(on crate3 crate0)
	(in crate10 truck0)
	(at pallet3 distributor1)
	(at pallet1 distributor0)
	(on crate0 pallet1)
	(at pallet5 distributor1)
	(at pallet2 distributor1)
	(at crate0 depot1)
	(at truck0 depot2)
	(at crate2 distributor0)
	(at pallet5 depot0)
	(at crate6 depot1)
	(at crate9 depot2)
	(clear pallet3)
	(on crate3 pallet1)
	(on crate0 pallet0)
	(at pallet5 distributor2)
	(on crate13 crate9)
	(on crate4 pallet0)
	(on crate3 crate1)
	(at crate11 distributor0)
	(clear crate11)
	(at truck0 depot0)
	(on crate14 crate9)
	(at pallet4 distributor0)
)
(:add
	(lifting hoist1 crate10)
	(available hoist2)
	(clear crate6)
	(on crate6 pallet6)
	(at crate6 distributor1)
	(at crate10 distributor1)
	(clear crate10)
	(on crate10 crate0)
	(available hoist4)
	(clear crate1)
	(lifting hoist2 crate6)
	(lifting hoist3 crate10)
	(on crate10 pallet9)
	(clear crate10)
	(at crate10 distributor0)
	(available hoist1)
	(at crate1 distributor1)
	(clear crate1)
	(on crate1 crate10)
	(available hoist4)
	(lifting hoist4 crate1)
	(clear crate10)
	(at crate10 distributor0)
	(available hoist3)
	(on crate10 crate11)
	(lifting hoist4 crate10)
)
(:delete
	(in crate10 truck0)
	(available hoist1)
	(clear pallet6)
	(lifting hoist2 crate6)
	(clear crate0)
	(lifting hoist4 crate10)
	(available hoist2)
	(clear crate6)
	(at crate6 distributor1)
	(on crate6 crate1)
	(in crate10 truck0)
	(available hoist3)
	(lifting hoist1 crate10)
	(clear pallet9)
	(lifting hoist4 crate1)
	(clear crate10)
	(in crate1 truck0)
	(available hoist4)
	(clear crate11)
	(lifting hoist3 crate10)
	(in crate10 truck0)
	(available hoist4)
)
(:goal
	(on crate2 pallet0)
	(on crate14 pallet9)
	(on crate11 crate9)
	(on crate7 pallet4)
	(on crate13 pallet8)
	(on crate1 crate10)
	(on crate9 crate4)
	(on crate3 pallet1)
	(on crate4 crate7)
	(on crate12 crate5)
	(on crate6 pallet6)
	(on crate0 crate8)
	(on crate5 pallet5)
	(on crate8 pallet7)
	(on crate10 crate11)
)
(:current
	(on crate2 pallet0)
	(on crate14 pallet9)
	(on crate4 crate7)
	(on crate8 pallet7)
	(on crate0 crate8)
	(on crate11 crate9)
	(on crate7 pallet4)
	(on crate12 crate5)
	(on crate13 pallet8)
	(on crate9 crate4)
	(on crate5 pallet5)
	(on crate3 pallet1)
)
