13
(Lift hoist2 crate8 crate3 distributor1)
(Drive truck0 depot0 distributor0)
(Drop hoist0 crate6 crate9 depot0)
(Unload hoist0 crate4 truck0 depot0)
(Lift hoist2 crate3 crate0 distributor1)
(Unload hoist1 crate0 truck0 distributor0)
(Unload hoist1 crate5 truck0 distributor0)
(Unload hoist1 crate2 truck0 distributor0)
(Drop hoist1 crate2 crate0 distributor0)
(Drop hoist0 crate4 crate6 depot0)
(Drop hoist1 crate5 crate7 distributor0)
(Drop hoist1 crate5 crate4 distributor0)
(Drop hoist1 crate0 crate5 distributor0)
-4
(:init
	(clear crate7)
	(at crate1 distributor0)
	(at crate3 distributor1)
	(at pallet0 depot0)
	(on crate1 pallet1)
	(on crate0 pallet0)
	(at truck0 depot0)
	(on crate3 pallet1)
	(on crate0 pallet1)
	(available hoist1)
	(at hoist2 distributor1)
	(on crate8 crate3)
	(on crate2 pallet2)
	(on crate2 crate1)
	(on crate3 crate0)
	(at pallet1 distributor0)
	(at crate8 distributor1)
	(in crate4 truck0)
	(on crate7 crate1)
	(at pallet2 distributor1)
	(available hoist2)
	(in crate0 truck0)
	(at crate9 depot0)
	(at hoist0 depot0)
	(clear crate9)
	(at crate3 distributor0)
	(on crate3 pallet2)
	(at crate4 distributor0)
	(at truck1 distributor0)
	(lifting hoist0 crate6)
	(in crate2 truck0)
	(at crate7 distributor0)
	(at crate1 distributor1)
	(in crate5 truck0)
	(at crate0 distributor0)
	(on crate1 pallet2)
	(clear crate8)
	(at hoist1 distributor0)
	(on crate9 pallet0)
)
(:add
	(lifting hoist2 crate8)
	(clear crate3)
	(on crate2 crate0)
	(available hoist1)
	(at crate2 distributor0)
	(clear crate2)
	(at truck0 distributor0)
	(available hoist1)
	(on crate0 crate5)
	(at crate0 distributor0)
	(clear crate0)
	(available hoist1)
	(on crate5 crate7)
	(clear crate5)
	(at crate5 distributor0)
	(lifting hoist1 crate5)
	(lifting hoist1 crate2)
	(at crate6 depot0)
	(clear crate6)
	(on crate6 crate9)
	(available hoist0)
	(clear crate4)
	(at crate4 depot0)
	(on crate4 crate6)
	(available hoist0)
	(lifting hoist1 crate0)
	(available hoist1)
	(clear crate5)
	(at crate5 distributor0)
	(on crate5 crate4)
	(clear crate0)
	(lifting hoist2 crate3)
	(lifting hoist0 crate4)
)
(:delete
	(available hoist2)
	(at crate8 distributor1)
	(clear crate8)
	(on crate8 crate3)
	(lifting hoist1 crate2)
	(clear crate0)
	(at truck0 depot0)
	(lifting hoist1 crate0)
	(clear crate5)
	(clear crate7)
	(lifting hoist1 crate5)
	(available hoist1)
	(in crate5 truck0)
	(available hoist1)
	(in crate2 truck0)
	(clear crate9)
	(lifting hoist0 crate6)
	(lifting hoist0 crate4)
	(clear crate6)
	(available hoist1)
	(in crate0 truck0)
	(clear crate4)
	(lifting hoist1 crate5)
	(on crate3 crate0)
	(available hoist2)
	(at crate3 distributor1)
	(clear crate3)
	(available hoist0)
	(in crate4 truck0)
)
(:goal
	(on crate2 crate0)
	(on crate7 crate1)
	(on crate3 pallet2)
	(on crate0 crate5)
	(on crate4 crate6)
	(on crate1 pallet1)
	(on crate6 crate9)
	(on crate5 crate4)
	(on crate8 crate3)
	(on crate9 pallet0)
)
(:current
	(on crate1 pallet1)
	(on crate8 crate3)
	(on crate7 crate1)
	(on crate3 pallet2)
	(on crate9 pallet0)
)
