16
(Lift hoist1 crate7 crate6 distributor0)
(Lift hoist1 crate12 crate11 distributor0)
(Unload hoist1 crate13 truck1 distributor0)
(Lift hoist0 crate3 pallet1 depot0)
(Drive truck0 distributor1 distributor0)
(Unload hoist1 crate4 truck1 distributor0)
(Drop hoist1 crate13 crate3 distributor0)
(Lift hoist1 crate6 crate1 distributor0)
(Drop hoist1 crate4 crate6 distributor0)
(Lift hoist1 crate11 pallet4 distributor0)
(Load hoist1 crate12 truck0 distributor0)
(Drop hoist0 crate3 pallet0 depot0)
(Drop hoist1 crate6 pallet4 distributor0)
(Unload hoist2 crate12 truck0 distributor1)
(Drop hoist1 crate11 pallet1 distributor0)
(Drop hoist2 crate12 crate14 distributor1)
8
(:init
	(on crate2 pallet2)
	(at crate4 depot0)
	(on crate2 crate10)
	(at pallet2 distributor1)
	(at pallet5 distributor1)
	(at crate0 depot0)
	(on crate9 crate5)
	(at pallet1 distributor0)
	(at pallet3 distributor1)
	(on crate6 crate1)
	(at pallet0 depot0)
	(clear crate3)
	(at pallet5 depot0)
	(on crate5 pallet5)
	(at truck0 distributor1)
	(at pallet4 distributor0)
	(clear crate9)
	(at crate10 distributor1)
	(at crate11 distributor0)
	(at crate6 depot0)
	(at crate1 distributor1)
	(on crate8 crate7)
	(at truck1 distributor0)
	(at crate3 depot0)
	(clear crate12)
	(at crate9 distributor1)
	(on crate5 crate2)
	(on crate11 crate6)
	(at crate0 distributor0)
	(in crate4 truck1)
	(at hoist0 depot0)
	(on crate0 pallet4)
	(on crate2 crate0)
	(on crate0 crate5)
	(at crate3 distributor0)
	(at crate4 distributor0)
	(clear pallet1)
	(on crate3 crate0)
	(at hoist2 distributor1)
	(on crate5 pallet0)
	(at crate5 depot0)
	(at crate13 distributor0)
	(on crate11 pallet4)
	(on crate4 crate3)
	(available hoist0)
	(on crate0 pallet1)
	(on crate3 crate2)
	(on crate0 pallet0)
	(on crate3 pallet1)
	(at crate6 distributor0)
	(at crate3 distributor1)
	(on crate13 crate12)
	(clear pallet0)
	(on crate7 crate6)
	(on crate3 crate1)
	(on crate14 pallet3)
	(clear crate14)
	(in crate13 truck1)
	(at crate11 depot0)
	(at pallet3 distributor0)
	(at crate12 distributor0)
	(on crate9 crate1)
	(at crate7 distributor0)
	(at crate8 distributor0)
	(on crate12 crate11)
	(on crate1 pallet2)
	(on crate1 crate2)
	(at crate2 distributor1)
	(on crate7 crate4)
	(on crate12 crate9)
	(at hoist1 distributor0)
	(on crate6 crate3)
	(on crate1 pallet5)
	(on crate10 pallet2)
	(clear crate7)
	(clear crate0)
	(on crate6 pallet1)
	(available hoist1)
	(in crate8 truck0)
	(on crate9 crate8)
	(at crate14 distributor1)
	(on crate14 crate13)
	(available hoist2)
)
(:add
	(clear crate4)
	(on crate4 crate6)
	(available hoist1)
	(at crate4 distributor0)
	(lifting hoist1 crate4)
	(available hoist0)
	(at crate3 depot0)
	(on crate3 pallet0)
	(clear crate3)
	(clear crate1)
	(lifting hoist1 crate6)
	(available hoist1)
	(in crate12 truck0)
	(on crate12 crate14)
	(available hoist2)
	(at crate12 distributor1)
	(clear crate12)
	(clear crate13)
	(on crate13 crate3)
	(available hoist1)
	(at crate13 distributor0)
	(at truck0 distributor0)
	(lifting hoist0 crate3)
	(clear pallet1)
	(lifting hoist2 crate12)
	(clear crate11)
	(lifting hoist1 crate12)
	(lifting hoist1 crate11)
	(clear pallet4)
	(on crate6 pallet4)
	(clear crate6)
	(available hoist1)
	(at crate6 distributor0)
	(on crate11 pallet1)
	(clear crate11)
	(available hoist1)
	(at crate11 distributor0)
	(clear crate6)
	(lifting hoist1 crate7)
	(lifting hoist1 crate13)
)
(:delete
	(lifting hoist1 crate4)
	(clear crate6)
	(in crate4 truck1)
	(available hoist1)
	(lifting hoist0 crate3)
	(clear pallet0)
	(on crate6 crate1)
	(clear crate6)
	(available hoist1)
	(at crate6 distributor0)
	(lifting hoist1 crate12)
	(lifting hoist2 crate12)
	(clear crate14)
	(clear crate3)
	(lifting hoist1 crate13)
	(at truck0 distributor1)
	(available hoist0)
	(at crate3 depot0)
	(on crate3 pallet1)
	(clear crate3)
	(available hoist2)
	(in crate12 truck0)
	(at crate12 distributor0)
	(on crate12 crate11)
	(available hoist1)
	(clear crate12)
	(clear crate11)
	(available hoist1)
	(on crate11 pallet4)
	(at crate11 distributor0)
	(lifting hoist1 crate6)
	(clear pallet4)
	(clear pallet1)
	(lifting hoist1 crate11)
	(clear crate7)
	(at crate7 distributor0)
	(on crate7 crate6)
	(available hoist1)
	(available hoist1)
	(in crate13 truck1)
)
(:goal
	(on crate5 pallet5)
	(on crate9 crate1)
	(on crate4 crate6)
	(on crate11 pallet1)
	(on crate14 pallet3)
	(on crate12 crate14)
	(on crate0 crate5)
	(on crate3 pallet0)
	(on crate13 crate3)
	(on crate1 crate2)
	(on crate6 pallet4)
	(on crate2 crate10)
	(on crate10 pallet2)
)
(:current
	(on crate2 crate10)
	(on crate5 pallet5)
	(on crate0 crate5)
	(on crate14 pallet3)
	(on crate9 crate1)
	(on crate1 crate2)
	(on crate10 pallet2)
)
