8
(Lift hoist0 crate3 crate0 depot0)
(Lift hoist1 crate5 crate2 depot1)
(Lift hoist4 crate2 pallet0 distributor1)
(Lift hoist1 crate4 crate2 distributor0)
(Drop hoist1 crate5 pallet1 depot1)
(Drop hoist0 crate3 pallet7 depot0)
(Drop hoist1 crate4 pallet9 distributor0)
(Drop hoist4 crate2 pallet4 distributor1)
18
(:init
	(at pallet7 depot0)
	(on crate2 crate1)
	(on crate0 pallet1)
	(on crate4 crate0)
	(on crate11 pallet4)
	(on crate3 crate1)
	(on crate4 crate3)
	(on crate0 pallet0)
	(on crate8 crate7)
	(on crate5 pallet0)
	(at hoist3 distributor0)
	(on crate7 crate6)
	(on crate2 pallet3)
	(available hoist3)
	(on crate3 crate0)
	(at pallet0 depot0)
	(at crate5 depot2)
	(on crate3 pallet1)
	(at hoist4 distributor1)
	(at crate4 distributor0)
	(at hoist2 distributor1)
	(on crate0 pallet2)
	(on crate5 crate2)
	(at pallet1 depot1)
	(on crate5 pallet3)
	(at pallet2 distributor1)
	(on crate3 crate0)
	(at crate5 distributor1)
	(on crate14 crate11)
	(available hoist4)
	(at truck0 depot0)
	(on crate11 crate6)
	(at crate5 distributor1)
	(at pallet1 distributor0)
	(at hoist0 depot0)
	(at pallet3 distributor1)
	(clear crate8)
	(on crate1 pallet0)
	(on crate4 crate3)
	(at crate4 depot0)
	(at pallet0 depot0)
	(available hoist2)
	(at crate2 distributor1)
	(at hoist1 depot1)
	(on crate8 pallet5)
	(at hoist1 distributor0)
	(at crate5 depot2)
	(on crate13 crate9)
	(on crate1 crate0)
	(at hoist1 distributor0)
	(at crate3 distributor2)
	(available hoist1)
	(at hoist1 distributor0)
	(at pallet3 distributor0)
	(on crate2 crate0)
	(on crate3 crate2)
	(clear pallet1)
	(at hoist4 distributor1)
	(clear pallet4)
	(on crate5 crate4)
	(at pallet8 depot0)
	(on crate1 pallet1)
	(at pallet5 depot0)
	(clear pallet1)
	(at crate12 distributor0)
	(available hoist1)
	(at crate2 distributor1)
	(at crate7 distributor0)
	(at pallet4 distributor0)
	(at pallet1 distributor0)
	(at crate10 distributor1)
	(at crate8 distributor0)
	(at crate11 distributor0)
	(on crate10 crate5)
	(at crate6 distributor2)
	(at pallet2 distributor1)
	(available hoist0)
	(available hoist2)
	(on crate7 crate6)
	(at hoist2 depot2)
	(on crate4 crate2)
	(clear crate1)
	(at crate0 distributor2)
	(at hoist1 distributor0)
	(available hoist0)
	(at crate2 distributor1)
	(on crate0 pallet1)
	(available hoist0)
	(at crate3 distributor1)
	(at crate2 distributor1)
	(at crate2 depot2)
	(available hoist1)
	(at truck0 distributor1)
	(clear crate4)
	(at crate7 distributor2)
	(at truck1 distributor0)
	(on crate13 crate4)
	(at crate2 depot0)
	(at pallet3 distributor0)
	(clear crate0)
	(available hoist1)
	(on crate0 pallet2)
	(at crate1 depot0)
	(at pallet2 depot2)
	(at hoist0 depot0)
	(at crate11 depot0)
	(clear crate12)
	(clear pallet2)
	(clear crate8)
	(on crate6 crate3)
	(on crate3 crate0)
	(at pallet4 distributor1)
	(on crate6 pallet1)
	(clear pallet7)
	(at crate14 distributor0)
	(on crate1 pallet5)
	(at crate8 distributor2)
	(at pallet0 depot0)
	(at pallet5 distributor2)
	(clear crate1)
	(available hoist2)
	(clear pallet6)
	(available hoist0)
	(clear crate1)
	(at crate3 depot1)
	(available hoist2)
	(at hoist1 distributor0)
	(clear crate12)
	(at truck1 distributor0)
	(on crate6 crate1)
	(clear crate9)
	(at crate3 depot0)
	(on crate1 pallet0)
	(at crate1 depot0)
	(at crate5 depot0)
	(at hoist0 depot0)
	(on crate4 crate2)
	(on crate7 crate6)
	(at pallet3 distributor0)
	(on crate1 pallet2)
	(at crate0 distributor1)
	(at crate2 distributor0)
	(at crate9 distributor0)
	(clear crate10)
	(on crate9 crate8)
	(at hoist2 distributor1)
	(available hoist5)
	(at pallet2 depot2)
	(at pallet6 distributor1)
	(clear crate14)
	(at hoist5 distributor2)
	(at pallet4 distributor1)
	(at crate3 distributor0)
	(on crate3 pallet8)
	(on crate1 pallet0)
	(at hoist2 distributor1)
	(at pallet9 distributor0)
	(at crate13 distributor1)
	(clear crate2)
	(clear pallet3)
	(at crate9 distributor1)
	(at hoist2 distributor1)
	(on crate10 crate5)
	(at hoist2 distributor1)
	(clear crate3)
	(clear crate3)
	(at crate13 distributor0)
	(at hoist5 distributor2)
	(at pallet4 distributor1)
	(clear crate3)
	(at crate1 depot1)
	(at crate3 distributor0)
	(available hoist2)
	(at crate9 depot2)
	(clear crate13)
	(clear crate5)
	(at hoist2 distributor1)
	(on crate0 pallet1)
	(at crate8 distributor2)
	(at crate4 distributor0)
	(clear pallet3)
	(at crate6 distributor0)
	(at crate4 distributor0)
	(at pallet5 distributor2)
	(on crate4 crate0)
	(on crate0 pallet2)
	(on crate5 crate1)
	(at pallet0 depot0)
	(available hoist0)
	(on crate2 pallet2)
	(at hoist0 depot0)
	(at crate3 distributor0)
	(on crate11 pallet4)
	(clear crate2)
	(at crate0 depot0)
	(on crate12 crate9)
	(at crate10 depot1)
	(on crate7 crate4)
	(available hoist0)
	(at pallet1 distributor0)
	(clear crate13)
	(available hoist5)
	(on crate2 pallet2)
	(on crate8 crate7)
	(at crate1 depot0)
	(at crate14 distributor1)
	(clear crate4)
	(available hoist1)
	(at hoist0 depot0)
	(at hoist0 depot0)
	(at crate0 distributor1)
	(at hoist0 depot0)
	(at crate7 distributor2)
	(at crate9 distributor0)
	(at crate1 depot0)
	(available hoist0)
	(at crate1 depot0)
	(clear crate3)
	(at pallet2 distributor1)
	(on crate6 pallet5)
	(at crate8 depot0)
	(at crate4 distributor0)
	(clear pallet0)
	(clear crate1)
	(on crate2 crate1)
	(at hoist5 distributor2)
	(at crate0 distributor0)
	(on crate9 crate8)
	(at crate0 distributor0)
	(at crate14 distributor0)
	(at truck1 depot0)
	(on crate9 crate5)
	(at truck1 depot0)
	(at pallet0 depot0)
	(at crate4 distributor1)
	(at pallet5 distributor2)
	(at pallet0 depot0)
	(on crate3 pallet1)
	(at hoist2 distributor1)
	(clear crate14)
	(at crate1 distributor1)
	(available hoist3)
	(at crate6 distributor0)
	(on crate14 crate9)
	(at crate6 depot0)
	(at crate0 distributor1)
	(clear crate0)
	(at truck1 depot0)
	(at crate0 distributor0)
	(on crate10 crate5)
	(on crate1 pallet0)
	(on crate14 crate13)
	(at crate11 distributor1)
	(at crate0 depot2)
	(on crate7 crate6)
	(at truck1 distributor0)
	(clear crate4)
	(at truck0 depot0)
	(at truck0 distributor1)
	(available hoist0)
	(at pallet3 distributor0)
	(available hoist0)
	(clear crate14)
	(at pallet2 depot2)
	(at truck0 depot2)
	(clear crate10)
	(at crate0 depot1)
	(available hoist4)
	(at crate9 distributor2)
	(at crate12 distributor0)
	(at crate3 depot0)
	(at pallet1 depot1)
	(at crate2 depot0)
	(on crate4 pallet3)
	(at crate4 depot2)
	(at crate7 distributor0)
	(at truck0 distributor1)
	(clear pallet9)
	(at crate5 distributor1)
	(on crate5 crate1)
	(on crate5 crate2)
	(at crate10 distributor1)
	(clear crate2)
	(on crate9 crate5)
	(at crate1 depot2)
	(on crate12 crate11)
	(available hoist5)
	(at pallet0 depot0)
	(clear pallet4)
	(at crate1 depot0)
	(at crate1 distributor1)
	(at hoist2 depot2)
	(at truck0 distributor1)
	(on crate8 crate7)
	(at hoist0 depot0)
	(available hoist1)
	(available hoist1)
	(at truck0 depot0)
	(at truck1 depot0)
	(at crate13 distributor2)
	(on crate0 pallet5)
	(on crate4 crate3)
	(on crate2 pallet2)
	(on crate1 pallet0)
	(at pallet0 depot0)
	(at truck1 depot0)
	(clear crate9)
	(at hoist3 distributor0)
	(at hoist1 depot1)
	(at truck1 depot1)
	(at hoist1 distributor0)
	(on crate6 crate3)
	(on crate2 crate0)
	(on crate2 pallet0)
	(at crate5 depot1)
	(available hoist2)
	(at crate12 depot1)
	(available hoist2)
	(at pallet4 distributor0)
	(at truck0 distributor1)
	(at pallet0 depot0)
	(at pallet0 depot0)
	(at truck1 distributor0)
	(at pallet1 depot1)
	(on crate5 crate2)
	(available hoist0)
	(at pallet2 distributor1)
	(on crate0 pallet4)
	(at pallet1 distributor0)
	(clear crate5)
	(at pallet1 distributor0)
	(available hoist1)
	(clear crate11)
	(available hoist4)
	(at crate2 distributor1)
	(on crate3 pallet1)
	(at crate6 distributor2)
	(at pallet2 distributor1)
	(at crate7 distributor0)
	(clear crate4)
	(at pallet2 distributor1)
	(at crate5 distributor1)
	(at pallet1 distributor0)
	(at hoist0 depot0)
	(on crate13 crate12)
	(at crate8 distributor0)
	(available hoist2)
	(at hoist2 depot2)
	(available hoist1)
	(at hoist0 depot0)
	(clear pallet2)
	(at pallet1 distributor0)
	(at truck0 distributor0)
	(available hoist2)
	(on crate12 crate10)
	(on crate1 pallet0)
	(on crate8 crate7)
	(on crate9 crate7)
	(at hoist1 depot1)
	(available hoist3)
	(at hoist3 distributor0)
	(clear crate4)
	(available hoist1)
	(clear crate5)
	(at crate3 distributor0)
	(available hoist2)
	(at pallet5 distributor1)
	(at hoist4 distributor1)
	(at crate4 distributor0)
	(on crate0 pallet2)
	(at pallet2 distributor1)
	(clear crate8)
	(clear pallet5)
	(at hoist1 distributor0)
)
(:add
	(clear pallet0)
	(lifting hoist4 crate2)
	(at crate3 depot0)
	(available hoist0)
	(clear crate3)
	(on crate3 pallet7)
	(lifting hoist1 crate4)
	(clear crate2)
	(clear crate4)
	(at crate4 distributor0)
	(available hoist1)
	(on crate4 pallet9)
	(on crate5 pallet1)
	(clear crate5)
	(at crate5 depot1)
	(available hoist1)
	(lifting hoist0 crate3)
	(clear crate0)
	(lifting hoist1 crate5)
	(clear crate2)
	(at crate2 distributor1)
	(on crate2 pallet4)
	(clear crate2)
	(available hoist4)
)
(:delete
	(on crate2 pallet0)
	(at crate2 distributor1)
	(clear crate2)
	(available hoist4)
	(lifting hoist0 crate3)
	(clear pallet7)
	(on crate4 crate2)
	(clear crate4)
	(at crate4 distributor0)
	(available hoist1)
	(lifting hoist1 crate4)
	(clear pallet9)
	(clear pallet1)
	(lifting hoist1 crate5)
	(at crate3 depot0)
	(available hoist0)
	(clear crate3)
	(on crate3 crate0)
	(clear crate5)
	(at crate5 depot1)
	(on crate5 crate2)
	(available hoist1)
	(clear pallet4)
	(lifting hoist4 crate2)
)
(:goal
	(on crate5 pallet1)
	(on crate0 pallet0)
	(on crate1 pallet5)
	(on crate2 pallet4)
	(on crate3 pallet7)
	(on crate4 pallet9)
)
(:current
	(on crate0 pallet0)
	(on crate1 pallet5)
)
