10
(Load hoist1 crate0 truck1 distributor0)
(Drive truck0 distributor0 depot0)
(Drop hoist1 crate0 pallet1 distributor0)
(Drive truck1 distributor0 distributor1)
(Unload hoist0 crate5 truck0 depot0)
(Unload hoist2 crate0 truck1 distributor1)
(Unload hoist1 crate4 truck0 distributor0)
(Drop hoist0 crate5 crate0 depot0)
(Drop hoist2 crate0 crate1 distributor1)
(Drop hoist1 crate4 pallet1 distributor0)
