37
(Lift hoist13 crate10 crate5 depot1)
(Lift hoist6 crate15 pallet13 distributor2)
(Lift hoist2 crate19 crate4 distributor1)
(Lift hoist12 crate6 crate3 depot0)
(Lift hoist5 crate15 pallet13 distributor2)
(Lift hoist8 crate9 crate5 distributor2)
(Drive truck0 distributor1 distributor4)
(Lift hoist5 crate1 pallet4 depot1)
(Lift hoist5 crate17 crate12 depot1)
(Lift hoist10 crate18 pallet12 distributor4)
(Lift hoist6 crate11 pallet4 distributor0)
(Lift hoist2 crate12 pallet1 distributor0)
(Lift hoist3 crate0 pallet7 distributor1)
(Lift hoist7 crate13 crate7 distributor1)
(Lift hoist10 crate5 pallet3 distributor4)
(Lift hoist7 crate3 pallet1 distributor1)
(Lift hoist1 crate8 pallet1 distributor0)
(Lift hoist7 crate16 crate11 distributor3)
(Drop hoist6 crate11 pallet1 distributor0)
(Drop hoist5 crate15 crate7 distributor1)
(Drop hoist13 crate10 crate17 depot1)
(Drop hoist2 crate19 pallet9 depot2)
(Drop hoist5 crate1 pallet15 depot1)
(Drop hoist6 crate15 pallet7 depot0)
(Drop hoist1 crate8 crate10 depot1)
(Drop hoist7 crate3 pallet18 distributor3)
(Drop hoist12 crate6 pallet6 depot0)
(Drop hoist10 crate5 pallet12 distributor4)
(Drop hoist7 crate13 crate16 distributor3)
(Drop hoist5 crate17 pallet2 distributor1)
(Drop hoist2 crate12 pallet16 distributor1)
(Load hoist10 crate18 truck0 distributor4)
(Drop hoist3 crate0 pallet14 depot3)
(Drop hoist8 crate9 pallet17 distributor2)
(Unload hoist5 crate18 truck0 distributor2)
(Drop hoist7 crate16 crate15 distributor1)
(Drop hoist5 crate18 pallet4 depot1)
65
(:init
	(at crate4 distributor2)
	(at pallet7 depot0)
	(at crate14 distributor0)
	(available hoist5)
	(available hoist0)
	(on crate11 pallet4)
	(at pallet9 depot0)
	(at crate8 distributor0)
	(on crate3 crate0)
	(at crate15 distributor2)
	(clear pallet17)
	(at crate5 depot2)
	(on crate2 pallet4)
	(at truck2 depot1)
	(at pallet7 depot1)
	(at crate4 distributor0)
	(at hoist2 distributor1)
	(clear pallet2)
	(at pallet19 distributor1)
	(on crate0 pallet2)
	(available hoist6)
	(available hoist1)
	(at crate5 depot3)
	(clear pallet12)
	(at pallet12 distributor1)
	(at pallet1 depot1)
	(at crate5 distributor4)
	(at crate3 depot1)
	(at hoist6 distributor0)
	(on crate11 crate6)
	(available hoist2)
	(at hoist0 depot0)
	(at truck1 distributor0)
	(at hoist2 distributor0)
	(at hoist4 distributor0)
	(clear crate8)
	(at hoist0 depot0)
	(clear pallet5)
	(at pallet0 depot0)
	(at hoist1 depot1)
	(at hoist5 depot5)
	(at crate2 depot3)
	(on crate3 pallet6)
	(available hoist0)
	(available hoist1)
	(on crate2 pallet2)
	(on crate2 crate0)
	(available hoist4)
	(at pallet1 depot1)
	(clear pallet4)
	(clear pallet1)
	(at pallet9 distributor0)
	(clear pallet0)
	(clear pallet2)
	(at crate12 distributor0)
	(at pallet1 distributor0)
	(at crate10 distributor1)
	(at crate8 distributor0)
	(at crate14 depot1)
	(at crate6 distributor2)
	(at pallet2 distributor1)
	(available hoist0)
	(available hoist2)
	(on crate4 crate2)
	(available hoist3)
	(at pallet6 distributor2)
	(clear crate10)
	(at hoist1 distributor0)
	(at crate19 distributor1)
	(at hoist3 distributor1)
	(at crate13 distributor2)
	(available hoist2)
	(on crate0 pallet7)
	(at crate2 distributor1)
	(clear pallet3)
	(at crate2 depot2)
	(available hoist1)
	(at truck0 depot1)
	(at crate7 distributor2)
	(at crate7 depot1)
	(at crate0 depot0)
	(at crate1 depot0)
	(at hoist5 depot1)
	(at pallet4 distributor0)
	(at hoist0 depot0)
	(at crate11 depot0)
	(on crate14 pallet9)
	(available hoist1)
	(at pallet4 distributor1)
	(on crate6 pallet4)
	(at truck2 depot0)
	(available hoist6)
	(clear pallet7)
	(at crate9 distributor0)
	(available hoist5)
	(available hoist2)
	(clear pallet6)
	(available hoist0)
	(at crate17 depot1)
	(at pallet3 distributor1)
	(on crate1 pallet0)
	(clear crate11)
	(at pallet9 distributor3)
	(on crate9 pallet19)
	(at crate5 depot0)
	(available hoist2)
	(at hoist7 distributor1)
	(clear pallet11)
	(available hoist3)
	(on crate7 crate6)
	(on crate1 pallet2)
	(at crate9 distributor0)
	(at pallet5 distributor1)
	(at hoist5 distributor1)
	(at hoist4 distributor1)
	(at crate7 distributor2)
	(at crate2 distributor0)
	(available hoist1)
	(at pallet8 distributor2)
	(clear crate14)
	(at crate14 distributor4)
	(at pallet9 distributor0)
	(clear pallet14)
	(available hoist4)
	(clear crate7)
	(available hoist0)
	(clear crate14)
	(clear pallet6)
	(on crate3 pallet0)
	(clear crate3)
	(available hoist2)
	(at pallet1 depot1)
	(on crate0 pallet1)
	(at crate6 distributor0)
	(on crate4 pallet2)
	(at crate7 depot0)
	(at crate4 distributor0)
	(on crate4 crate0)
	(at crate1 depot0)
	(on crate0 pallet2)
	(at pallet10 distributor4)
	(at hoist0 depot0)
	(at hoist2 depot2)
	(on crate0 pallet0)
	(available hoist1)
	(at hoist0 depot0)
	(at hoist0 depot0)
	(at crate9 distributor0)
	(at crate1 depot0)
	(available hoist0)
	(at crate1 depot0)
	(at hoist7 distributor3)
	(on crate11 pallet9)
	(at truck3 distributor1)
	(at crate8 depot0)
	(at crate6 distributor1)
	(at pallet16 depot1)
	(at pallet0 depot0)
	(at crate1 depot1)
	(at pallet6 distributor0)
	(on crate14 crate9)
	(at crate6 depot0)
	(at truck1 depot0)
	(at crate12 distributor1)
	(at pallet6 distributor1)
	(on crate1 pallet0)
	(at pallet7 distributor0)
	(at crate11 distributor1)
	(on crate7 crate6)
	(on crate1 pallet9)
	(at truck0 depot0)
	(on crate15 pallet13)
	(at pallet8 distributor1)
	(at hoist3 depot3)
	(available hoist0)
	(at hoist1 depot1)
	(at pallet9 depot3)
	(at crate12 distributor0)
	(at pallet4 depot4)
	(clear crate4)
	(clear crate13)
	(at crate7 depot4)
	(at crate10 distributor1)
	(on crate9 crate2)
	(on crate10 crate9)
	(on crate1 pallet0)
	(at crate3 depot0)
	(on crate9 crate5)
	(at pallet6 depot1)
	(on crate7 pallet18)
	(clear pallet4)
	(at hoist2 depot2)
	(on crate7 pallet5)
	(available hoist1)
	(on crate0 pallet5)
	(at pallet0 depot0)
	(clear crate5)
	(on crate1 pallet0)
	(at truck1 depot0)
	(on crate2 pallet10)
	(at hoist5 depot0)
	(at hoist3 depot3)
	(at pallet6 depot0)
	(available hoist2)
	(at truck0 distributor1)
	(at hoist3 distributor1)
	(on crate8 crate6)
	(at crate4 distributor2)
	(at truck1 distributor0)
	(available hoist0)
	(at hoist6 distributor2)
	(on crate4 pallet7)
	(at pallet1 distributor0)
	(clear crate5)
	(at pallet1 distributor0)
	(at crate0 distributor1)
	(on crate3 pallet1)
	(at pallet2 distributor1)
	(at pallet2 distributor1)
	(on crate5 pallet7)
	(available hoist1)
	(at pallet0 depot0)
	(at hoist11 distributor5)
	(at pallet1 depot1)
	(on crate12 crate10)
	(at pallet5 distributor1)
	(on crate9 crate7)
	(at crate0 depot1)
	(clear crate4)
	(at pallet7 distributor1)
	(at crate10 distributor1)
	(at crate3 distributor0)
	(at truck3 depot1)
	(available hoist2)
	(at hoist8 distributor2)
	(at hoist4 distributor1)
	(at hoist0 depot0)
	(clear crate6)
	(at crate1 depot0)
	(clear pallet5)
	(at pallet3 distributor1)
	(on crate11 crate5)
	(at hoist2 depot2)
	(on crate0 pallet1)
	(clear crate4)
	(available hoist1)
	(at crate9 distributor1)
	(on crate3 pallet6)
	(on crate4 pallet8)
	(on crate3 crate1)
	(on crate5 pallet0)
	(at crate6 depot0)
	(at hoist1 depot1)
	(at pallet0 depot0)
	(at crate2 distributor4)
	(at hoist4 distributor1)
	(available hoist5)
	(available hoist2)
	(at pallet5 distributor0)
	(at pallet2 distributor1)
	(on crate3 crate0)
	(clear crate5)
	(on crate0 pallet5)
	(at pallet1 distributor0)
	(at crate1 depot1)
	(available hoist8)
	(available hoist6)
	(at crate2 depot0)
	(at crate4 depot0)
	(at crate2 distributor1)
	(available hoist11)
	(clear crate3)
	(available hoist4)
	(at pallet3 distributor0)
	(at pallet2 depot2)
	(at pallet11 distributor5)
	(available hoist0)
	(available hoist5)
	(on crate3 crate2)
	(on crate1 pallet1)
	(at pallet5 depot0)
	(available hoist7)
	(on crate12 crate10)
	(on crate19 crate4)
	(at hoist14 depot4)
	(at pallet4 depot0)
	(at hoist2 distributor0)
	(at crate3 depot0)
	(available hoist3)
	(at crate11 distributor0)
	(available hoist7)
	(on crate18 pallet12)
	(at hoist2 depot2)
	(clear crate1)
	(at crate4 depot1)
	(available hoist0)
	(clear crate5)
	(clear crate8)
	(on crate8 pallet7)
	(clear crate2)
	(at crate3 distributor1)
	(at crate2 distributor0)
	(at pallet2 depot2)
	(at truck5 distributor0)
	(at truck4 distributor3)
	(available hoist3)
	(clear crate4)
	(on crate13 crate4)
	(at pallet3 distributor1)
	(at pallet3 depot3)
	(available hoist2)
	(at hoist13 depot5)
	(available hoist1)
	(at hoist4 distributor1)
	(at truck1 depot1)
	(clear crate8)
	(clear crate4)
	(at crate11 depot1)
	(at pallet19 depot1)
	(clear crate13)
	(at hoist9 distributor3)
	(available hoist5)
	(at truck0 distributor2)
	(at crate8 distributor2)
	(available hoist4)
	(at pallet17 distributor2)
	(at pallet0 depot0)
	(clear crate13)
	(at crate3 depot1)
	(available hoist2)
	(at hoist1 distributor0)
	(available hoist1)
	(available hoist6)
	(at pallet7 distributor3)
	(clear crate9)
	(at truck0 depot1)
	(at crate1 depot0)
	(at pallet0 depot0)
	(on crate6 pallet5)
	(at pallet7 distributor1)
	(at hoist0 depot0)
	(at crate7 distributor1)
	(at pallet3 distributor0)
	(available hoist3)
	(at hoist2 distributor1)
	(at crate5 depot0)
	(at pallet2 depot2)
	(clear crate9)
	(available hoist0)
	(on crate3 pallet8)
	(clear crate3)
	(clear crate1)
	(on crate8 crate6)
	(at crate0 distributor3)
	(clear crate2)
	(at crate9 distributor0)
	(on crate10 crate5)
	(available hoist4)
	(clear crate3)
	(clear pallet0)
	(on crate7 pallet6)
	(clear crate12)
	(at crate9 depot2)
	(at crate8 distributor1)
	(on crate17 crate12)
	(at crate4 distributor0)
	(at crate11 depot1)
	(on crate3 pallet6)
	(on crate1 pallet1)
	(at pallet5 distributor2)
	(at crate1 distributor1)
	(clear crate0)
	(on crate2 pallet0)
	(on crate2 pallet2)
	(on crate1 pallet1)
	(clear crate2)
	(at crate0 depot0)
	(at crate10 depot1)
	(clear pallet2)
	(available hoist5)
	(on crate2 pallet2)
	(on crate8 crate7)
	(at crate1 depot0)
	(at crate5 distributor1)
	(at hoist0 depot0)
	(at pallet3 depot3)
	(at crate9 depot1)
	(at pallet5 distributor1)
	(at hoist4 depot4)
	(clear crate1)
	(available hoist14)
	(at truck2 distributor2)
	(at hoist5 distributor2)
	(at pallet1 depot1)
	(on crate2 pallet4)
	(at crate10 depot0)
	(at crate8 depot5)
	(at crate4 distributor1)
	(at hoist0 depot0)
	(at pallet14 depot3)
	(clear crate2)
	(at hoist2 depot2)
	(at hoist2 distributor0)
	(at pallet4 depot1)
	(clear crate10)
	(available hoist3)
	(at crate6 distributor0)
	(clear crate0)
	(clear crate8)
	(at crate0 distributor0)
	(at crate13 depot2)
	(on crate10 crate5)
	(at hoist1 depot1)
	(at pallet0 depot0)
	(on crate0 pallet3)
	(at crate3 distributor2)
	(clear crate7)
	(at truck0 depot2)
	(at crate0 depot1)
	(available hoist4)
	(clear pallet4)
	(at pallet4 distributor0)
	(at crate9 distributor2)
	(on crate5 crate2)
	(available hoist13)
	(clear crate6)
	(at crate1 depot2)
	(available hoist7)
	(available hoist5)
	(on crate14 crate5)
	(at pallet0 depot0)
	(at truck1 depot0)
	(at hoist1 depot1)
	(available hoist10)
	(at hoist3 distributor0)
	(at hoist10 distributor4)
	(on crate6 crate3)
	(on crate2 crate0)
	(at crate11 distributor2)
	(at crate12 depot1)
	(at pallet4 distributor0)
	(at hoist2 depot2)
	(at pallet0 depot0)
	(at crate9 distributor1)
	(at pallet0 depot0)
	(on crate8 crate7)
	(at crate2 distributor5)
	(at truck2 depot0)
	(at hoist12 depot5)
	(at pallet1 depot1)
	(on crate5 crate3)
	(at pallet2 distributor1)
	(on crate0 pallet4)
	(at crate4 depot0)
	(at crate6 depot1)
	(at pallet5 depot5)
	(at truck4 depot0)
	(available hoist4)
	(at pallet1 distributor0)
	(at hoist0 depot0)
	(clear crate14)
	(on crate3 crate2)
	(at crate8 distributor0)
	(at truck3 distributor1)
	(clear crate11)
	(at hoist1 depot1)
	(available hoist3)
	(on crate5 crate2)
	(at hoist3 distributor1)
	(at crate5 depot1)
	(available hoist12)
	(at truck0 depot2)
	(on crate9 crate1)
	(clear crate11)
	(at crate3 distributor1)
	(at crate9 depot0)
	(at pallet5 distributor1)
	(on crate6 pallet17)
	(at truck0 depot1)
	(at crate4 distributor0)
	(on crate0 pallet2)
	(at hoist5 depot0)
	(on crate13 crate3)
	(available hoist9)
	(at crate6 depot4)
	(at truck2 depot1)
	(on crate2 crate1)
	(on crate4 crate3)
	(on crate0 pallet0)
	(at hoist3 distributor0)
	(available hoist3)
	(clear crate6)
	(on crate8 pallet1)
	(on crate3 pallet1)
	(at crate6 distributor1)
	(clear pallet16)
	(available hoist7)
	(available hoist3)
	(clear crate14)
	(at pallet7 distributor1)
	(on crate5 pallet3)
	(on crate11 pallet8)
	(on crate13 crate3)
	(at pallet1 depot1)
	(at hoist0 depot0)
	(available hoist4)
	(at truck0 depot0)
	(at hoist1 depot1)
	(at pallet15 depot3)
	(clear crate5)
	(at crate5 distributor1)
	(available hoist4)
	(at hoist7 distributor1)
	(on crate1 pallet0)
	(at pallet8 depot1)
	(on crate4 crate3)
	(on crate0 pallet11)
	(available hoist2)
	(on crate12 crate6)
	(at crate16 distributor3)
	(available hoist14)
	(clear crate5)
	(available hoist2)
	(on crate3 crate1)
	(at hoist1 depot1)
	(on crate8 pallet5)
	(at hoist9 distributor3)
	(at hoist1 distributor0)
	(at pallet2 depot2)
	(at crate5 depot2)
	(on crate13 crate9)
	(on crate1 crate0)
	(at crate3 distributor2)
	(at crate12 depot1)
	(clear pallet1)
	(at pallet17 distributor2)
	(at pallet3 distributor0)
	(at crate2 depot2)
	(available hoist1)
	(at crate2 distributor1)
	(at crate7 distributor0)
	(clear crate4)
	(at pallet4 distributor1)
	(available hoist1)
	(at crate5 depot1)
	(clear pallet19)
	(at crate1 distributor1)
	(on crate5 crate0)
	(on crate7 crate6)
	(at crate0 distributor2)
	(at pallet2 distributor0)
	(clear crate3)
	(available hoist0)
	(available hoist9)
	(at truck0 distributor2)
	(on crate0 pallet1)
	(available hoist0)
	(on crate5 crate1)
	(on crate10 crate9)
	(clear crate0)
	(at truck1 distributor0)
	(at crate2 depot0)
	(clear crate0)
	(on crate0 pallet2)
	(available hoist12)
	(clear crate8)
	(clear crate12)
	(at crate12 depot1)
	(at crate0 distributor5)
	(at truck3 depot0)
	(at hoist14 depot5)
	(at pallet5 distributor1)
	(on crate3 crate0)
	(at crate2 distributor0)
	(at crate14 distributor0)
	(at pallet5 distributor2)
	(at pallet13 distributor5)
	(clear crate9)
	(clear crate1)
	(at crate4 depot0)
	(at pallet11 distributor5)
	(at pallet2 depot2)
	(clear crate7)
	(available hoist6)
	(at crate10 distributor1)
	(on crate6 crate1)
	(clear crate9)
	(available hoist6)
	(on crate4 crate2)
	(at hoist4 distributor1)
	(at crate2 distributor0)
	(available hoist5)
	(clear crate10)
	(at crate3 depot1)
	(on crate9 crate8)
	(available hoist5)
	(available hoist10)
	(at pallet6 distributor1)
	(clear crate14)
	(clear crate8)
	(at hoist5 distributor2)
	(at pallet4 distributor1)
	(available hoist7)
	(on crate11 crate1)
	(on crate1 pallet0)
	(at crate0 distributor1)
	(at pallet4 distributor0)
	(at crate13 distributor1)
	(at truck0 depot0)
	(clear pallet10)
	(at pallet0 depot0)
	(clear pallet6)
	(at crate9 distributor1)
	(on crate7 pallet3)
	(at hoist2 distributor1)
	(at hoist2 distributor1)
	(clear crate3)
	(available hoist13)
	(at crate13 distributor0)
	(clear pallet7)
	(at hoist7 distributor1)
	(at pallet3 depot3)
	(on crate10 crate1)
	(at pallet2 depot2)
	(clear crate5)
	(at crate4 depot0)
	(at crate8 distributor2)
	(clear pallet3)
	(at hoist0 depot0)
	(at pallet1 depot1)
	(on crate2 pallet3)
	(at pallet0 depot0)
	(on crate0 pallet16)
	(at truck2 distributor3)
	(at crate0 depot1)
	(clear crate7)
	(at crate3 distributor0)
	(on crate11 pallet4)
	(at crate4 depot1)
	(at hoist3 distributor0)
	(at crate8 distributor0)
	(at pallet5 depot5)
	(on crate7 crate4)
	(available hoist0)
	(at pallet1 distributor0)
	(clear crate13)
	(at crate12 distributor0)
	(available hoist5)
	(clear crate4)
	(at pallet18 depot4)
	(at crate4 distributor0)
	(at crate14 distributor0)
	(at crate10 distributor3)
	(available hoist6)
	(clear crate3)
	(available hoist11)
	(at pallet2 distributor1)
	(clear crate8)
	(on crate13 crate7)
	(at crate8 distributor2)
	(at hoist10 distributor4)
	(at pallet2 distributor0)
	(clear crate1)
	(on crate2 crate1)
	(at crate3 depot2)
	(at pallet15 depot1)
	(on crate4 crate0)
	(available hoist8)
	(at crate0 distributor0)
	(on crate9 crate8)
	(at crate0 distributor0)
	(at crate14 distributor0)
	(at truck1 distributor2)
	(on crate9 pallet3)
	(at hoist2 depot2)
	(at truck1 depot0)
	(at pallet7 distributor3)
	(on crate3 pallet1)
	(at hoist2 distributor1)
	(clear crate14)
	(clear crate3)
	(at pallet0 depot0)
	(at hoist1 depot1)
	(at crate0 distributor1)
	(clear crate9)
	(at crate0 depot2)
	(at hoist12 depot0)
	(at hoist13 depot1)
	(clear crate4)
	(clear crate0)
	(at truck0 distributor1)
	(at pallet3 distributor0)
	(available hoist0)
	(at pallet2 depot2)
	(at crate3 distributor2)
	(at crate3 depot0)
	(at crate2 depot0)
	(on crate4 pallet3)
	(at crate4 depot2)
	(at crate7 distributor0)
	(at truck0 distributor1)
	(on crate5 crate2)
	(at hoist1 depot1)
	(clear pallet2)
	(at pallet0 depot0)
	(at hoist2 depot2)
	(at pallet0 depot0)
	(at pallet5 distributor2)
	(at crate1 distributor1)
	(available hoist1)
	(at truck0 depot0)
	(on crate2 pallet2)
	(at truck1 depot0)
	(clear crate9)
	(at truck2 depot2)
	(on crate0 pallet9)
	(at hoist1 distributor0)
	(clear crate4)
	(on crate6 pallet0)
	(at crate5 depot1)
	(available hoist2)
	(at truck1 distributor1)
	(on crate16 crate11)
	(on crate6 pallet1)
	(available hoist4)
	(on crate5 crate2)
	(at pallet3 depot3)
	(on crate1 pallet5)
	(on crate8 pallet3)
	(at hoist6 depot1)
	(at pallet13 distributor2)
	(available hoist1)
	(at hoist5 distributor2)
	(at crate2 distributor1)
	(at pallet14 depot2)
	(at crate3 distributor1)
	(clear crate4)
	(at crate5 distributor1)
	(clear crate0)
	(at hoist2 depot2)
	(at hoist4 depot4)
	(at hoist0 depot0)
	(on crate5 crate0)
	(available hoist3)
	(available hoist2)
	(on crate8 crate7)
	(on crate0 pallet4)
	(clear crate5)
	(on crate7 crate4)
	(clear crate8)
	(at crate2 distributor0)
	(at truck0 distributor1)
	(clear pallet2)
	(on crate4 crate0)
	(on crate4 pallet6)
	(at pallet8 distributor2)
	(available hoist7)
	(on crate8 crate7)
	(on crate7 crate6)
	(on crate2 pallet3)
	(available hoist3)
	(at pallet2 depot2)
	(at pallet3 distributor0)
	(on crate9 pallet7)
	(at hoist4 distributor0)
	(available hoist3)
	(at truck1 distributor0)
	(on crate5 crate2)
	(clear pallet5)
	(at hoist7 distributor1)
	(on crate3 pallet8)
	(at pallet9 distributor3)
	(at hoist3 depot3)
	(at pallet2 distributor0)
	(at crate5 distributor1)
	(at crate13 depot0)
	(at pallet4 distributor1)
	(on crate14 crate11)
	(on crate12 pallet1)
	(available hoist4)
	(on crate9 pallet2)
	(clear crate19)
	(at pallet3 distributor1)
	(at hoist4 depot0)
	(clear pallet9)
	(available hoist4)
	(clear pallet9)
	(clear pallet3)
	(available hoist2)
	(available hoist2)
	(at hoist1 distributor0)
	(clear crate16)
	(on crate4 pallet1)
	(at hoist1 distributor0)
	(at crate0 depot3)
	(at hoist4 distributor1)
	(clear pallet4)
	(on crate5 crate4)
	(at hoist6 distributor2)
	(at pallet8 depot0)
	(clear crate7)
	(available hoist1)
	(at pallet4 distributor0)
	(at hoist0 depot0)
	(on crate1 pallet1)
	(available hoist1)
	(on crate12 crate2)
	(on crate10 crate5)
	(at pallet1 depot1)
	(clear crate13)
	(at crate2 distributor1)
	(clear pallet6)
	(available hoist0)
	(at crate11 distributor3)
	(clear pallet5)
	(available hoist0)
	(at pallet8 depot2)
	(at crate4 distributor1)
	(at truck0 distributor1)
	(at pallet3 distributor0)
	(clear crate18)
	(at pallet2 depot2)
	(clear pallet2)
	(at hoist7 distributor3)
	(on crate6 crate3)
	(on crate6 pallet1)
	(on crate1 pallet5)
	(at hoist6 depot0)
	(at hoist5 depot5)
	(on crate7 crate5)
	(clear crate1)
	(on crate1 pallet5)
	(clear crate2)
	(at pallet6 distributor2)
	(at pallet0 depot0)
	(at truck1 distributor4)
	(available hoist7)
	(on crate2 pallet8)
	(clear crate12)
	(at crate5 depot0)
	(at crate8 distributor1)
	(at truck1 distributor0)
	(at crate3 depot0)
	(on crate9 crate1)
	(on crate5 crate2)
	(at crate0 distributor1)
	(clear crate1)
	(available hoist5)
	(at crate8 depot1)
	(available hoist5)
	(at hoist6 distributor0)
	(at crate3 distributor0)
	(on crate13 crate4)
	(at pallet12 distributor4)
	(at hoist2 distributor1)
	(at truck3 distributor3)
	(clear pallet3)
	(clear crate17)
	(clear crate0)
	(on crate8 crate7)
	(at hoist5 distributor2)
	(at pallet4 distributor1)
	(at crate1 depot1)
	(at crate3 distributor0)
	(clear crate13)
	(at hoist2 distributor1)
	(clear pallet3)
	(at hoist11 distributor5)
	(at pallet9 depot2)
	(at pallet1 depot1)
	(at crate0 distributor2)
	(at hoist0 depot0)
	(at hoist8 distributor2)
	(clear crate5)
	(at crate7 depot3)
	(at crate1 depot0)
	(at truck5 depot4)
	(on crate5 crate1)
	(on crate6 pallet7)
	(available hoist0)
	(on crate14 crate12)
	(on crate3 pallet15)
	(at hoist0 depot0)
	(at crate18 distributor4)
	(at hoist1 depot1)
	(on crate12 crate9)
	(at crate14 distributor1)
	(clear crate4)
	(on crate10 crate0)
	(at crate0 distributor1)
	(at crate7 distributor2)
	(at truck1 depot2)
	(on crate6 pallet5)
	(on crate14 crate12)
	(at crate4 distributor0)
	(at pallet7 distributor0)
	(on crate4 pallet8)
	(at crate7 depot5)
	(clear pallet0)
	(at hoist5 distributor1)
	(at crate6 depot1)
	(at truck1 depot0)
	(on crate9 crate5)
	(on crate6 pallet1)
	(at pallet5 distributor2)
	(at pallet0 depot0)
	(on crate4 crate3)
	(at hoist7 distributor1)
	(at crate5 distributor1)
	(at crate1 distributor1)
	(at crate6 distributor2)
	(at hoist3 distributor0)
	(on crate14 crate13)
	(clear pallet14)
	(at pallet7 depot1)
	(on crate4 pallet0)
	(at pallet4 depot4)
	(at truck1 distributor0)
	(on crate2 pallet3)
	(clear pallet7)
	(clear crate14)
	(at crate1 depot1)
	(available hoist0)
	(clear crate10)
	(on crate7 crate6)
	(at truck3 depot0)
	(clear crate10)
	(at pallet1 depot1)
	(at truck1 depot0)
	(clear pallet9)
	(at pallet0 depot0)
	(at crate5 distributor1)
	(on crate0 pallet8)
	(at pallet6 distributor0)
	(on crate5 crate1)
	(clear crate2)
	(at hoist5 distributor2)
	(on crate12 crate11)
	(at crate1 distributor1)
	(available hoist1)
	(at crate5 distributor2)
	(at crate13 depot0)
	(at crate1 depot0)
	(at truck0 distributor1)
	(on crate8 crate7)
	(at hoist0 depot0)
	(at hoist3 depot3)
	(at crate13 distributor2)
	(clear crate8)
	(clear crate15)
	(on crate4 crate3)
	(on crate5 pallet1)
	(on crate1 pallet0)
	(clear pallet4)
	(at hoist4 distributor0)
	(at hoist6 distributor0)
	(at hoist1 depot1)
	(at truck1 depot1)
	(at pallet8 distributor2)
	(on crate2 pallet0)
	(clear crate8)
	(at truck3 distributor0)
	(at pallet18 distributor3)
	(available hoist2)
	(on crate1 pallet4)
	(clear pallet15)
	(at pallet1 depot1)
	(at pallet6 depot1)
	(at crate9 distributor0)
	(clear pallet6)
	(clear crate11)
	(at crate6 distributor2)
	(at hoist0 depot0)
	(at crate7 distributor0)
	(on crate6 pallet4)
	(on crate2 pallet13)
	(at pallet5 distributor2)
	(on crate13 crate12)
	(available hoist2)
	(clear pallet7)
	(clear crate3)
	(clear pallet2)
	(at truck0 depot1)
	(clear pallet18)
	(at pallet1 distributor0)
	(clear pallet2)
	(at truck0 distributor0)
	(at pallet16 distributor1)
	(on crate1 pallet0)
	(at crate7 distributor1)
	(at hoist3 distributor0)
	(at pallet6 distributor2)
	(on crate3 pallet5)
	(available hoist1)
	(at crate6 distributor0)
	(on crate7 crate6)
	(clear crate9)
	(at pallet2 distributor1)
	(at pallet10 distributor4)
	(at hoist1 distributor0)
)
(:add
	(clear crate6)
	(on crate6 pallet6)
	(at crate6 depot0)
	(available hoist12)
	(lifting hoist5 crate1)
	(clear pallet4)
	(lifting hoist5 crate18)
	(available hoist10)
	(in crate18 truck0)
	(at crate0 depot3)
	(available hoist3)
	(clear crate0)
	(on crate0 pallet14)
	(lifting hoist7 crate3)
	(clear pallet1)
	(available hoist7)
	(at crate3 distributor3)
	(clear crate3)
	(on crate3 pallet18)
	(clear pallet13)
	(lifting hoist5 crate15)
	(lifting hoist6 crate15)
	(clear pallet13)
	(at crate16 distributor1)
	(available hoist7)
	(clear crate16)
	(on crate16 crate15)
	(available hoist6)
	(on crate15 pallet7)
	(clear crate15)
	(at crate15 depot0)
	(on crate17 pallet2)
	(at crate17 distributor1)
	(available hoist5)
	(clear crate17)
	(lifting hoist13 crate10)
	(clear crate5)
	(clear crate10)
	(available hoist13)
	(at crate10 depot1)
	(on crate10 crate17)
	(available hoist6)
	(clear crate11)
	(at crate11 distributor0)
	(on crate11 pallet1)
	(lifting hoist2 crate12)
	(clear pallet1)
	(lifting hoist10 crate18)
	(clear pallet12)
	(lifting hoist8 crate9)
	(clear crate5)
	(at crate9 distributor2)
	(on crate9 pallet17)
	(available hoist8)
	(clear crate9)
	(available hoist1)
	(clear crate8)
	(on crate8 crate10)
	(at crate8 depot1)
	(available hoist7)
	(on crate13 crate16)
	(clear crate13)
	(at crate13 distributor3)
	(at crate19 depot2)
	(available hoist2)
	(clear crate19)
	(on crate19 pallet9)
	(clear crate11)
	(lifting hoist7 crate16)
	(lifting hoist10 crate5)
	(clear pallet3)
	(lifting hoist12 crate6)
	(clear crate3)
	(clear crate12)
	(lifting hoist5 crate17)
	(clear crate15)
	(available hoist5)
	(on crate15 crate7)
	(at crate15 distributor1)
	(clear pallet7)
	(lifting hoist3 crate0)
	(available hoist10)
	(at crate5 distributor4)
	(on crate5 pallet12)
	(clear crate5)
	(available hoist5)
	(clear crate18)
	(on crate18 pallet4)
	(at crate18 depot1)
	(clear crate7)
	(lifting hoist7 crate13)
	(at crate12 distributor1)
	(clear crate12)
	(on crate12 pallet16)
	(available hoist2)
	(clear pallet4)
	(lifting hoist6 crate11)
	(at truck0 distributor4)
	(on crate1 pallet15)
	(available hoist5)
	(at crate1 depot1)
	(clear crate1)
	(lifting hoist2 crate19)
	(clear crate4)
	(lifting hoist1 crate8)
	(clear pallet1)
)
(:delete
	(lifting hoist12 crate6)
	(clear pallet6)
	(on crate1 pallet4)
	(at crate1 depot1)
	(available hoist5)
	(clear crate1)
	(available hoist5)
	(in crate18 truck0)
	(lifting hoist10 crate18)
	(clear pallet14)
	(lifting hoist3 crate0)
	(at crate3 distributor1)
	(available hoist7)
	(clear crate3)
	(on crate3 pallet1)
	(clear pallet18)
	(lifting hoist7 crate3)
	(on crate15 pallet13)
	(clear crate15)
	(at crate15 distributor2)
	(available hoist5)
	(available hoist6)
	(on crate15 pallet13)
	(clear crate15)
	(at crate15 distributor2)
	(clear crate15)
	(lifting hoist7 crate16)
	(clear pallet7)
	(lifting hoist6 crate15)
	(clear pallet2)
	(lifting hoist5 crate17)
	(clear crate10)
	(on crate10 crate5)
	(at crate10 depot1)
	(available hoist13)
	(lifting hoist13 crate10)
	(clear crate17)
	(lifting hoist6 crate11)
	(clear pallet1)
	(on crate12 pallet1)
	(clear crate12)
	(available hoist2)
	(at crate12 distributor0)
	(at crate18 distributor4)
	(on crate18 pallet12)
	(available hoist10)
	(clear crate18)
	(on crate9 crate5)
	(at crate9 distributor2)
	(available hoist8)
	(clear crate9)
	(clear pallet17)
	(lifting hoist8 crate9)
	(clear crate10)
	(lifting hoist1 crate8)
	(clear crate16)
	(lifting hoist7 crate13)
	(lifting hoist2 crate19)
	(clear pallet9)
	(clear crate16)
	(available hoist7)
	(at crate16 distributor3)
	(on crate16 crate11)
	(at crate5 distributor4)
	(available hoist10)
	(clear crate5)
	(on crate5 pallet3)
	(clear crate6)
	(on crate6 crate3)
	(at crate6 depot0)
	(available hoist12)
	(clear crate17)
	(available hoist5)
	(on crate17 crate12)
	(at crate17 depot1)
	(clear crate7)
	(lifting hoist5 crate15)
	(on crate0 pallet7)
	(clear crate0)
	(available hoist3)
	(at crate0 distributor1)
	(clear pallet12)
	(lifting hoist10 crate5)
	(clear pallet4)
	(lifting hoist5 crate18)
	(at crate13 distributor1)
	(available hoist7)
	(clear crate13)
	(on crate13 crate7)
	(lifting hoist2 crate12)
	(clear pallet16)
	(clear crate11)
	(available hoist6)
	(at crate11 distributor0)
	(on crate11 pallet4)
	(at truck0 distributor1)
	(lifting hoist5 crate1)
	(clear pallet15)
	(at crate19 distributor1)
	(on crate19 crate4)
	(clear crate19)
	(available hoist2)
	(available hoist1)
	(clear crate8)
	(at crate8 distributor0)
	(on crate8 pallet1)
)
(:goal
	(on crate17 pallet2)
	(on crate1 pallet15)
	(on crate16 crate15)
	(on crate0 pallet14)
	(on crate6 pallet6)
	(on crate8 crate10)
	(on crate18 pallet4)
	(on crate9 pallet17)
	(on crate19 pallet9)
	(on crate15 pallet7)
	(on crate12 pallet16)
	(on crate13 crate16)
	(on crate7 pallet5)
	(on crate5 pallet12)
	(on crate3 pallet18)
	(on crate11 pallet1)
	(on crate10 crate17)
	(on crate2 pallet13)
)
(:current
	(on crate7 pallet5)
	(on crate2 pallet13)
)
