21
(Drive truck1 depot0 distributor0)
(Unload hoist0 crate7 truck1 depot0)
(Unload hoist0 crate6 truck0 depot0)
(Lift hoist0 crate9 crate0 depot0)
(Unload hoist0 crate2 truck0 depot0)
(Unload hoist0 crate5 truck0 depot0)
(Drop hoist0 crate2 crate0 depot0)
(Lift hoist0 crate0 crate4 depot0)
(Lift hoist0 crate0 pallet0 depot0)
(Drop hoist0 crate6 crate9 depot0)
(Drop hoist0 crate5 crate9 depot0)
(Lift hoist0 crate4 crate1 depot0)
(Drop hoist0 crate5 crate4 depot0)
(Drop hoist0 crate9 pallet0 depot0)
(Drop hoist0 crate0 crate5 depot0)
(Drop hoist0 crate7 crate1 depot0)
(Drop hoist0 crate4 crate6 depot0)
(Lift hoist0 crate1 pallet2 depot0)
(Load hoist0 crate1 truck1 depot0)
(Unload hoist1 crate1 truck1 distributor0)
(Drop hoist1 crate1 pallet1 distributor0)
4
(:init
	(at crate3 distributor1)
	(at pallet0 depot0)
	(on crate0 pallet0)
	(at truck0 depot0)
	(on crate3 pallet1)
	(at crate4 depot0)
	(on crate0 pallet1)
	(available hoist1)
	(at hoist2 distributor1)
	(on crate8 crate3)
	(at crate0 depot0)
	(on crate2 pallet2)
	(on crate2 crate1)
	(on crate3 crate0)
	(at pallet1 distributor0)
	(at crate8 distributor1)
	(at pallet2 distributor1)
	(available hoist2)
	(at crate9 depot0)
	(in crate7 truck1)
	(on crate4 crate1)
	(on crate0 crate4)
	(at crate1 depot0)
	(at hoist0 depot0)
	(on crate1 pallet0)
	(clear crate9)
	(at crate3 distributor0)
	(on crate3 pallet2)
	(available hoist0)
	(at crate4 distributor0)
	(on crate9 crate0)
	(clear pallet1)
	(in crate2 truck0)
	(at crate1 distributor1)
	(at truck1 depot0)
	(in crate5 truck0)
	(at crate0 distributor0)
	(on crate1 pallet2)
	(in crate6 truck0)
	(clear crate8)
	(at hoist1 distributor0)
)
(:add
	(in crate1 truck1)
	(available hoist0)
	(at crate0 depot0)
	(on crate0 crate5)
	(clear crate0)
	(available hoist0)
	(lifting hoist1 crate1)
	(lifting hoist0 crate4)
	(clear crate1)
	(on crate2 crate0)
	(at crate2 depot0)
	(clear crate2)
	(available hoist0)
	(lifting hoist0 crate2)
	(at truck1 distributor0)
	(lifting hoist0 crate7)
	(clear crate7)
	(on crate7 crate1)
	(at crate7 depot0)
	(available hoist0)
	(clear crate0)
	(lifting hoist0 crate9)
	(clear crate9)
	(available hoist0)
	(at crate9 depot0)
	(on crate9 pallet0)
	(at crate6 depot0)
	(clear crate6)
	(on crate6 crate9)
	(available hoist0)
	(lifting hoist0 crate1)
	(clear pallet2)
	(clear crate4)
	(at crate4 depot0)
	(on crate4 crate6)
	(available hoist0)
	(clear crate5)
	(at crate5 depot0)
	(available hoist0)
	(on crate5 crate4)
	(clear crate5)
	(at crate5 depot0)
	(available hoist0)
	(on crate5 crate9)
	(lifting hoist0 crate5)
	(lifting hoist0 crate0)
	(clear pallet0)
	(lifting hoist0 crate6)
	(available hoist1)
	(clear crate1)
	(at crate1 distributor0)
	(on crate1 pallet1)
	(clear crate4)
	(lifting hoist0 crate0)
)
(:delete
	(lifting hoist0 crate1)
	(lifting hoist0 crate0)
	(clear crate5)
	(available hoist1)
	(in crate1 truck1)
	(clear crate4)
	(on crate4 crate1)
	(at crate4 depot0)
	(available hoist0)
	(lifting hoist0 crate2)
	(clear crate0)
	(in crate2 truck0)
	(available hoist0)
	(at truck1 depot0)
	(available hoist0)
	(in crate7 truck1)
	(lifting hoist0 crate7)
	(clear crate1)
	(clear crate9)
	(available hoist0)
	(at crate9 depot0)
	(on crate9 crate0)
	(clear pallet0)
	(lifting hoist0 crate9)
	(clear crate9)
	(lifting hoist0 crate6)
	(on crate1 pallet2)
	(clear crate1)
	(at crate1 depot0)
	(available hoist0)
	(lifting hoist0 crate4)
	(clear crate6)
	(clear crate4)
	(lifting hoist0 crate5)
	(clear crate9)
	(lifting hoist0 crate5)
	(in crate5 truck0)
	(available hoist0)
	(at crate0 depot0)
	(clear crate0)
	(available hoist0)
	(on crate0 pallet0)
	(available hoist0)
	(in crate6 truck0)
	(clear pallet1)
	(lifting hoist1 crate1)
	(at crate0 depot0)
	(on crate0 crate4)
	(clear crate0)
	(available hoist0)
)
(:goal
	(on crate2 crate0)
	(on crate7 crate1)
	(on crate3 pallet2)
	(on crate0 crate5)
	(on crate4 crate6)
	(on crate1 pallet1)
	(on crate6 crate9)
	(on crate5 crate4)
	(on crate8 crate3)
	(on crate9 pallet0)
)
(:current
	(on crate8 crate3)
	(on crate3 pallet2)
)
