7
(Lift hoist0 crate1 pallet5 depot0)
(Drop hoist2 crate5 crate1 distributor1)
(Lift hoist1 crate8 crate7 distributor0)
(Lift hoist1 crate7 crate4 distributor0)
(Unload hoist2 crate4 truck1 distributor1)
(Drop hoist0 crate1 crate4 depot0)
(Drop hoist2 crate4 pallet5 distributor1)
6
(:init
	(at crate5 distributor1)
	(at crate1 depot0)
	(on crate2 pallet2)
	(at hoist0 depot0)
	(on crate3 crate0)
	(on crate2 crate1)
	(clear crate14)
	(on crate9 crate5)
	(at crate3 distributor0)
	(on crate0 pallet1)
	(clear crate11)
	(on crate4 crate3)
	(clear crate9)
	(clear pallet0)
	(on crate13 crate12)
	(at crate3 depot0)
	(in crate4 truck1)
	(on crate3 pallet1)
	(at crate2 distributor1)
	(at crate12 distributor0)
	(at crate6 depot0)
	(at pallet3 distributor0)
	(on crate0 pallet0)
	(at crate7 distributor0)
	(clear pallet1)
	(at crate8 distributor0)
	(at crate1 distributor1)
	(on crate6 crate1)
	(lifting hoist2 crate5)
	(clear crate8)
	(at crate0 distributor0)
	(on crate0 pallet3)
	(on crate10 crate5)
	(at crate9 distributor1)
	(on crate3 crate1)
	(on crate7 crate6)
	(available hoist0)
	(at crate14 distributor0)
	(at hoist1 distributor0)
	(on crate0 pallet2)
	(clear crate10)
	(on crate1 pallet2)
	(at crate6 distributor0)
	(at truck1 distributor1)
	(on crate8 crate7)
	(clear crate0)
	(at pallet0 depot0)
	(available hoist1)
	(clear pallet4)
	(on crate11 crate6)
	(on crate1 pallet5)
	(at crate11 depot0)
	(at pallet4 distributor0)
	(at truck0 distributor1)
	(clear crate1)
	(on crate7 crate4)
	(at crate10 distributor1)
	(on crate5 crate2)
	(on crate12 crate9)
	(at crate4 depot0)
	(on crate2 crate0)
	(at crate13 distributor0)
	(on crate6 pallet1)
	(in crate3 truck1)
	(on crate9 crate8)
	(clear crate2)
	(at hoist2 distributor1)
	(on crate1 pallet0)
	(at crate0 distributor1)
	(at crate0 depot0)
	(clear pallet2)
	(at pallet1 distributor0)
	(at crate9 distributor0)
	(at pallet5 distributor1)
	(on crate14 crate13)
	(at pallet2 distributor1)
)
(:add
	(on crate5 crate1)
	(at crate5 distributor1)
	(available hoist2)
	(clear crate5)
	(lifting hoist1 crate7)
	(clear crate4)
	(lifting hoist1 crate8)
	(clear crate7)
	(lifting hoist0 crate1)
	(clear pallet5)
	(on crate4 pallet5)
	(at crate4 distributor1)
	(available hoist2)
	(clear crate4)
	(lifting hoist2 crate4)
	(available hoist0)
	(clear crate1)
	(at crate1 depot0)
	(on crate1 crate4)
)
(:delete
	(lifting hoist2 crate5)
	(clear crate1)
	(at crate7 distributor0)
	(on crate7 crate4)
	(available hoist1)
	(clear crate7)
	(on crate8 crate7)
	(clear crate8)
	(at crate8 distributor0)
	(available hoist1)
	(available hoist0)
	(clear crate1)
	(at crate1 depot0)
	(on crate1 pallet5)
	(clear pallet5)
	(lifting hoist2 crate4)
	(available hoist2)
	(in crate4 truck1)
	(lifting hoist0 crate1)
	(clear crate4)
)
(:goal
	(on crate4 pallet5)
	(on crate5 crate1)
	(on crate0 pallet3)
	(on crate1 crate4)
	(on crate3 pallet1)
)
(:current
	(on crate3 pallet1)
	(on crate0 pallet3)
)
