5
(Drop hoist3 crate5 crate7 distributor1)
(Lift hoist6 crate1 crate0 depot0)
(Unload hoist5 crate4 truck3 distributor2)
(Drop hoist5 crate4 pallet5 distributor1)
(Drop hoist6 crate1 pallet8 depot0)
17
(:init
	(at pallet5 distributor0)
	(at crate0 distributor2)
	(available hoist5)
	(at crate1 distributor1)
	(at crate1 depot2)
	(at crate13 depot0)
	(at crate6 distributor2)
	(at pallet2 distributor0)
	(on crate8 pallet5)
	(clear crate13)
	(on crate6 crate1)
	(available hoist6)
	(at pallet8 distributor1)
	(on crate0 pallet3)
	(at pallet7 distributor0)
	(at crate3 distributor2)
	(at crate9 distributor1)
	(clear pallet1)
	(at hoist1 depot1)
	(at crate0 distributor0)
	(at hoist4 distributor0)
	(on crate3 pallet6)
	(at hoist0 depot0)
	(on crate6 pallet7)
	(at crate1 depot0)
	(at pallet4 depot0)
	(clear pallet0)
	(on crate4 pallet3)
	(at pallet1 depot1)
	(on crate2 crate1)
	(on crate2 pallet2)
	(at crate4 distributor0)
	(on crate9 crate5)
	(at crate6 distributor1)
	(at crate3 distributor0)
	(at crate13 depot2)
	(on crate4 pallet2)
	(at hoist3 distributor0)
	(on crate2 pallet8)
	(on crate5 pallet3)
	(at crate5 distributor2)
	(at hoist6 depot1)
	(on crate0 pallet4)
	(on crate2 crate0)
	(at hoist5 distributor2)
	(on crate1 pallet0)
	(at crate0 depot1)
	(at truck0 depot2)
	(at pallet5 distributor1)
	(at crate11 distributor2)
	(on crate12 crate10)
	(at pallet2 distributor1)
	(on crate0 pallet6)
	(at pallet3 distributor1)
	(at pallet1 distributor0)
	(on crate0 pallet2)
	(on crate11 crate5)
	(on crate4 pallet6)
	(at pallet5 distributor2)
	(at pallet5 depot0)
	(at truck3 depot0)
	(at crate9 depot2)
	(on crate9 pallet7)
	(at crate6 depot1)
	(at crate11 distributor0)
	(at pallet4 distributor0)
	(on crate11 crate6)
	(on crate11 crate1)
	(on crate0 pallet5)
	(available hoist4)
	(on crate7 pallet3)
	(clear crate7)
	(clear pallet7)
	(on crate1 pallet4)
	(on crate4 pallet1)
	(at pallet2 depot2)
	(on crate3 pallet1)
	(at pallet3 distributor0)
	(clear crate8)
	(at crate2 distributor1)
	(on crate0 pallet0)
	(on crate3 crate2)
	(at crate11 distributor1)
	(on crate13 crate9)
	(on crate4 pallet0)
	(on crate7 crate6)
	(at crate11 depot1)
	(at hoist7 distributor3)
	(on crate3 crate1)
	(on crate14 crate9)
	(on crate9 pallet3)
	(on crate11 pallet4)
	(on crate4 crate0)
	(on crate13 crate7)
	(at pallet7 depot1)
	(on crate5 pallet0)
	(clear crate9)
	(at pallet7 distributor3)
	(at pallet9 depot0)
	(clear crate11)
	(on crate3 crate0)
	(clear pallet3)
	(at crate3 depot1)
	(on crate9 pallet2)
	(at truck0 distributor0)
	(at crate4 depot1)
	(at hoist7 distributor1)
	(on crate0 pallet1)
	(at pallet9 depot3)
	(on crate10 crate9)
	(on crate4 crate2)
	(on crate1 crate0)
	(at hoist4 distributor1)
	(at hoist2 distributor1)
	(at hoist6 distributor0)
	(clear pallet2)
	(on crate6 pallet1)
	(on crate9 crate8)
	(at pallet8 depot2)
	(at pallet7 distributor1)
	(at truck2 depot2)
	(clear pallet5)
	(clear crate12)
	(on crate9 crate7)
	(on crate8 crate6)
	(at crate0 distributor1)
	(at pallet6 depot0)
	(at pallet8 depot0)
	(at hoist6 distributor2)
	(at crate5 depot1)
	(on crate1 pallet2)
	(at hoist3 distributor1)
	(at truck1 distributor1)
	(on crate0 pallet8)
	(in crate4 truck3)
	(at crate6 distributor0)
	(at hoist5 depot1)
	(on crate5 pallet7)
	(at crate4 distributor1)
	(at truck2 depot0)
	(on crate7 crate5)
	(clear crate10)
	(on crate1 pallet5)
	(on crate7 crate4)
	(clear crate6)
	(at hoist2 depot2)
	(at pallet4 depot1)
	(at crate3 depot0)
	(at hoist2 distributor0)
	(at truck1 distributor0)
	(at crate14 distributor0)
	(at hoist3 depot3)
	(on crate10 crate5)
	(at truck1 depot0)
	(at truck3 distributor2)
	(clear crate14)
	(at hoist4 depot0)
	(at crate3 depot2)
	(available hoist0)
	(at crate4 depot2)
	(at truck1 distributor2)
	(on crate8 pallet1)
	(on crate14 pallet9)
	(at truck1 depot2)
	(on crate2 pallet0)
	(on crate12 crate2)
	(at crate13 distributor1)
	(at crate12 distributor1)
	(at pallet6 depot1)
	(at pallet3 depot3)
	(available hoist2)
	(lifting hoist3 crate5)
	(at crate4 depot0)
	(at crate8 distributor1)
	(on crate5 crate0)
	(at truck0 depot1)
	(available hoist7)
	(at crate7 distributor1)
	(at crate0 depot0)
	(on crate6 pallet5)
	(on crate5 crate1)
	(at pallet0 depot0)
	(on crate13 crate4)
	(on crate8 crate7)
	(at crate8 distributor2)
	(clear crate1)
	(at hoist6 depot0)
	(on crate6 pallet4)
	(at crate10 distributor1)
	(at truck0 distributor1)
	(on crate13 crate3)
	(at crate0 depot2)
	(in crate2 truck0)
	(clear crate0)
	(on crate5 crate2)
	(at crate8 distributor0)
	(on crate13 crate12)
	(at crate7 distributor0)
	(on crate8 pallet3)
	(at crate2 depot0)
	(at crate12 distributor0)
	(on crate1 pallet1)
	(on crate14 crate12)
	(at crate7 depot3)
	(at hoist1 distributor0)
	(on crate3 pallet8)
	(at crate7 depot0)
	(on crate1 pallet9)
	(at hoist5 distributor1)
	(at pallet6 distributor1)
	(at crate7 distributor2)
	(at crate2 depot2)
	(at crate14 distributor1)
	(at crate10 depot1)
	(on crate2 pallet3)
	(at pallet9 distributor0)
	(at pallet4 distributor1)
	(on crate4 crate3)
	(at crate1 depot1)
	(on crate14 crate11)
	(at crate7 depot1)
	(lifting hoist1 crate3)
	(at hoist5 depot0)
	(at truck2 depot1)
	(at crate8 depot1)
	(at crate13 distributor0)
	(at crate5 depot0)
	(at pallet7 depot0)
	(on crate5 crate4)
	(at pallet8 distributor2)
	(at crate8 depot0)
	(clear pallet8)
	(on crate14 crate13)
	(at crate9 distributor0)
	(on crate9 crate2)
	(on crate10 crate1)
	(at crate5 depot2)
	(on crate12 crate11)
	(at crate12 depot1)
	(clear pallet9)
	(at truck1 depot1)
	(at crate13 distributor2)
	(on crate6 crate3)
	(at pallet6 distributor2)
	(at crate11 depot0)
	(at crate9 distributor2)
	(on crate12 crate9)
)
(:add
	(lifting hoist6 crate1)
	(clear crate0)
	(clear crate1)
	(at crate1 depot0)
	(on crate1 pallet8)
	(available hoist6)
	(on crate4 pallet5)
	(clear crate4)
	(available hoist5)
	(at crate4 distributor1)
	(clear crate5)
	(on crate5 crate7)
	(at crate5 distributor1)
	(available hoist3)
	(lifting hoist5 crate4)
)
(:delete
	(on crate1 crate0)
	(clear crate1)
	(at crate1 depot0)
	(available hoist6)
	(lifting hoist6 crate1)
	(clear pallet8)
	(clear pallet5)
	(lifting hoist5 crate4)
	(clear crate7)
	(lifting hoist3 crate5)
	(available hoist5)
	(in crate4 truck3)
)
(:goal
	(on crate0 pallet6)
	(on crate4 pallet5)
	(on crate6 pallet4)
	(on crate3 crate1)
	(on crate5 crate7)
	(on crate1 pallet8)
	(on crate7 crate4)
)
(:current
	(on crate0 pallet6)
	(on crate3 crate1)
	(on crate7 crate4)
	(on crate6 pallet4)
)
