9
(Lift hoist1 crate0 pallet1 distributor0)
(Load hoist0 crate1 truck1 depot0)
(Drive truck0 distributor1 distributor0)
(Drive truck1 depot0 distributor0)
(Load hoist1 crate0 truck0 distributor0)
(Unload hoist1 crate1 truck1 distributor0)
(Drop hoist1 crate1 pallet1 distributor0)
(Unload hoist2 crate0 truck0 distributor1)
(Drop hoist2 crate0 pallet2 distributor1)
0
(:init
	(clear pallet2)
	(at pallet1 distributor0)
	(at crate0 distributor0)
	(on crate0 pallet1)
	(at truck1 depot0)
	(at hoist0 depot0)
	(available hoist1)
	(at hoist1 distributor0)
	(at hoist2 distributor1)
	(at pallet2 distributor1)
	(clear crate0)
	(available hoist2)
	(at truck0 distributor1)
	(at pallet0 depot0)
	(clear pallet0)
	(lifting hoist0 crate1)
)
(:add
	(at truck0 distributor0)
	(available hoist0)
	(in crate1 truck1)
	(clear pallet1)
	(lifting hoist1 crate0)
	(available hoist1)
	(in crate0 truck0)
	(clear crate0)
	(on crate0 pallet2)
	(available hoist2)
	(at crate0 distributor1)
	(lifting hoist1 crate1)
	(lifting hoist2 crate0)
	(available hoist1)
	(at crate1 distributor0)
	(on crate1 pallet1)
	(clear crate1)
	(at truck1 distributor0)
)
(:delete
	(at truck0 distributor1)
	(lifting hoist0 crate1)
	(available hoist1)
	(clear crate0)
	(at crate0 distributor0)
	(on crate0 pallet1)
	(lifting hoist1 crate0)
	(clear pallet2)
	(lifting hoist2 crate0)
	(available hoist1)
	(in crate1 truck1)
	(in crate0 truck0)
	(available hoist2)
	(lifting hoist1 crate1)
	(clear pallet1)
	(at truck1 depot0)
)
(:goal
	(on crate1 pallet1)
	(on crate0 pallet2)
)
(:current
)
