34
(Lift hoist0 crate11 crate6 depot0)
(Lift hoist0 crate1 pallet0 depot0)
(Drive truck0 distributor0 distributor1)
(Drive truck1 distributor0 distributor1)
(Drive truck0 distributor0 depot0)
(Lift hoist2 crate1 pallet2 distributor1)
(Drive truck1 distributor0 depot0)
(Lift hoist0 crate0 pallet1 depot0)
(Lift hoist2 crate5 crate2 distributor1)
(Drop hoist1 crate14 crate8 distributor0)
(Lift hoist0 crate4 crate3 depot0)
(Lift hoist1 crate0 pallet1 distributor0)
(Drop hoist2 crate5 crate0 distributor1)
(Lift hoist1 crate9 crate5 distributor0)
(Unload hoist0 crate10 truck1 depot0)
(Load hoist0 crate11 truck0 depot0)
(Lift hoist1 crate3 crate0 distributor0)
(Drop hoist0 crate4 crate11 depot0)
(Lift hoist1 crate8 crate7 distributor0)
(Drop hoist2 crate1 crate9 distributor1)
(Lift hoist1 crate13 crate12 distributor0)
(Drop hoist1 crate3 crate12 distributor0)
(Drop hoist0 crate10 crate4 depot0)
(Unload hoist2 crate11 truck0 distributor1)
(Drop hoist1 crate0 crate8 distributor0)
(Lift hoist1 crate12 crate9 distributor0)
(Drop hoist1 crate9 pallet1 distributor0)
(Load hoist1 crate8 truck1 distributor0)
(Unload hoist0 crate8 truck1 depot0)
(Drop hoist2 crate11 crate5 distributor1)
(Load hoist1 crate12 truck1 distributor0)
(Drop hoist0 crate8 pallet0 depot0)
(Unload hoist2 crate12 truck1 distributor1)
(Drop hoist2 crate12 pallet2 distributor1)
49
(:init
	(at crate3 distributor0)
	(at truck0 distributor0)
	(on crate8 crate7)
	(at crate4 distributor0)
	(on crate1 pallet2)
	(clear crate4)
	(clear pallet2)
	(on crate0 pallet2)
	(on crate5 crate2)
	(on crate12 crate9)
	(on crate7 crate4)
	(at crate1 depot0)
	(at hoist0 depot0)
	(clear crate2)
	(clear crate5)
	(on crate11 crate6)
	(at crate5 distributor1)
	(on crate1 pallet0)
	(clear crate1)
	(at crate9 distributor1)
	(on crate9 crate8)
	(at hoist1 distributor0)
	(on crate6 pallet1)
	(on crate2 crate0)
	(at crate0 distributor0)
	(at crate12 distributor0)
	(at crate6 depot0)
	(at crate7 distributor0)
	(at crate1 distributor1)
	(at crate8 distributor0)
	(clear crate0)
	(at truck1 distributor0)
	(at crate3 depot0)
	(available hoist0)
	(at crate2 distributor1)
	(on crate2 pallet2)
	(on crate3 crate0)
	(clear crate13)
	(on crate2 crate1)
	(clear crate8)
	(at crate11 depot0)
	(on crate4 crate3)
	(at pallet0 depot0)
	(on crate0 pallet1)
	(on crate9 crate5)
	(available hoist2)
	(at crate6 distributor0)
	(clear crate9)
	(on crate6 crate1)
	(at pallet2 distributor1)
	(on crate0 pallet0)
	(clear crate11)
	(on crate3 pallet1)
	(at crate0 depot0)
	(at crate0 distributor1)
	(at crate9 distributor0)
	(at pallet1 distributor0)
	(on crate13 crate12)
	(on crate3 crate1)
	(on crate7 crate6)
	(at hoist2 distributor1)
	(lifting hoist1 crate14)
	(in crate10 truck1)
	(at crate4 depot0)
	(clear crate3)
	(at crate13 distributor0)
)
(:add
	(lifting hoist2 crate5)
	(clear crate2)
	(clear crate0)
	(lifting hoist1 crate3)
	(at truck0 distributor1)
	(clear pallet2)
	(lifting hoist2 crate1)
	(clear crate9)
	(at crate9 distributor0)
	(available hoist1)
	(on crate9 pallet1)
	(clear crate1)
	(on crate1 crate9)
	(at crate1 distributor1)
	(available hoist2)
	(lifting hoist0 crate8)
	(in crate11 truck0)
	(available hoist0)
	(lifting hoist0 crate4)
	(clear crate3)
	(on crate14 crate8)
	(available hoist1)
	(at crate14 distributor0)
	(clear crate14)
	(in crate12 truck1)
	(available hoist1)
	(clear crate5)
	(lifting hoist1 crate9)
	(at truck0 depot0)
	(on crate12 pallet2)
	(at crate12 distributor1)
	(clear crate12)
	(available hoist2)
	(on crate8 pallet0)
	(clear crate8)
	(at crate8 depot0)
	(available hoist0)
	(lifting hoist2 crate11)
	(lifting hoist0 crate10)
	(at truck1 depot0)
	(at crate11 distributor1)
	(available hoist2)
	(clear crate11)
	(on crate11 crate5)
	(available hoist1)
	(in crate8 truck1)
	(lifting hoist1 crate13)
	(clear crate12)
	(clear pallet1)
	(lifting hoist0 crate0)
	(clear pallet1)
	(lifting hoist1 crate0)
	(on crate4 crate11)
	(at crate4 depot0)
	(clear crate4)
	(available hoist0)
	(lifting hoist2 crate12)
	(lifting hoist0 crate11)
	(clear crate6)
	(at truck1 distributor1)
	(clear crate9)
	(lifting hoist1 crate12)
	(lifting hoist1 crate8)
	(clear crate7)
	(clear crate5)
	(at crate5 distributor1)
	(on crate5 crate0)
	(available hoist2)
	(clear pallet0)
	(lifting hoist0 crate1)
	(on crate3 crate12)
	(at crate3 distributor0)
	(available hoist1)
	(clear crate3)
	(available hoist1)
	(at crate0 distributor0)
	(on crate0 crate8)
	(clear crate0)
	(on crate10 crate4)
	(at crate10 depot0)
	(clear crate10)
	(available hoist0)
)
(:delete
	(on crate5 crate2)
	(clear crate5)
	(at crate5 distributor1)
	(available hoist2)
	(on crate3 crate0)
	(at crate3 distributor0)
	(available hoist1)
	(clear crate3)
	(at truck0 distributor0)
	(clear crate1)
	(on crate1 pallet2)
	(at crate1 distributor1)
	(available hoist2)
	(clear pallet1)
	(lifting hoist1 crate9)
	(clear crate9)
	(lifting hoist2 crate1)
	(in crate8 truck1)
	(available hoist0)
	(lifting hoist0 crate11)
	(at crate4 depot0)
	(on crate4 crate3)
	(clear crate4)
	(available hoist0)
	(clear crate8)
	(lifting hoist1 crate14)
	(lifting hoist1 crate12)
	(clear crate9)
	(on crate9 crate5)
	(at crate9 distributor0)
	(available hoist1)
	(at truck0 distributor0)
	(clear pallet2)
	(lifting hoist2 crate12)
	(clear pallet0)
	(lifting hoist0 crate8)
	(in crate11 truck0)
	(available hoist2)
	(in crate10 truck1)
	(available hoist0)
	(at truck1 distributor0)
	(clear crate5)
	(lifting hoist2 crate11)
	(lifting hoist1 crate8)
	(clear crate13)
	(available hoist1)
	(on crate13 crate12)
	(at crate13 distributor0)
	(at crate0 depot0)
	(on crate0 pallet1)
	(clear crate0)
	(available hoist0)
	(available hoist1)
	(at crate0 distributor0)
	(on crate0 pallet1)
	(clear crate0)
	(lifting hoist0 crate4)
	(clear crate11)
	(in crate12 truck1)
	(available hoist2)
	(on crate11 crate6)
	(at crate11 depot0)
	(clear crate11)
	(available hoist0)
	(at truck1 distributor0)
	(at crate12 distributor0)
	(on crate12 crate9)
	(available hoist1)
	(clear crate12)
	(available hoist1)
	(at crate8 distributor0)
	(clear crate8)
	(on crate8 crate7)
	(clear crate0)
	(lifting hoist2 crate5)
	(on crate1 pallet0)
	(clear crate1)
	(at crate1 depot0)
	(available hoist0)
	(clear crate12)
	(lifting hoist1 crate3)
	(lifting hoist1 crate0)
	(clear crate8)
	(lifting hoist0 crate10)
	(clear crate4)
)
(:goal
	(on crate3 crate12)
	(on crate10 crate4)
	(on crate4 crate11)
	(on crate2 crate1)
	(on crate1 crate9)
	(on crate8 pallet0)
	(on crate0 crate8)
	(on crate9 pallet1)
	(on crate12 pallet2)
	(on crate5 crate0)
	(on crate11 crate5)
)
(:current
	(on crate2 crate1)
)
