3
(Drop hoist1 crate1 pallet1 distributor0)
(Unload hoist2 crate0 truck1 distributor1)
(Drop hoist2 crate0 pallet2 distributor1)
0
(:init
	(clear pallet2)
	(lifting hoist1 crate1)
	(at pallet1 distributor0)
	(at hoist0 depot0)
	(at hoist1 distributor0)
	(at hoist2 distributor1)
	(in crate0 truck1)
	(at pallet2 distributor1)
	(available hoist0)
	(available hoist2)
	(clear pallet1)
	(at truck0 distributor1)
	(at pallet0 depot0)
	(at truck1 distributor1)
	(clear pallet0)
)
(:add
	(lifting hoist2 crate0)
	(clear crate0)
	(on crate0 pallet2)
	(available hoist2)
	(at crate0 distributor1)
	(available hoist1)
	(at crate1 distributor0)
	(on crate1 pallet1)
	(clear crate1)
)
(:delete
	(in crate0 truck1)
	(available hoist2)
	(clear pallet2)
	(lifting hoist2 crate0)
	(lifting hoist1 crate1)
	(clear pallet1)
)
(:goal
	(on crate1 pallet1)
	(on crate0 pallet2)
)
(:current
)
