2
(Unload hoist0 crate2 truck0 depot0)
(Drop hoist0 crate2 crate0 depot0)
0
(:init
	(clear crate7)
	(at crate1 distributor0)
	(clear crate0)
	(at crate3 distributor1)
	(at pallet0 depot0)
	(on crate1 pallet1)
	(on crate0 pallet0)
	(at truck0 depot0)
	(on crate3 pallet1)
	(at crate4 depot0)
	(on crate0 pallet1)
	(at crate5 depot0)
	(available hoist1)
	(at hoist2 distributor1)
	(on crate8 crate3)
	(at crate0 depot0)
	(on crate2 pallet2)
	(on crate2 crate1)
	(at pallet1 distributor0)
	(on crate3 crate0)
	(at crate8 distributor1)
	(on crate7 crate1)
	(at pallet2 distributor1)
	(available hoist2)
	(at crate9 depot0)
	(on crate5 crate4)
	(at hoist0 depot0)
	(on crate4 crate6)
	(on crate6 crate9)
	(at crate3 distributor0)
	(on crate3 pallet2)
	(on crate0 crate5)
	(available hoist0)
	(at crate4 distributor0)
	(at truck1 distributor0)
	(in crate2 truck0)
	(at crate6 depot0)
	(at crate7 distributor0)
	(at crate1 distributor1)
	(at crate0 distributor0)
	(on crate1 pallet2)
	(clear crate8)
	(on crate9 pallet0)
	(at hoist1 distributor0)
)
(:add
	(on crate2 crate0)
	(at crate2 depot0)
	(clear crate2)
	(available hoist0)
	(lifting hoist0 crate2)
)
(:delete
	(lifting hoist0 crate2)
	(clear crate0)
	(in crate2 truck0)
	(available hoist0)
)
(:goal
	(on crate2 crate0)
	(on crate7 crate1)
	(on crate3 pallet2)
	(on crate0 crate5)
	(on crate4 crate6)
	(on crate1 pallet1)
	(on crate6 crate9)
	(on crate5 crate4)
	(on crate8 crate3)
	(on crate9 pallet0)
)
(:current
	(on crate1 pallet1)
	(on crate8 crate3)
	(on crate7 crate1)
	(on crate5 crate4)
	(on crate4 crate6)
	(on crate6 crate9)
	(on crate3 pallet2)
	(on crate0 crate5)
	(on crate9 pallet0)
)
