14
(Lift hoist1 crate0 pallet8 depot1)
(Lift hoist0 crate4 crate0 depot0)
(Lift hoist4 crate2 crate12 depot0)
(Unload hoist2 crate13 truck0 distributor1)
(Unload hoist0 crate14 truck0 depot0)
(Drop hoist7 crate9 crate1 distributor1)
(Drop hoist5 crate8 crate4 depot0)
(Unload hoist2 crate10 truck1 depot2)
(Drop hoist2 crate13 pallet3 distributor1)
(Drop hoist0 crate4 pallet4 depot0)
(Drop hoist0 crate14 pallet0 depot0)
(Drop hoist2 crate10 pallet1 distributor0)
(Lift hoist4 crate12 crate10 distributor0)
(Drop hoist1 crate0 crate10 depot1)
6
(:init
	(clear crate2)
	(on crate2 crate12)
	(on crate1 pallet6)
	(on crate6 crate1)
	(on crate2 pallet4)
	(on crate5 pallet2)
	(on crate8 pallet5)
	(at truck1 depot0)
	(available hoist1)
	(at hoist2 depot2)
	(at crate6 depot0)
	(on crate0 pallet3)
	(at pallet4 depot1)
	(available hoist2)
	(at hoist2 distributor0)
	(at crate3 depot0)
	(at crate13 distributor1)
	(at truck1 depot2)
	(on crate6 pallet7)
	(clear crate0)
	(on crate2 crate1)
	(at crate12 distributor1)
	(on crate4 pallet3)
	(on crate12 crate5)
	(on crate9 crate5)
	(clear crate1)
	(at hoist4 depot0)
	(on crate5 pallet3)
	(on crate2 pallet8)
	(at crate3 depot2)
	(on crate4 pallet2)
	(at truck1 distributor2)
	(at crate4 depot2)
	(on crate2 crate0)
	(on crate0 pallet4)
	(at truck3 distributor1)
	(on crate1 pallet0)
	(at crate8 distributor1)
	(at crate0 depot0)
	(at crate7 distributor1)
	(at pallet6 depot1)
	(on crate12 crate10)
	(at crate4 depot0)
	(lifting hoist3 crate3)
	(on crate4 pallet6)
	(on crate11 crate5)
	(on crate0 pallet2)
	(at truck0 distributor1)
	(on crate9 pallet7)
	(at crate0 depot2)
	(on crate0 pallet5)
	(on crate11 crate6)
	(at pallet0 depot0)
	(at crate8 distributor2)
	(available hoist0)
	(at hoist6 depot0)
	(on crate3 pallet1)
	(at hoist1 distributor0)
	(on crate1 pallet4)
	(on crate4 pallet1)
	(at crate7 depot0)
	(on crate13 crate9)
	(on crate3 crate2)
	(on crate0 pallet0)
	(at crate12 distributor0)
	(at crate2 depot0)
	(at crate7 distributor0)
	(on crate4 pallet0)
	(on crate14 crate9)
	(on crate7 crate6)
	(on crate3 crate1)
	(on crate5 pallet0)
	(on crate4 crate0)
	(on crate11 pallet4)
	(on crate3 crate0)
	(at pallet9 distributor0)
	(at pallet4 distributor1)
	(clear pallet9)
	(at pallet6 distributor1)
	(in crate14 truck0)
	(on crate11 pallet5)
	(at crate2 depot2)
	(on crate9 pallet2)
	(at crate7 distributor2)
	(at crate14 distributor1)
	(at crate10 depot1)
	(on crate0 pallet1)
	(at crate5 distributor1)
	(on crate4 crate2)
	(on crate1 crate0)
	(at crate8 depot0)
	(on crate9 crate8)
	(on crate6 pallet1)
	(at crate9 distributor0)
	(at crate7 depot1)
	(at crate8 depot1)
	(at truck2 depot1)
	(at hoist5 depot0)
	(at crate5 depot0)
	(at crate13 distributor0)
	(at pallet7 depot0)
	(on crate9 crate7)
	(on crate0 pallet8)
	(on crate1 pallet2)
	(at pallet6 distributor2)
	(at crate11 depot0)
	(at crate9 distributor2)
	(on crate1 pallet5)
	(on crate7 crate5)
	(at crate12 depot1)
	(at crate5 depot2)
	(at truck3 depot1)
	(on crate7 crate4)
	(in crate13 truck0)
	(at crate13 distributor2)
	(at pallet8 distributor1)
	(at crate3 distributor2)
	(at pallet7 distributor0)
	(at hoist1 depot1)
	(at hoist4 distributor0)
	(at crate0 distributor0)
	(at crate1 distributor1)
	(at crate0 distributor2)
	(at pallet5 distributor0)
	(on crate10 crate5)
	(at pallet2 distributor0)
	(at crate6 distributor2)
	(at crate1 depot2)
	(clear crate7)
	(at crate4 distributor0)
	(at crate3 distributor0)
	(at crate6 distributor1)
	(available hoist4)
	(at hoist3 distributor0)
	(on crate8 pallet1)
	(at crate13 depot2)
	(at crate1 depot0)
	(at hoist0 depot0)
	(at pallet4 depot0)
	(on crate2 pallet0)
	(on crate14 pallet9)
	(at pallet1 depot1)
	(at pallet2 distributor1)
	(at crate11 distributor2)
	(at pallet5 distributor1)
	(at truck0 depot2)
	(at crate0 depot1)
	(clear pallet1)
	(at crate2 distributor0)
	(lifting hoist5 crate8)
	(at pallet3 distributor1)
	(at pallet1 distributor0)
	(at hoist6 depot1)
	(at crate5 distributor2)
	(on crate5 crate0)
	(at hoist5 distributor2)
	(available hoist6)
	(on crate13 crate4)
	(at crate11 distributor0)
	(at truck0 depot0)
	(on crate5 crate1)
	(at pallet4 distributor0)
	(lifting hoist7 crate9)
	(on crate8 crate7)
	(clear pallet0)
	(on crate13 crate3)
	(at pallet5 distributor2)
	(at crate5 distributor0)
	(on crate6 pallet4)
	(on crate5 crate2)
	(at truck3 depot0)
	(at pallet5 depot0)
	(at crate6 depot1)
	(at crate9 depot2)
	(on crate8 pallet3)
	(on crate13 crate12)
	(at pallet2 depot2)
	(at pallet3 distributor0)
	(clear crate4)
	(on crate1 pallet9)
	(at crate2 distributor1)
	(at crate11 distributor1)
	(on crate3 pallet8)
	(at crate3 depot1)
	(clear crate6)
	(at crate4 depot1)
	(on crate2 pallet3)
	(at hoist7 distributor1)
	(at pallet7 depot1)
	(on crate14 crate11)
	(on crate4 crate3)
	(in crate10 truck1)
	(at pallet9 depot0)
	(clear pallet4)
	(at crate0 distributor1)
	(at hoist2 distributor1)
	(at hoist4 distributor1)
	(at hoist6 distributor0)
	(on crate5 crate4)
	(on crate14 crate13)
	(at pallet7 distributor1)
	(at pallet8 depot2)
	(on crate12 crate11)
	(on crate10 crate1)
	(on crate9 crate2)
	(clear pallet3)
	(at pallet8 depot0)
	(at pallet6 depot0)
	(on crate6 crate3)
	(clear crate11)
	(at hoist3 distributor1)
	(at hoist5 depot1)
	(on crate12 crate9)
	(at crate4 distributor1)
)
(:add
	(available hoist2)
	(on crate10 pallet1)
	(clear crate10)
	(at crate10 distributor0)
	(lifting hoist2 crate13)
	(lifting hoist0 crate14)
	(lifting hoist2 crate10)
	(lifting hoist4 crate12)
	(clear crate10)
	(available hoist2)
	(at crate13 distributor1)
	(clear crate13)
	(on crate13 pallet3)
	(on crate9 crate1)
	(clear crate9)
	(at crate9 distributor1)
	(available hoist7)
	(on crate14 pallet0)
	(available hoist0)
	(at crate14 depot0)
	(clear crate14)
	(at crate8 depot0)
	(available hoist5)
	(on crate8 crate4)
	(clear crate8)
	(at crate0 depot1)
	(clear crate0)
	(available hoist1)
	(on crate0 crate10)
	(clear crate4)
	(available hoist0)
	(at crate4 depot0)
	(on crate4 pallet4)
	(lifting hoist1 crate0)
	(clear pallet8)
	(lifting hoist4 crate2)
	(clear crate12)
	(lifting hoist0 crate4)
	(clear crate0)
)
(:delete
	(clear pallet1)
	(lifting hoist2 crate10)
	(available hoist2)
	(in crate13 truck0)
	(available hoist0)
	(in crate14 truck0)
	(available hoist2)
	(in crate10 truck1)
	(at crate12 distributor0)
	(on crate12 crate10)
	(clear crate12)
	(available hoist4)
	(clear pallet3)
	(lifting hoist2 crate13)
	(lifting hoist7 crate9)
	(clear crate1)
	(clear pallet0)
	(lifting hoist0 crate14)
	(lifting hoist5 crate8)
	(clear crate4)
	(lifting hoist1 crate0)
	(clear crate10)
	(lifting hoist0 crate4)
	(clear pallet4)
	(on crate0 pallet8)
	(at crate0 depot1)
	(clear crate0)
	(available hoist1)
	(clear crate2)
	(at crate2 depot0)
	(on crate2 crate12)
	(available hoist4)
	(clear crate4)
	(available hoist0)
	(on crate4 crate0)
	(at crate4 depot0)
)
(:goal
	(on crate6 pallet7)
	(on crate11 pallet5)
	(on crate2 crate12)
	(on crate1 pallet6)
	(on crate9 crate1)
	(on crate14 pallet0)
	(on crate5 pallet2)
	(on crate8 crate4)
	(on crate10 pallet1)
	(on crate12 crate5)
	(on crate13 pallet3)
	(on crate4 pallet4)
	(on crate0 crate10)
)
(:current
	(on crate2 crate12)
	(on crate1 pallet6)
	(on crate5 pallet2)
	(on crate6 pallet7)
	(on crate12 crate5)
	(on crate11 pallet5)
)
