9
(Unload hoist2 crate14 truck3 distributor0)
(Unload hoist4 crate12 truck3 distributor0)
(Lift hoist1 crate5 pallet3 depot1)
(Lift hoist4 crate7 crate6 depot0)
(Unload hoist3 crate4 truck3 distributor0)
(Drop hoist3 crate4 crate5 distributor1)
(Drop hoist4 crate12 crate6 depot0)
(Drop hoist2 crate14 pallet1 distributor0)
(Drop hoist1 crate5 crate14 distributor0)
6
(:init
	(at crate5 depot0)
	(at crate13 distributor0)
	(on crate0 pallet3)
	(in crate4 truck3)
	(at crate8 depot1)
	(at hoist5 depot0)
	(at pallet8 distributor2)
	(on crate2 pallet4)
	(on crate8 pallet5)
	(at truck1 depot1)
	(at crate13 distributor2)
	(on crate5 pallet3)
	(at crate5 depot2)
	(clear pallet4)
	(on crate3 pallet6)
	(on crate2 pallet2)
	(on crate2 crate1)
	(at pallet6 distributor2)
	(at crate7 depot3)
	(on crate12 crate10)
	(at crate2 depot0)
	(at crate7 distributor0)
	(at crate7 depot0)
	(on crate0 pallet4)
	(on crate2 crate0)
	(at hoist1 distributor0)
	(at crate14 distributor1)
	(on crate0 pallet5)
	(on crate11 crate6)
	(at crate5 distributor1)
	(at pallet6 distributor1)
	(at hoist5 distributor1)
	(at crate2 depot2)
	(at crate7 depot2)
	(at pallet4 distributor1)
	(on crate11 crate5)
	(at crate1 depot1)
	(on crate0 pallet2)
	(on crate3 crate1)
	(on crate3 pallet1)
	(at truck0 depot1)
	(at crate0 depot0)
	(at crate7 distributor1)
	(on crate3 crate2)
	(on crate0 pallet0)
	(on crate11 pallet5)
	(on crate0 pallet1)
	(on crate5 pallet0)
	(at crate0 depot2)
	(on crate11 pallet4)
	(on crate3 crate0)
	(at truck0 distributor1)
	(at pallet4 depot1)
	(clear crate13)
	(at truck1 distributor0)
	(at hoist2 distributor0)
	(at truck3 distributor0)
	(on crate8 crate6)
	(clear pallet1)
	(at truck1 depot0)
	(at crate3 depot3)
	(on crate10 crate9)
	(at hoist3 depot3)
	(at crate14 distributor0)
	(in crate12 truck3)
	(clear pallet0)
	(at crate3 depot2)
	(at crate0 depot3)
	(at truck1 distributor2)
	(at truck1 depot2)
	(on crate5 pallet7)
	(at crate13 distributor1)
	(on crate10 crate5)
	(at pallet7 distributor1)
	(at pallet8 depot2)
	(at hoist2 distributor1)
	(at crate0 distributor1)
	(at truck2 depot2)
	(at hoist5 depot1)
	(at crate3 distributor1)
	(on crate14 pallet9)
	(at pallet8 depot0)
	(at pallet6 depot0)
	(at crate5 depot1)
	(at hoist3 distributor1)
	(available hoist7)
	(at truck2 depot0)
	(at crate2 distributor1)
	(at pallet2 depot2)
	(on crate5 pallet8)
	(at pallet3 distributor0)
	(at pallet7 distributor3)
	(on crate6 pallet4)
	(at crate2 distributor2)
	(on crate6 pallet5)
	(at crate3 depot1)
	(at truck0 distributor0)
	(at hoist5 distributor2)
	(on crate1 pallet9)
	(at crate5 distributor2)
	(on crate3 pallet8)
	(at pallet3 distributor1)
	(at pallet5 distributor1)
	(at crate0 depot1)
	(at truck0 depot2)
	(on crate1 pallet1)
	(at crate2 distributor0)
	(clear crate1)
	(at crate9 depot2)
	(at pallet5 distributor2)
	(in crate14 truck3)
	(at truck2 distributor1)
	(at truck0 depot0)
	(at pallet4 distributor0)
	(at crate9 distributor3)
	(on crate5 crate4)
	(at crate0 distributor2)
	(at pallet5 distributor0)
	(at hoist1 depot1)
	(at crate0 distributor0)
	(at crate3 distributor2)
	(at pallet7 distributor0)
	(at pallet4 depot0)
	(at hoist3 distributor0)
	(on crate12 crate11)
	(on crate5 crate3)
	(on crate9 crate2)
	(at crate3 distributor0)
	(on crate13 crate2)
	(at pallet7 depot0)
	(available hoist3)
	(at crate7 depot1)
	(at crate8 depot0)
	(at crate9 distributor0)
	(available hoist4)
	(on crate6 crate1)
	(clear crate5)
	(at pallet8 depot1)
	(on crate9 crate5)
	(on crate2 pallet8)
	(on crate4 pallet2)
	(at crate11 depot0)
	(on crate6 pallet7)
	(at crate9 distributor2)
	(on crate4 pallet3)
	(at crate8 distributor0)
	(at crate12 distributor0)
	(on crate1 pallet0)
	(on crate7 pallet2)
	(available hoist6)
	(on crate11 crate1)
	(clear crate9)
	(at crate10 depot1)
	(available hoist5)
	(on crate7 pallet3)
	(at pallet9 distributor0)
	(on crate4 pallet6)
	(on crate9 pallet7)
	(clear crate3)
	(at pallet3 depot3)
	(on crate4 pallet0)
	(at pallet6 depot1)
	(on crate14 crate9)
	(on crate7 crate6)
	(at crate8 distributor1)
	(on crate4 pallet1)
	(on crate1 pallet4)
	(on crate13 crate9)
	(on crate9 pallet2)
	(at hoist6 depot0)
	(at pallet0 depot0)
	(clear crate7)
	(on crate13 crate7)
	(on crate4 crate0)
	(on crate9 pallet3)
	(at crate10 distributor1)
	(on crate0 pallet9)
	(at hoist2 depot2)
	(at crate6 depot0)
	(on crate6 pallet0)
	(on crate9 crate7)
	(on crate1 crate0)
	(on crate4 crate2)
	(on crate9 crate8)
	(on crate7 crate5)
	(at crate4 depot2)
	(on crate7 crate4)
	(at hoist4 depot0)
	(on crate0 pallet8)
	(at crate12 distributor1)
	(on crate1 pallet2)
	(at crate8 distributor3)
	(at hoist4 distributor1)
	(at hoist6 distributor0)
	(at crate4 distributor2)
	(clear pallet9)
	(at crate6 distributor0)
	(at crate4 distributor1)
	(available hoist2)
	(on crate12 crate2)
	(on crate2 pallet0)
	(at truck1 distributor1)
	(at hoist6 distributor2)
	(available hoist1)
	(on crate8 pallet1)
	(available hoist0)
	(at crate11 distributor1)
	(on crate5 crate0)
	(on crate1 crate11)
	(at hoist7 distributor3)
	(on crate13 crate3)
	(at pallet9 depot0)
	(at pallet7 depot1)
	(at hoist7 distributor1)
	(on crate5 crate1)
	(at pallet9 depot3)
	(at crate4 depot1)
	(at pallet9 depot2)
	(on crate4 pallet8)
	(at hoist6 depot1)
	(on crate8 pallet3)
	(on crate13 crate12)
	(at pallet1 distributor0)
	(at pallet2 distributor1)
	(at crate11 distributor2)
	(at pallet5 depot0)
	(on crate14 crate11)
	(at crate11 distributor0)
	(in crate6 truck3)
	(on crate8 pallet7)
	(at crate1 distributor1)
	(on crate14 crate13)
	(at crate6 distributor2)
	(at pallet2 distributor0)
	(at crate1 depot2)
	(at hoist4 distributor0)
	(at pallet8 distributor1)
	(on crate3 pallet5)
	(in crate10 truck3)
	(on crate6 crate3)
	(at pallet1 depot1)
	(on crate12 crate9)
	(at crate1 depot0)
	(at hoist0 depot0)
	(at crate13 depot2)
	(on crate10 crate1)
	(on crate2 pallet6)
	(at crate4 distributor0)
	(at crate6 distributor1)
)
(:add
	(at crate14 distributor0)
	(clear crate14)
	(available hoist2)
	(on crate14 pallet1)
	(available hoist4)
	(on crate12 crate6)
	(clear crate12)
	(at crate12 depot0)
	(on crate5 crate14)
	(available hoist1)
	(clear crate5)
	(at crate5 distributor0)
	(lifting hoist2 crate14)
	(on crate4 crate5)
	(clear crate4)
	(available hoist3)
	(at crate4 distributor1)
	(lifting hoist3 crate4)
	(lifting hoist4 crate12)
	(lifting hoist4 crate7)
	(clear crate6)
	(clear pallet3)
	(lifting hoist1 crate5)
)
(:delete
	(clear pallet1)
	(lifting hoist2 crate14)
	(lifting hoist4 crate12)
	(clear crate6)
	(lifting hoist1 crate5)
	(clear crate14)
	(in crate14 truck3)
	(available hoist2)
	(clear crate5)
	(lifting hoist3 crate4)
	(available hoist3)
	(in crate4 truck3)
	(available hoist4)
	(in crate12 truck3)
	(clear crate7)
	(available hoist4)
	(at crate7 depot0)
	(on crate7 crate6)
	(on crate5 pallet3)
	(available hoist1)
	(clear crate5)
	(at crate5 depot1)
)
(:goal
	(on crate4 crate5)
	(on crate5 crate14)
	(on crate7 pallet2)
	(on crate1 crate11)
	(on crate12 crate6)
	(on crate0 pallet3)
	(on crate11 pallet5)
	(on crate2 pallet6)
	(on crate6 pallet4)
	(on crate8 pallet7)
	(on crate3 crate0)
	(on crate9 crate8)
	(on crate14 pallet1)
	(on crate13 crate2)
)
(:current
	(on crate0 pallet3)
	(on crate11 pallet5)
	(on crate3 crate0)
	(on crate6 pallet4)
	(on crate13 crate2)
	(on crate7 pallet2)
	(on crate9 crate8)
	(on crate1 crate11)
	(on crate8 pallet7)
	(on crate2 pallet6)
)
