21
(Drop hoist1 crate14 crate10 depot1)
(Lift hoist3 crate12 crate10 distributor0)
(Lift hoist3 crate13 crate9 distributor0)
(Drop hoist1 crate14 crate5 depot1)
(Lift hoist3 crate8 pallet5 distributor0)
(Lift hoist2 crate10 crate5 distributor1)
(Lift hoist4 crate3 crate2 distributor1)
(Lift hoist3 crate12 crate11 distributor0)
(Lift hoist2 crate9 crate5 depot2)
(Drop hoist4 crate3 crate9 distributor1)
(Drop hoist2 crate9 pallet2 distributor1)
(Drop hoist3 crate13 pallet1 distributor0)
(Load hoist3 crate12 truck1 distributor0)
(Drop hoist2 crate10 crate13 distributor1)
(Lift hoist0 crate11 crate6 depot0)
(Lift hoist1 crate1 pallet5 depot1)
(Lift hoist1 crate6 pallet1 distributor0)
(Drop hoist1 crate1 crate12 depot1)
(Unload hoist0 crate12 truck1 depot0)
(Drop hoist1 crate6 crate2 distributor0)
(Drop hoist0 crate12 pallet5 depot0)
63
(:init
	(on crate5 pallet0)
	(on crate4 crate0)
	(at hoist3 distributor0)
	(on crate2 pallet3)
	(available hoist3)
	(on crate3 crate0)
	(at crate3 distributor0)
	(at crate13 distributor1)
	(clear crate8)
	(at crate4 depot2)
	(at pallet1 depot1)
	(available hoist4)
	(on crate4 crate3)
	(at hoist0 depot0)
	(on crate0 pallet1)
	(at crate1 depot0)
	(on crate3 pallet1)
	(at crate0 distributor0)
	(clear crate9)
	(at truck1 depot0)
	(available hoist2)
	(on crate13 crate12)
	(at hoist1 depot1)
	(on crate13 crate9)
	(at crate3 distributor2)
	(on crate3 crate2)
	(at crate9 distributor1)
	(on crate0 pallet0)
	(at crate14 distributor0)
	(on crate1 pallet1)
	(at crate3 depot0)
	(at truck1 distributor0)
	(clear pallet3)
	(at crate6 distributor2)
	(on crate14 crate9)
	(at crate6 depot0)
	(on crate3 crate1)
	(on crate7 crate6)
	(at hoist2 depot2)
	(at crate0 distributor2)
	(clear crate3)
	(at crate1 distributor1)
	(on crate1 pallet2)
	(on crate12 crate11)
	(in crate4 truck1)
	(available hoist0)
	(at pallet4 distributor0)
	(at truck0 distributor1)
	(at truck0 depot0)
	(in crate11 truck0)
	(at crate11 distributor0)
	(at crate10 distributor1)
	(clear pallet2)
	(at crate9 depot2)
	(on crate6 crate3)
	(on crate1 pallet5)
	(at pallet5 depot0)
	(at crate8 distributor2)
	(on crate12 crate9)
	(at pallet0 depot0)
	(at pallet5 distributor2)
	(on crate7 crate4)
	(clear crate5)
	(clear crate12)
	(at pallet1 distributor0)
	(at crate0 depot0)
	(at pallet3 distributor1)
	(at crate2 distributor0)
	(at crate0 depot1)
	(on crate9 crate8)
	(available hoist5)
	(at truck0 depot2)
	(clear pallet4)
	(at pallet5 distributor1)
	(at pallet2 distributor1)
	(on crate6 pallet1)
	(at hoist5 distributor2)
	(at crate4 depot0)
	(on crate5 crate4)
	(on crate14 crate13)
	(clear crate10)
	(on crate9 crate7)
	(at pallet4 distributor1)
	(at crate1 depot1)
	(clear crate13)
	(on crate2 pallet2)
	(at truck0 distributor0)
	(on crate2 crate1)
	(at crate3 depot1)
	(at crate5 distributor1)
	(at crate10 depot1)
	(clear pallet1)
	(on crate9 crate5)
	(on crate5 pallet3)
	(at crate7 distributor2)
	(at crate2 depot2)
	(lifting hoist1 crate14)
	(clear pallet0)
	(on crate6 crate1)
	(at hoist1 distributor0)
	(on crate8 pallet5)
	(on crate10 crate5)
	(at crate2 distributor1)
	(at crate7 distributor0)
	(at crate2 depot0)
	(at pallet3 distributor0)
	(at crate12 distributor0)
	(at crate8 distributor0)
	(at pallet2 depot2)
	(at crate9 distributor2)
	(on crate13 crate4)
	(at crate11 depot0)
	(on crate5 crate1)
	(on crate0 pallet2)
	(on crate6 pallet5)
	(on crate8 crate7)
	(at crate13 distributor2)
	(on crate0 pallet5)
	(on crate11 crate6)
	(at crate4 distributor1)
	(at crate3 distributor1)
	(at crate6 distributor0)
	(clear crate2)
	(at crate5 depot2)
	(on crate5 crate2)
	(at crate5 depot1)
	(at crate12 depot1)
	(at crate9 distributor0)
	(on crate2 crate0)
	(clear crate1)
	(at crate0 distributor1)
	(on crate0 pallet4)
	(at crate8 depot0)
	(on crate1 pallet0)
	(at crate13 distributor0)
	(on crate12 crate10)
	(clear crate0)
	(at crate5 depot0)
	(at hoist4 distributor1)
	(at hoist2 distributor1)
)
(:add
	(available hoist1)
	(at crate14 depot1)
	(on crate14 crate5)
	(clear crate14)
	(clear crate9)
	(lifting hoist3 crate13)
	(clear crate9)
	(at crate9 distributor1)
	(available hoist2)
	(on crate9 pallet2)
	(available hoist3)
	(in crate12 truck1)
	(lifting hoist1 crate1)
	(clear pallet5)
	(available hoist1)
	(at crate1 depot1)
	(clear crate1)
	(on crate1 crate12)
	(lifting hoist0 crate12)
	(lifting hoist4 crate3)
	(clear crate2)
	(clear pallet5)
	(lifting hoist3 crate8)
	(available hoist3)
	(on crate13 pallet1)
	(clear crate13)
	(at crate13 distributor0)
	(at crate12 depot0)
	(available hoist0)
	(clear crate12)
	(on crate12 pallet5)
	(lifting hoist1 crate6)
	(clear pallet1)
	(clear crate10)
	(lifting hoist3 crate12)
	(on crate14 crate10)
	(available hoist1)
	(at crate14 depot1)
	(clear crate14)
	(lifting hoist0 crate11)
	(clear crate6)
	(available hoist1)
	(at crate6 distributor0)
	(on crate6 crate2)
	(clear crate6)
	(available hoist4)
	(on crate3 crate9)
	(at crate3 distributor1)
	(clear crate3)
	(clear crate5)
	(lifting hoist2 crate9)
	(clear crate11)
	(lifting hoist3 crate12)
	(clear crate10)
	(available hoist2)
	(at crate10 distributor1)
	(on crate10 crate13)
	(clear crate5)
	(lifting hoist2 crate10)
)
(:delete
	(clear crate5)
	(lifting hoist1 crate14)
	(on crate13 crate9)
	(available hoist3)
	(clear crate13)
	(at crate13 distributor0)
	(lifting hoist2 crate9)
	(clear pallet2)
	(lifting hoist3 crate12)
	(available hoist1)
	(at crate1 depot1)
	(clear crate1)
	(on crate1 pallet5)
	(lifting hoist1 crate1)
	(clear crate12)
	(available hoist0)
	(in crate12 truck1)
	(available hoist4)
	(on crate3 crate2)
	(at crate3 distributor1)
	(clear crate3)
	(available hoist3)
	(on crate8 pallet5)
	(at crate8 distributor0)
	(clear crate8)
	(clear pallet1)
	(lifting hoist3 crate13)
	(lifting hoist0 crate12)
	(clear pallet5)
	(available hoist1)
	(at crate6 distributor0)
	(clear crate6)
	(on crate6 pallet1)
	(available hoist3)
	(at crate12 distributor0)
	(on crate12 crate10)
	(clear crate12)
	(clear crate10)
	(lifting hoist1 crate14)
	(on crate11 crate6)
	(at crate11 depot0)
	(clear crate11)
	(available hoist0)
	(lifting hoist1 crate6)
	(clear crate2)
	(clear crate9)
	(lifting hoist4 crate3)
	(at crate9 depot2)
	(clear crate9)
	(on crate9 crate5)
	(available hoist2)
	(available hoist3)
	(on crate12 crate11)
	(at crate12 distributor0)
	(clear crate12)
	(lifting hoist2 crate10)
	(clear crate13)
	(on crate10 crate5)
	(available hoist2)
	(clear crate10)
	(at crate10 distributor1)
)
(:goal
	(on crate5 pallet0)
	(on crate14 crate10)
	(on crate13 pallet1)
	(on crate0 pallet4)
	(on crate1 crate12)
	(on crate2 crate0)
	(on crate3 crate9)
	(on crate6 crate2)
	(on crate9 pallet2)
	(on crate10 crate13)
	(on crate12 pallet5)
)
(:current
	(on crate5 pallet0)
	(on crate2 crate0)
	(on crate0 pallet4)
)
