11
(Lift hoist1 crate0 pallet4 distributor0)
(Lift hoist0 crate4 crate3 depot0)
(Drop hoist2 crate3 crate0 distributor1)
(Lift hoist0 crate5 pallet0 depot0)
(Lift hoist0 crate1 pallet5 depot0)
(Load hoist0 crate4 truck0 depot0)
(Drop hoist0 crate1 crate4 depot0)
(Drop hoist1 crate0 pallet3 distributor0)
(Drop hoist0 crate5 crate1 depot0)
(Unload hoist2 crate4 truck0 distributor1)
(Drop hoist2 crate4 pallet5 distributor1)
14
(:init
	(at crate5 distributor1)
	(on crate4 crate0)
	(on crate5 pallet0)
	(clear pallet3)
	(at crate1 depot0)
	(on crate2 pallet2)
	(at hoist0 depot0)
	(on crate3 crate0)
	(on crate2 crate1)
	(clear crate14)
	(on crate9 crate5)
	(lifting hoist2 crate3)
	(at crate3 distributor0)
	(on crate0 pallet1)
	(clear crate11)
	(on crate4 crate3)
	(clear crate9)
	(at crate4 distributor0)
	(at truck1 distributor0)
	(on crate13 crate12)
	(at crate3 depot0)
	(on crate3 pallet1)
	(at crate2 distributor1)
	(at crate12 distributor0)
	(at crate6 depot0)
	(at pallet3 distributor0)
	(on crate0 pallet0)
	(at crate7 distributor0)
	(clear pallet1)
	(at crate8 distributor0)
	(at crate1 distributor1)
	(on crate6 crate1)
	(clear crate8)
	(at crate0 distributor0)
	(on crate10 crate5)
	(at crate9 distributor1)
	(on crate3 crate1)
	(on crate7 crate6)
	(available hoist0)
	(at crate14 distributor0)
	(at hoist1 distributor0)
	(on crate0 pallet2)
	(clear crate10)
	(on crate1 pallet2)
	(at crate6 distributor0)
	(on crate8 crate7)
	(at truck1 distributor1)
	(clear crate0)
	(at pallet0 depot0)
	(available hoist1)
	(on crate11 crate6)
	(on crate1 pallet5)
	(at crate11 depot0)
	(at truck0 depot0)
	(at truck0 distributor1)
	(at pallet4 distributor0)
	(clear crate1)
	(on crate7 crate4)
	(at crate10 distributor1)
	(on crate5 crate2)
	(on crate12 crate9)
	(at crate4 depot0)
	(on crate2 crate0)
	(on crate0 pallet4)
	(clear crate5)
	(at crate5 depot0)
	(at crate13 distributor0)
	(on crate6 pallet1)
	(on crate9 crate8)
	(clear crate2)
	(at hoist2 distributor1)
	(on crate1 pallet0)
	(at crate0 distributor1)
	(at crate0 depot0)
	(clear pallet2)
	(at pallet1 distributor0)
	(at crate9 distributor0)
	(clear crate4)
	(at pallet5 distributor1)
	(on crate14 crate13)
	(at pallet2 distributor1)
)
(:add
	(clear crate3)
	(available hoist2)
	(at crate3 distributor1)
	(on crate3 crate0)
	(clear crate3)
	(lifting hoist0 crate4)
	(lifting hoist2 crate4)
	(at crate0 distributor0)
	(on crate0 pallet3)
	(clear crate0)
	(available hoist1)
	(clear pallet4)
	(lifting hoist1 crate0)
	(lifting hoist0 crate1)
	(clear pallet5)
	(on crate4 pallet5)
	(at crate4 distributor1)
	(available hoist2)
	(clear crate4)
	(available hoist0)
	(in crate4 truck0)
	(on crate5 crate1)
	(available hoist0)
	(clear crate5)
	(at crate5 depot0)
	(available hoist0)
	(clear crate1)
	(at crate1 depot0)
	(on crate1 crate4)
	(lifting hoist0 crate5)
	(clear pallet0)
)
(:delete
	(clear crate0)
	(lifting hoist2 crate3)
	(at crate4 depot0)
	(available hoist0)
	(on crate4 crate3)
	(clear crate4)
	(available hoist2)
	(in crate4 truck0)
	(lifting hoist1 crate0)
	(clear pallet3)
	(at crate0 distributor0)
	(clear crate0)
	(on crate0 pallet4)
	(available hoist1)
	(available hoist0)
	(clear crate1)
	(at crate1 depot0)
	(on crate1 pallet5)
	(clear pallet5)
	(lifting hoist2 crate4)
	(lifting hoist0 crate4)
	(clear crate1)
	(lifting hoist0 crate5)
	(lifting hoist0 crate1)
	(clear crate4)
	(available hoist0)
	(at crate5 depot0)
	(clear crate5)
	(on crate5 pallet0)
)
(:goal
	(on crate4 pallet5)
	(on crate5 crate1)
	(on crate0 pallet3)
	(on crate1 crate4)
	(on crate3 pallet1)
)
(:current
	(on crate3 pallet1)
)
