1
(Drop hoist4 crate1 pallet8 distributor1)
17
(:init
	(at pallet9 depot0)
	(at pallet7 depot1)
	(on crate2 pallet0)
	(at crate3 depot1)
	(at truck0 distributor0)
	(clear pallet8)
	(at crate2 distributor1)
	(at crate11 distributor1)
	(available hoist0)
	(at pallet2 depot2)
	(clear pallet9)
	(at pallet3 distributor0)
	(on crate10 crate5)
	(at crate3 distributor1)
	(at crate6 distributor0)
	(on crate13 crate4)
	(at crate4 distributor1)
	(on crate6 pallet5)
	(available hoist2)
	(at pallet8 depot0)
	(at truck1 distributor1)
	(on crate8 crate7)
	(at crate5 depot1)
	(available hoist1)
	(on crate6 pallet4)
	(on crate5 crate2)
	(in crate9 truck1)
	(at hoist2 distributor1)
	(at hoist4 distributor1)
	(at pallet1 depot1)
	(on crate2 pallet3)
	(at hoist0 depot0)
	(at hoist3 distributor0)
	(clear crate2)
	(on crate4 crate3)
	(on crate14 crate11)
	(at crate4 distributor0)
	(at crate3 distributor0)
	(at crate6 distributor1)
	(on crate13 crate12)
	(at crate0 distributor2)
	(at crate1 distributor1)
	(at crate6 distributor2)
	(on crate1 pallet1)
	(at crate1 depot2)
	(at hoist1 depot1)
	(at crate0 distributor0)
	(at pallet8 distributor1)
	(on crate3 pallet8)
	(at crate9 distributor1)
	(at crate3 distributor2)
	(on crate12 crate11)
	(at pallet5 depot0)
	(at crate9 depot2)
	(at pallet5 distributor2)
	(on crate6 crate3)
	(at crate11 distributor0)
	(on crate12 crate9)
	(at truck0 depot0)
	(at pallet4 distributor0)
	(clear crate14)
	(at hoist5 distributor2)
	(at crate5 distributor2)
	(at pallet3 distributor1)
	(on crate5 crate4)
	(at pallet1 distributor0)
	(at pallet5 distributor1)
	(on crate14 crate13)
	(at pallet2 distributor1)
	(at crate0 depot1)
	(at truck0 depot2)
	(on crate8 pallet7)
	(at crate2 distributor0)
	(at crate14 distributor1)
	(clear pallet2)
	(clear crate4)
	(on crate3 pallet6)
	(at crate5 distributor1)
	(at crate10 depot1)
	(at pallet6 distributor1)
	(on crate2 pallet2)
	(on crate2 crate1)
	(at crate7 distributor2)
	(at crate2 depot2)
	(on crate4 pallet3)
	(available hoist5)
	(on crate9 crate5)
	(at pallet9 distributor0)
	(clear crate12)
	(at pallet4 distributor1)
	(clear crate5)
	(at crate1 depot1)
	(on crate5 pallet3)
	(clear pallet4)
	(at crate8 distributor0)
	(on crate6 crate1)
	(at crate2 depot0)
	(at crate12 distributor0)
	(at crate7 distributor0)
	(on crate8 pallet5)
	(clear crate10)
	(on crate5 pallet5)
	(at hoist1 distributor0)
	(at truck1 depot1)
	(clear crate8)
	(on crate0 pallet2)
	(at crate13 distributor2)
	(at crate12 depot1)
	(at crate5 depot2)
	(on crate11 crate6)
	(at crate11 depot0)
	(on crate0 pallet5)
	(at crate9 distributor2)
	(at pallet6 distributor2)
	(on crate0 pallet4)
	(on crate2 crate0)
	(at crate13 distributor0)
	(at pallet7 depot0)
	(clear crate11)
	(on crate1 pallet0)
	(available hoist3)
	(at crate8 depot1)
	(at crate8 depot0)
	(clear crate3)
	(clear pallet3)
	(on crate12 crate10)
	(on crate4 crate0)
	(on crate5 pallet0)
	(on crate11 pallet4)
	(at crate4 depot2)
	(on crate3 crate0)
	(at crate13 distributor1)
	(on crate0 pallet1)
	(on crate3 pallet1)
	(at crate3 depot0)
	(on crate3 crate2)
	(on crate13 crate9)
	(at hoist2 depot2)
	(at crate6 depot0)
	(on crate0 pallet0)
	(clear pallet6)
	(on crate4 pallet0)
	(at crate14 distributor0)
	(on crate14 crate9)
	(clear crate7)
	(on crate3 crate1)
	(on crate7 crate6)
	(at crate8 distributor2)
	(on crate1 pallet2)
	(clear crate13)
	(at pallet0 depot0)
	(in crate0 truck1)
	(on crate1 pallet5)
	(at crate0 depot2)
	(on crate7 crate4)
	(at crate10 distributor1)
	(at truck0 distributor1)
	(clear pallet1)
	(at crate4 depot0)
	(on crate1 crate0)
	(lifting hoist4 crate1)
	(on crate4 crate2)
	(clear pallet0)
	(on crate6 pallet1)
	(on crate9 crate8)
	(at truck0 depot1)
	(at crate7 distributor1)
	(at crate0 depot0)
	(on crate9 crate7)
)
(:add
	(on crate1 pallet8)
	(at crate1 distributor1)
	(available hoist4)
	(clear crate1)
)
(:delete
	(lifting hoist4 crate1)
	(clear pallet8)
)
(:goal
	(on crate5 pallet5)
	(on crate1 pallet8)
	(on crate2 pallet3)
	(on crate9 crate7)
	(on crate4 pallet0)
	(on crate6 pallet1)
	(on crate7 crate6)
)
(:current
	(on crate2 pallet3)
	(on crate5 pallet5)
	(on crate4 pallet0)
	(on crate7 crate6)
	(on crate6 pallet1)
	(on crate9 crate7)
)
