8
(Lift hoist3 crate2 pallet8 distributor1)
(Lift hoist0 crate3 crate2 depot0)
(Unload hoist1 crate0 truck0 distributor0)
(Lift hoist1 crate5 crate1 depot1)
(Drop hoist1 crate0 pallet3 distributor0)
(Drop hoist1 crate5 pallet2 distributor0)
(Drop hoist3 crate2 pallet1 distributor0)
(Drop hoist0 crate3 pallet0 depot0)
15
(:init
	(at pallet7 depot1)
	(on crate0 pallet1)
	(at pallet9 depot0)
	(available hoist3)
	(at crate4 depot1)
	(at truck0 distributor0)
	(on crate3 crate0)
	(at crate3 depot1)
	(on crate4 crate0)
	(on crate5 pallet0)
	(on crate11 pallet4)
	(available hoist4)
	(at hoist7 distributor1)
	(on crate14 crate9)
	(at pallet3 distributor0)
	(at pallet2 depot2)
	(on crate3 crate1)
	(on crate7 crate6)
	(at crate11 distributor1)
	(on crate4 pallet0)
	(at crate2 distributor1)
	(on crate3 crate2)
	(on crate13 crate9)
	(on crate0 pallet0)
	(on crate3 pallet1)
	(on crate1 pallet4)
	(on crate7 crate4)
	(at crate5 depot1)
	(at hoist3 distributor1)
	(at pallet8 depot0)
	(at crate4 distributor1)
	(on crate1 pallet5)
	(at hoist5 depot1)
	(at crate3 distributor1)
	(at crate6 distributor0)
	(on crate1 pallet2)
	(on crate0 pallet8)
	(on crate9 crate7)
	(at hoist2 distributor1)
	(available hoist6)
	(at hoist4 distributor1)
	(at pallet8 depot2)
	(available hoist5)
	(on crate6 pallet1)
	(on crate9 crate8)
	(clear pallet9)
	(at crate0 distributor1)
	(on crate1 crate0)
	(on crate4 crate2)
	(on crate2 pallet8)
	(on crate5 pallet3)
	(at crate1 depot0)
	(at hoist0 depot0)
	(on crate4 pallet2)
	(on crate9 crate5)
	(at pallet1 depot1)
	(at crate3 distributor0)
	(on crate2 pallet2)
	(on crate2 crate1)
	(at crate6 distributor1)
	(on crate4 pallet3)
	(at crate4 distributor0)
	(at hoist3 distributor0)
	(on crate3 pallet6)
	(at crate13 depot2)
	(at crate6 distributor2)
	(at pallet2 distributor0)
	(at crate1 depot2)
	(in crate0 truck0)
	(at crate0 distributor2)
	(at crate1 distributor1)
	(at crate9 distributor1)
	(at pallet7 distributor0)
	(on crate6 crate1)
	(at crate3 distributor2)
	(clear crate14)
	(at pallet8 distributor1)
	(on crate8 pallet5)
	(at crate0 distributor0)
	(at hoist1 depot1)
	(at pallet5 distributor2)
	(at crate6 depot1)
	(on crate11 crate6)
	(at crate9 depot2)
	(on crate0 pallet5)
	(clear crate2)
	(at pallet5 depot0)
	(at truck0 depot0)
	(on crate9 pallet7)
	(at pallet4 distributor0)
	(at crate11 distributor0)
	(on crate4 pallet6)
	(on crate11 crate5)
	(on crate0 pallet2)
	(at hoist6 depot1)
	(at crate5 distributor2)
	(at hoist5 distributor2)
	(on crate12 crate10)
	(on crate1 pallet0)
	(at crate2 distributor0)
	(at pallet5 distributor1)
	(at crate11 distributor2)
	(at pallet2 distributor1)
	(at truck0 depot2)
	(on crate2 crate0)
	(at pallet1 distributor0)
	(clear crate1)
	(at pallet3 distributor1)
	(at crate7 distributor2)
	(on crate4 crate3)
	(at crate2 depot2)
	(on crate14 crate11)
	(at pallet6 distributor1)
	(at crate5 distributor1)
	(at crate10 depot1)
	(at crate14 distributor1)
	(on crate2 pallet3)
	(clear crate8)
	(at pallet4 distributor1)
	(at crate1 depot1)
	(at pallet9 distributor0)
	(on crate1 pallet9)
	(at crate2 depot0)
	(at crate12 distributor0)
	(clear pallet3)
	(at crate7 distributor0)
	(available hoist2)
	(at crate8 distributor0)
	(on crate3 pallet8)
	(clear crate3)
	(on crate1 pallet1)
	(at hoist1 distributor0)
	(available hoist1)
	(available hoist7)
	(on crate8 pallet3)
	(clear crate9)
	(clear crate11)
	(on crate13 crate12)
	(at crate12 depot1)
	(clear crate5)
	(available hoist0)
	(at crate5 depot2)
	(on crate12 crate9)
	(clear pallet5)
	(clear crate12)
	(on crate6 crate3)
	(at crate13 distributor2)
	(at truck1 depot1)
	(at truck3 depot1)
	(clear crate4)
	(at pallet6 distributor2)
	(clear pallet2)
	(on crate12 crate11)
	(at crate9 distributor2)
	(on crate10 crate1)
	(on crate9 crate2)
	(at crate11 depot0)
	(at truck2 depot1)
	(at crate8 depot1)
	(on crate14 crate13)
	(clear crate10)
	(at crate7 depot1)
	(at pallet7 depot0)
	(at crate5 depot0)
	(on crate5 crate4)
	(at crate13 distributor0)
	(clear pallet4)
	(at crate9 distributor0)
	(at crate8 depot0)
	(at truck1 distributor2)
	(at crate4 depot2)
	(clear pallet1)
	(on crate2 pallet0)
	(on crate14 pallet9)
	(at crate3 depot2)
	(on crate8 pallet1)
	(at truck1 depot2)
	(at crate13 distributor1)
	(clear crate13)
	(at crate12 distributor1)
	(at crate6 depot0)
	(at hoist2 depot2)
	(on crate10 crate5)
	(at truck1 distributor0)
	(at crate3 depot0)
	(at hoist2 distributor0)
	(at pallet4 depot1)
	(at crate14 distributor0)
	(clear pallet0)
	(at truck1 depot0)
	(on crate5 crate2)
	(at pallet0 depot0)
	(on crate13 crate3)
	(at crate8 distributor2)
	(on crate6 pallet4)
	(at truck0 distributor1)
	(on crate8 crate7)
	(at crate10 distributor1)
	(on crate13 crate4)
	(on crate6 pallet5)
	(at crate0 depot2)
	(on crate5 crate1)
	(at pallet6 depot1)
	(clear pallet6)
	(on crate5 crate0)
	(clear crate7)
	(at crate4 depot0)
	(clear pallet7)
	(at crate7 distributor1)
	(at crate0 depot0)
)
(:add
	(lifting hoist1 crate0)
	(at crate2 distributor0)
	(clear crate2)
	(on crate2 pallet1)
	(available hoist3)
	(at crate0 distributor0)
	(clear crate0)
	(on crate0 pallet3)
	(available hoist1)
	(available hoist0)
	(on crate3 pallet0)
	(at crate3 depot0)
	(clear crate3)
	(on crate5 pallet2)
	(clear crate5)
	(at crate5 distributor0)
	(available hoist1)
	(lifting hoist0 crate3)
	(clear crate2)
	(clear crate1)
	(lifting hoist1 crate5)
	(clear pallet8)
	(lifting hoist3 crate2)
)
(:delete
	(in crate0 truck0)
	(available hoist1)
	(clear pallet1)
	(lifting hoist3 crate2)
	(lifting hoist1 crate0)
	(clear pallet3)
	(clear pallet0)
	(lifting hoist0 crate3)
	(lifting hoist1 crate5)
	(clear pallet2)
	(on crate3 crate2)
	(available hoist0)
	(at crate3 depot0)
	(clear crate3)
	(clear crate5)
	(at crate5 depot1)
	(available hoist1)
	(on crate5 crate1)
	(on crate2 pallet8)
	(clear crate2)
	(at crate2 distributor1)
	(available hoist3)
)
(:goal
	(on crate5 pallet2)
	(on crate4 crate3)
	(on crate3 pallet0)
	(on crate0 pallet3)
	(on crate2 pallet1)
)
(:current
	(on crate4 crate3)
)
