30
(Unload hoist1 crate10 truck1 distributor0)
(Drive truck0 depot0 distributor0)
(Drive truck1 distributor0 distributor1)
(Lift hoist1 crate3 pallet1 distributor0)
(Drive truck0 depot0 distributor1)
(Lift hoist1 crate4 crate3 distributor0)
(Drop hoist0 crate0 crate8 depot0)
(Unload hoist2 crate1 truck1 distributor1)
(Unload hoist0 crate5 truck0 depot0)
(Unload hoist0 crate9 truck0 depot0)
(Unload hoist2 crate5 truck0 distributor1)
(Unload hoist2 crate11 truck0 distributor1)
(Unload hoist1 crate11 truck0 distributor0)
(Unload hoist1 crate5 truck0 distributor0)
(Unload hoist2 crate12 truck0 distributor1)
(Unload hoist1 crate12 truck0 distributor0)
(Drop hoist1 crate10 crate4 distributor0)
(Unload hoist1 crate9 truck0 distributor0)
(Drop hoist0 crate9 crate3 depot0)
(Drop hoist1 crate5 crate7 distributor0)
(Drop hoist1 crate12 crate3 distributor0)
(Drop hoist2 crate12 pallet2 distributor1)
(Drop hoist0 crate5 crate0 depot0)
(Drop hoist1 crate11 crate7 distributor0)
(Drop hoist1 crate9 pallet1 distributor0)
(Drop hoist2 crate5 pallet2 distributor1)
(Drop hoist1 crate3 crate12 distributor0)
(Drop hoist1 crate4 crate11 distributor0)
(Drop hoist2 crate1 crate9 distributor1)
(Drop hoist2 crate11 crate5 distributor1)
5
(:init
	(at crate3 distributor0)
	(at crate4 distributor0)
	(in crate12 truck0)
	(on crate1 pallet2)
	(clear crate4)
	(clear pallet2)
	(on crate7 crate4)
	(lifting hoist0 crate0)
	(at hoist0 depot0)
	(in crate11 truck0)
	(at crate9 distributor1)
	(at hoist1 distributor0)
	(on crate6 pallet1)
	(in crate6 truck1)
	(at crate0 distributor0)
	(in crate1 truck1)
	(in crate13 truck0)
	(at crate7 distributor0)
	(clear crate7)
	(at crate1 distributor1)
	(at truck1 distributor0)
	(at crate3 depot0)
	(on crate2 pallet2)
	(on crate3 crate0)
	(on crate2 crate1)
	(at truck0 depot0)
	(available hoist1)
	(clear crate8)
	(on crate4 crate3)
	(at pallet0 depot0)
	(in crate9 truck0)
	(on crate0 pallet1)
	(on crate9 crate5)
	(available hoist2)
	(at crate6 distributor0)
	(at pallet2 distributor1)
	(on crate0 pallet0)
	(on crate3 pallet1)
	(at crate0 depot0)
	(in crate2 truck0)
	(at pallet1 distributor0)
	(at crate8 depot0)
	(on crate8 pallet0)
	(on crate3 crate1)
	(on crate7 crate6)
	(at hoist2 distributor1)
	(in crate10 truck1)
	(at crate4 depot0)
	(clear crate3)
	(in crate5 truck0)
	(in crate14 truck0)
)
(:add
	(clear crate5)
	(at crate5 depot0)
	(on crate5 crate0)
	(available hoist0)
	(clear crate1)
	(on crate1 crate9)
	(at crate1 distributor1)
	(available hoist2)
	(clear crate9)
	(at crate9 distributor0)
	(available hoist1)
	(on crate9 pallet1)
	(lifting hoist1 crate10)
	(on crate4 crate11)
	(available hoist1)
	(clear crate4)
	(at crate4 distributor0)
	(on crate10 crate4)
	(at crate10 distributor0)
	(available hoist1)
	(clear crate10)
	(lifting hoist1 crate4)
	(clear crate3)
	(at crate12 distributor0)
	(available hoist1)
	(clear crate12)
	(on crate12 crate3)
	(lifting hoist1 crate11)
	(on crate12 pallet2)
	(at crate12 distributor1)
	(clear crate12)
	(available hoist2)
	(lifting hoist2 crate11)
	(at truck0 distributor0)
	(lifting hoist2 crate1)
	(clear pallet1)
	(lifting hoist1 crate3)
	(lifting hoist1 crate12)
	(lifting hoist1 crate9)
	(at truck0 distributor1)
	(at crate11 distributor1)
	(available hoist2)
	(clear crate11)
	(on crate11 crate5)
	(clear crate5)
	(on crate5 pallet2)
	(at crate5 distributor1)
	(available hoist2)
	(clear crate5)
	(on crate5 crate7)
	(available hoist1)
	(at crate5 distributor0)
	(lifting hoist1 crate5)
	(lifting hoist2 crate5)
	(lifting hoist2 crate12)
	(lifting hoist0 crate5)
	(at truck1 distributor1)
	(on crate3 crate12)
	(at crate3 distributor0)
	(available hoist1)
	(clear crate3)
	(available hoist1)
	(on crate11 crate7)
	(clear crate11)
	(at crate11 distributor0)
	(clear crate9)
	(at crate9 depot0)
	(on crate9 crate3)
	(available hoist0)
	(lifting hoist0 crate9)
	(at crate0 depot0)
	(on crate0 crate8)
	(clear crate0)
	(available hoist0)
)
(:delete
	(lifting hoist0 crate5)
	(clear crate0)
	(clear crate9)
	(lifting hoist2 crate1)
	(clear pallet1)
	(lifting hoist1 crate9)
	(available hoist1)
	(in crate10 truck1)
	(lifting hoist1 crate4)
	(clear crate11)
	(lifting hoist1 crate10)
	(clear crate4)
	(on crate4 crate3)
	(available hoist1)
	(clear crate4)
	(at crate4 distributor0)
	(lifting hoist1 crate12)
	(clear crate3)
	(available hoist1)
	(in crate11 truck0)
	(clear pallet2)
	(lifting hoist2 crate12)
	(in crate11 truck0)
	(available hoist2)
	(at truck0 depot0)
	(in crate1 truck1)
	(available hoist2)
	(on crate3 pallet1)
	(at crate3 distributor0)
	(available hoist1)
	(clear crate3)
	(in crate12 truck0)
	(available hoist1)
	(available hoist1)
	(in crate9 truck0)
	(at truck0 depot0)
	(clear crate5)
	(lifting hoist2 crate11)
	(clear pallet2)
	(lifting hoist2 crate5)
	(lifting hoist1 crate5)
	(clear crate7)
	(available hoist1)
	(in crate5 truck0)
	(in crate5 truck0)
	(available hoist2)
	(in crate12 truck0)
	(available hoist2)
	(in crate5 truck0)
	(available hoist0)
	(at truck1 distributor0)
	(clear crate12)
	(lifting hoist1 crate3)
	(clear crate7)
	(lifting hoist1 crate11)
	(lifting hoist0 crate9)
	(clear crate3)
	(in crate9 truck0)
	(available hoist0)
	(lifting hoist0 crate0)
	(clear crate8)
)
(:goal
	(on crate3 crate12)
	(on crate10 crate4)
	(on crate4 crate11)
	(on crate2 crate1)
	(on crate1 crate9)
	(on crate8 pallet0)
	(on crate0 crate8)
	(on crate9 pallet1)
	(on crate12 pallet2)
	(on crate5 crate0)
	(on crate11 crate5)
)
(:current
	(on crate2 crate1)
	(on crate8 pallet0)
)
