18
(Drive truck0 distributor0 distributor1)
(Drive truck0 distributor0 depot0)
(Drop hoist1 crate1 crate3 distributor0)
(Drop hoist0 crate4 crate11 depot0)
(Drop hoist0 crate4 crate3 depot0)
(Unload hoist0 crate9 truck0 depot0)
(Unload hoist0 crate10 truck1 depot0)
(Lift hoist2 crate1 pallet2 distributor1)
(Lift hoist0 crate3 pallet1 depot0)
(Lift hoist1 crate3 crate0 distributor0)
(Unload hoist1 crate9 truck0 distributor0)
(Drop hoist0 crate9 crate11 depot0)
(Drop hoist0 crate10 crate4 depot0)
(Load hoist1 crate3 truck0 distributor0)
(Drop hoist1 crate9 pallet1 distributor0)
(Unload hoist2 crate3 truck0 distributor1)
(Drop hoist2 crate1 crate9 distributor1)
(Drop hoist2 crate3 crate12 distributor1)
1
(:init
	(at crate3 distributor0)
	(at truck0 distributor0)
	(on crate1 pallet2)
	(at crate12 distributor1)
	(on crate11 crate5)
	(at hoist0 depot0)
	(clear crate12)
	(at crate9 distributor1)
	(at hoist1 distributor0)
	(on crate6 pallet1)
	(at truck1 depot0)
	(in crate6 truck1)
	(at crate0 distributor0)
	(in crate13 truck0)
	(at crate1 distributor1)
	(on crate5 crate0)
	(at crate3 depot0)
	(on crate2 pallet2)
	(lifting hoist1 crate1)
	(on crate3 crate0)
	(on crate2 crate1)
	(on crate0 crate8)
	(in crate7 truck1)
	(on crate12 pallet2)
	(at crate11 depot0)
	(at pallet0 depot0)
	(lifting hoist0 crate4)
	(in crate9 truck0)
	(on crate0 pallet1)
	(on crate9 crate5)
	(available hoist2)
	(at crate6 distributor0)
	(at pallet2 distributor1)
	(on crate0 pallet0)
	(clear crate11)
	(on crate3 pallet1)
	(at crate0 depot0)
	(in crate2 truck0)
	(at pallet1 distributor0)
	(at crate8 depot0)
	(on crate8 pallet0)
	(on crate3 crate1)
	(on crate7 crate6)
	(at hoist2 distributor1)
	(in crate10 truck1)
	(at crate4 depot0)
	(clear crate3)
	(at crate5 depot0)
	(in crate14 truck0)
)
(:add
	(at truck0 depot0)
	(clear crate0)
	(lifting hoist1 crate3)
	(at truck0 distributor1)
	(clear pallet2)
	(lifting hoist2 crate1)
	(clear crate1)
	(available hoist1)
	(at crate1 distributor0)
	(on crate1 crate3)
	(lifting hoist0 crate10)
	(clear crate1)
	(on crate1 crate9)
	(at crate1 distributor1)
	(available hoist2)
	(clear crate9)
	(at crate9 distributor0)
	(available hoist1)
	(on crate9 pallet1)
	(lifting hoist2 crate3)
	(available hoist1)
	(in crate3 truck0)
	(lifting hoist1 crate9)
	(on crate3 crate12)
	(clear crate3)
	(available hoist2)
	(at crate3 distributor1)
	(clear crate9)
	(on crate9 crate11)
	(at crate9 depot0)
	(available hoist0)
	(clear pallet1)
	(lifting hoist0 crate3)
	(on crate4 crate11)
	(at crate4 depot0)
	(clear crate4)
	(available hoist0)
	(lifting hoist0 crate9)
	(at crate4 depot0)
	(on crate4 crate3)
	(clear crate4)
	(available hoist0)
	(on crate10 crate4)
	(at crate10 depot0)
	(clear crate10)
	(available hoist0)
)
(:delete
	(at truck0 distributor0)
	(on crate3 crate0)
	(at crate3 distributor0)
	(available hoist1)
	(clear crate3)
	(at truck0 distributor0)
	(clear crate1)
	(on crate1 pallet2)
	(at crate1 distributor1)
	(available hoist2)
	(lifting hoist1 crate1)
	(clear crate3)
	(in crate10 truck1)
	(available hoist0)
	(clear crate9)
	(lifting hoist2 crate1)
	(clear pallet1)
	(lifting hoist1 crate9)
	(in crate3 truck0)
	(available hoist2)
	(lifting hoist1 crate3)
	(available hoist1)
	(in crate9 truck0)
	(lifting hoist2 crate3)
	(clear crate12)
	(lifting hoist0 crate9)
	(clear crate11)
	(on crate3 pallet1)
	(at crate3 depot0)
	(clear crate3)
	(available hoist0)
	(lifting hoist0 crate4)
	(clear crate11)
	(in crate9 truck0)
	(available hoist0)
	(lifting hoist0 crate4)
	(clear crate3)
	(lifting hoist0 crate10)
	(clear crate4)
)
(:goal
	(on crate3 crate12)
	(on crate10 crate4)
	(on crate4 crate11)
	(on crate2 crate1)
	(on crate1 crate9)
	(on crate8 pallet0)
	(on crate0 crate8)
	(on crate9 pallet1)
	(on crate12 pallet2)
	(on crate5 crate0)
	(on crate11 crate5)
)
(:current
	(on crate11 crate5)
	(on crate5 crate0)
	(on crate2 crate1)
	(on crate0 crate8)
	(on crate12 pallet2)
	(on crate8 pallet0)
)
