1
(Drop hoist1 crate1 crate9 distributor0)
2
(:init
	(at truck0 distributor0)
	(on crate3 crate12)
	(on crate1 pallet2)
	(at crate12 distributor1)
	(on crate11 crate5)
	(at hoist0 depot0)
	(on crate10 crate4)
	(on crate9 pallet1)
	(at crate9 distributor1)
	(on crate4 crate11)
	(at hoist1 distributor0)
	(on crate6 pallet1)
	(in crate6 truck1)
	(at crate0 distributor0)
	(in crate13 truck0)
	(at crate1 distributor1)
	(on crate5 crate0)
	(at truck1 distributor0)
	(at crate3 depot0)
	(at crate10 depot0)
	(clear crate10)
	(available hoist0)
	(on crate2 pallet2)
	(lifting hoist1 crate1)
	(on crate3 crate0)
	(on crate2 crate1)
	(on crate0 crate8)
	(in crate7 truck1)
	(on crate12 pallet2)
	(at crate11 depot0)
	(at pallet0 depot0)
	(on crate0 pallet1)
	(on crate9 crate5)
	(available hoist2)
	(at crate3 distributor1)
	(at crate6 distributor0)
	(clear crate9)
	(at pallet2 distributor1)
	(on crate0 pallet0)
	(at crate0 depot0)
	(in crate2 truck0)
	(at crate9 distributor0)
	(at pallet1 distributor0)
	(at crate8 depot0)
	(on crate8 pallet0)
	(on crate3 crate1)
	(on crate7 crate6)
	(at hoist2 distributor1)
	(at crate4 depot0)
	(clear crate3)
	(at crate5 depot0)
	(in crate14 truck0)
)
(:add
	(clear crate1)
	(on crate1 crate9)
	(available hoist1)
	(at crate1 distributor0)
)
(:delete
	(clear crate9)
	(lifting hoist1 crate1)
)
(:goal
	(on crate3 crate12)
	(on crate10 crate4)
	(on crate4 crate11)
	(on crate2 crate1)
	(on crate1 crate9)
	(on crate8 pallet0)
	(on crate0 crate8)
	(on crate9 pallet1)
	(on crate12 pallet2)
	(on crate5 crate0)
	(on crate11 crate5)
)
(:current
	(on crate3 crate12)
	(on crate11 crate5)
	(on crate10 crate4)
	(on crate9 pallet1)
	(on crate4 crate11)
	(on crate5 crate0)
	(on crate2 crate1)
	(on crate0 crate8)
	(on crate12 pallet2)
	(on crate8 pallet0)
)
