(Drive truck1 depot0 distributor0)
(Lift hoist0 crate0 pallet0 depot0)
(Load hoist0 crate0 truck0 depot0)
(Drive truck0 depot0 distributor1)
(Lift hoist2 crate2 crate1 distributor1)
(Load hoist2 crate2 truck0 distributor1)
(Drive truck0 distributor1 depot0)
(Unload hoist0 crate2 truck0 depot0)
(Drive truck0 depot0 distributor1)
(Drop hoist0 crate2 pallet0 depot0)
(Lift hoist2 crate1 pallet2 distributor1)
(Load hoist2 crate1 truck0 distributor1)
(Unload hoist2 crate0 truck0 distributor1)
(Drop hoist2 crate0 pallet2 distributor1)
(Drive truck0 distributor1 distributor0)
(Unload hoist1 crate1 truck0 distributor0)
(Drop hoist1 crate1 crate3 distributor0)
