(Lift hoist0 crate1 pallet0 depot0)
(Load hoist0 crate1 truck1 depot0)
(Drive truck1 depot0 distributor0)
(Lift hoist1 crate0 pallet1 distributor0)
(Load hoist1 crate0 truck1 distributor0)
(Unload hoist1 crate1 truck1 distributor0)
(Drop hoist1 crate1 pallet1 distributor0)
(Drive truck1 distributor0 distributor1)
(Unload hoist2 crate0 truck1 distributor1)
(Drop hoist2 crate0 pallet2 distributor1)
